### ISSUE TITLE
What's the Use Case?

### ISSUE THREAD

**Issue by jasonwhat** [shprink/wordpress-hybrid-client#1]
This looks interesting and promising. Can you explain a little more about what it does and what our use-cases?

**Comment by shprink** [comment]
Well, I have not advertised it yet, there is still work to do (cache, theming etc.) but it basically creates hybrid apps using a simple config file such as this one:

```
{
    "api": {
        "baseUrl": "http://shprinkone.julienrenaux.fr/wp-json"
    },
    "menu": {
        "menu.home": "public.home",
        "menu.categories": "public.taxonomies({ term: 'category' })",
        "menu.tags": "public.taxonomies({ term: 'post_tag' })"
    },
    "cache": {
        "views": 10
    },
    "posts": {
        "posts_per_page": 5,
        "orderby": "date",
        "orderby": "desc",
        "post_status": "publish"
    },
    "translation": {
        "available": {
            "en": {
                "en_US": "en",
                "en_UK": "en"
            },
            "fr": {
                "fr_FR": "fr"
            }
        },
        "prefered": "en"
    }
}
```

Anyone that have a WordPress blog will be able the ability to create a mobile/iOS/Android app like this one: http://m.julienrenaux.fr/ in a blink of an eye :)

**Comment by jasonwhat** [comment]
That's incredible, good to see you using material design and the ionic framework.

**Comment by mingxia** [comment]
Thank you very much fruitful work , every day, see your updates . I'm trying to use your code to make app, a Chinese website .

**Comment by shprink** [comment]
I am about to release v1.0.0, The whole documentation is available here http://wphc.julienrenaux.fr/.

Let me know if you have any trouble.

Cheers

**Comment by shprink** [comment]
v1.0.0 is released BTW @mingxia  ;)
