### ISSUE TITLE
v2 testimonies

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#101]
Hi all,

for v2 release I would love to have testimonies about how users feel creating applications with WPHC.

That's why I am asking you guys, as contributors you might have interesting things to say :)

@CoachBirgit @gonzaloplaza @skibson @guschaves @mingxia @SilentKernel

Let me know if you would be interested in sharing your experience in a short paragraph.

Cheers

**Comment by guschaves** [comment]
Count on me

**Comment by shprink** [comment]
If you guys have an app built with WPHC in the store that would be better BTW. @PierreBresson 

That would be displayed like that: 

![image](https://cloud.githubusercontent.com/assets/1388706/10925801/f9a2292a-8256-11e5-9306-93f73575f606.png)

**Comment by SilentKernel** [comment]
You can also count on me
(sorry for answer relay)

**Comment by shprink** [comment]
Awesome @SilentKernel :)

**Comment by mingxia** [comment]
of course！ME!

**Comment by CoachBirgit** [comment]
Thank! I will test it and will give feedback asap

**Comment by CoachBirgit** [comment]
@shprink First feedback - I´m now on my Mac Mini - the WP-API v2 rules fine! Running devserver on mac compiles a stable preview. On the first view it is ok. 

If WPHC could get running on Windows, I had more time for testing ;-)

Now I am trying to build an app. But I am struggeling with IosEmulator or Android. But it´s another topic.

**Comment by shprink** [comment]
thanks @CoachBirgit, I am sure you will get everything working very soon :)

**Comment by shprink** [comment]
Hi guys,

Happy to announce that v2 is in Beta: http://julienrenaux.fr/2016/01/08/wordpress-hybrid-client-v2-beta/

I will start reshaping the http://wphc.julienrenaux.fr/ page and I would love to have up to 6 testimonies.

If you like the project, find it useful can you send me your text, name and website here?

Thanks a lot in advance

**Comment by shprink** [comment]
The website for v2 is out.
