### ISSUE TITLE
Problems at running build commands

### ISSUE THREAD

**Issue by guschaves** [shprink/wordpress-hybrid-client#102]
I got the following problem using the command npm run install
![printscreen3010](https://cloud.githubusercontent.com/assets/7849140/10853884/547eea24-7f17-11e5-83e2-808a73ab1d98.png)

**Comment by mingxia** [comment]
just need a right android path

**Comment by guschaves** [comment]
@mingxia how can I test if the Path is right, cause? When I execute the command android it opens the Android SDK

**Comment by guschaves** [comment]
![printscreen](https://cloud.githubusercontent.com/assets/7849140/10865295/b75ededc-7fe5-11e5-9273-922ba24846b9.png)

**Comment by shprink** [comment]
Is npm run runAndroid works on device?

**Comment by guschaves** [comment]
So, I executed the command, but anything changed on the device, what was supposed to happen?

**Comment by shprink** [comment]
it is suppose to build the app in dev mode and launch it in the device.
have not tested v2 on device yet but it should be fine

**Comment by guschaves** [comment]
It hadn't built the app, actually where would it be build? 
I ran the command npm run runAndroid
![print20](https://cloud.githubusercontent.com/assets/7849140/10866443/8badfade-800d-11e5-8c83-aec0e91c8bf0.png)

**Comment by harry-saputra** [comment]
same situation with @guschaves , npm run runAndroid on v2.0.0-alpha2 . will try on v1.7.0

**Comment by harry-saputra** [comment]
![image](https://cloud.githubusercontent.com/assets/6844866/11432980/45b5ec3e-94ea-11e5-9bee-60409063601b.png)

**Comment by shprink** [comment]
Which OS @harry-saputra ?

**Comment by harry-saputra** [comment]
i am using elementary OS, ubuntu 14.04 variant

**Comment by shprink** [comment]
@harry-saputra please join the chat https://gitter.im/shprink/wordpress-hybrid-client so I can help you debug

**Comment by shprink** [comment]
v2.0.0-beta01 build works on both android & ios
