### ISSUE TITLE
npm run dumpdev and npm run build error =>  ':dexArmv7Release'

### ISSUE THREAD

**Issue by ishanism** [shprink/wordpress-hybrid-client#105]
When I am trying to build i get this error

---
Execution failed for task ':dexArmv7Release'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/opt/android-sdk/build-tools/23.0.1/dx --dex --output /home/ishanism/wordpress-hybrid-client-1.7.0/platforms/android/build/intermediates/dex/armv7/release --input-list=/home/ishanism/wordpress-hybrid-client-1.7.0/platforms/android/build/intermediates/tmp/dex/armv7/release/inputList.txt
  Error Code:
  	2
---

npm-debug.log and the output on terminal is here:

https://justpaste.it/npm-debug-ishanism

password to open it is:

ishanism

thanks in advance. and sorry for using the above website, I just don't know how to show all these here.

PS: I don't have any devices running greater than 4.2.2 and my AVD is not working, so I have not been able to build it at all. devserver is working fine and it's working without any problem.

**Comment by shprink** [comment]
As I explained I have not tried to build the app yet with v2. This error is due to a conflict between cordova's plugins usually.
I will let you know when fixed. thanks for sharing!

**Comment by imran-monobitstudio** [comment]
Maybe you need to download the "Android Support Library" under "extra" section in Android SDK Manager.

**Comment by shprink** [comment]
Beta01 is out. let me know if this re-appear
