### ISSUE TITLE
App doesn't show images

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#106]
First of all thank you for this really nice project. I installed v2.0.0-alpha1 because v1.7. is not running at all. But the App doesn't show the post images and author images.
![bildschirmfoto 2015-11-04 um 10 54 38](https://cloud.githubusercontent.com/assets/12258469/10934831/7db97872-82e2-11e5-86a3-fc52b66aa0a8.png)

**Comment by PierreBresson** [comment]
Be sure when you run v1.7 that you are following the instruction for this version.
If this screenshot was taken from firefox, it's normal, use chrome and it should work. If not, it might be because your posts don't have featured images.

**Comment by yannicfries** [comment]
It works with Chrome. Thank you :)

**Comment by shprink** [comment]
Thanks @PierreBresson :)
