### ISSUE TITLE
White Screen when I try to open the app in chrome

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#107]
Hi,

I just tried to install v1.7.1. So I did everything that is described in the installation manual and installed the "old" WP REST API Plugin. When I run the devserver and try to open the app in google chrome it says "App ready" but just shows a white screen.

![bildschirmfoto 2015-11-04 um 18 02 25](https://cloud.githubusercontent.com/assets/12258469/10945548/391bb14e-831e-11e5-8004-6ca650973eb1.png)

**Comment by shprink** [comment]
what's the error message? (open the console)

**Comment by yannicfries** [comment]
![bildschirmfoto 2015-11-04 um 18 28 42](https://cloud.githubusercontent.com/assets/12258469/10946307/e5518ee0-8321-11e5-95a2-fed7424640e8.png)

**Comment by shprink** [comment]
the browser console not the terminal please.

**Comment by yannicfries** [comment]
sorry
![bildschirmfoto 2015-11-04 um 18 35 01](https://cloud.githubusercontent.com/assets/12258469/10946480/c79000ac-8322-11e5-9f4a-49517e0d3917.png)

**Comment by yannicfries** [comment]
Ah, I fixed it. I installed v2.0.0-alpha2 first and changed the language to "de" which is not available in v1.7.1
So I ran v2.0.0-alpha2 again and changed the language to en again. Now v1.7.1 works as well. Thank you :)

**Comment by shprink** [comment]
Good catch :)
