### ISSUE TITLE
Pull to refresh on posts page does not work

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#109]
> when there is a new post, i pull down to refresh, it doesn't load new posts. If i go to page like tags, categories for the first time, then it seems to show there but not on posts page. to get new posts, i have to clear data in app info.

**Comment by xvilo** [comment]
I have als problem with pull to refresh on the "homepage", sometimes it is just not there. Not sure under which conditions.

**Comment by shprink** [comment]
I am gonna tackle that this week, thanks
