### ISSUE TITLE
Back button translation is not changing

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#110]
Hi,

It's me again. I tried to change the "Back" translation in lib -> translations -> en.json to " " but the app still shows "Back". I'm using v1.7.1

![bildschirmfoto 2015-11-05 um 13 18 38](https://cloud.githubusercontent.com/assets/12258469/10968177/c161d26c-83bf-11e5-8f14-426974bbe5f6.png)

![bildschirmfoto 2015-11-05 um 13 19 21](https://cloud.githubusercontent.com/assets/12258469/10968191/db1d5c12-83bf-11e5-8605-fcf00d0c5c14.png)

**Comment by shprink** [comment]
https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/language/language.provider.coffee#L40

The back button is translated, if you are not seing it it might be because you need to rebuild the app. Can you try and let me know ?

**Comment by shprink** [comment]
lack of activity
