### ISSUE TITLE
wordpress - hybrid -client does not work in windows ?

### ISSUE THREAD

**Issue by codot91** [shprink/wordpress-hybrid-client#112]
wordpress - hybrid -client does not work in windows ?

**Comment by shprink** [comment]
If you use sygwin it should be fine.

**Comment by codot91** [comment]
what is sygwin ?

**Comment by shprink** [comment]
https://www.cygwin.com/

It is installed if you use git client on Windows

**Comment by CoachBirgit** [comment]
I don´t get it run on Windows 10 in parts. 

npm install > some errors for unsupported modules
npm run installWPHC > ok with git CMD as Administrator
npm run devserver > no compiling (s. attachement)

![webpack-dev-server-error-wphc](https://cloud.githubusercontent.com/assets/1078055/11318378/fd10d26c-904f-11e5-92db-a544ce06ddc4.PNG)

webpack watch in a separate git CMD as Administrator brings ERROR: in multi main...

I´ve researched a lot, but I didn´t found a solution. 

![output-webpack-dev-server](https://cloud.githubusercontent.com/assets/1078055/11318411/8194c966-9051-11e5-814d-e1f3404482f7.PNG)

![output-webpack-watch](https://cloud.githubusercontent.com/assets/1078055/11318412/87a49458-9051-11e5-929d-fa9848293d48.PNG)

Anyone a idea?

Windows 10
npm 3.4.0

I guess, it is a path problem while compiling on Windows.

**Comment by shprink** [comment]
@CoachBirgit it seems to be related to https://github.com/webpack/webpack-dev-server/issues/155. Do you confirm that's the same error?

**Comment by codot91** [comment]
@CoachBirgit  i'am using win 10 to, but too much eror, so i suing dual boot, win 10 and linux (ubuntu). so i using ubuntu, and not eror again.

**Comment by CoachBirgit** [comment]
I´ve tested it yesterday at work on my Windows 7 machine. Same error at compiling. The served comments on the issue, you´ve mentioned is similar, but not the same. All given hints were tested by myself without success. 

It´s really a pain in the ass to develop UNIX driven stuff on a Windows machine. I am happy, that on my PC at work VVV is running. But devserver don´t run in shared folders via Vagrant :( A dualboot with Linux is not that solution, I am searching for. 

If I find a proper solution, I´ll post it here.

**Comment by shprink** [comment]
:+1: thanks @CoachBirgit

**Comment by shprink** [comment]
Closing, duplicate with #39
