### ISSUE TITLE
organizing help

### ISSUE THREAD

**Issue by glenfordwilliams** [shprink/wordpress-hybrid-client#113]
Hi i started using whc this week and so far im loving it. Currently i find the need to reorganize a few things like 
putting featured article up top
8 top headlines after with smaller thumbnails
how can i go about achieving this?

**Comment by codot91** [comment]
this my problem to, how to add headline in home... and show some post by categories in homepage..

**Comment by shprink** [comment]
For now you cannot redefine the templates without having to modify the src code. Templating is something I have in mind and could be the next feature that I release. For now just modify the src template the way you want if you have angularJS/Ionic background.
