### ISSUE TITLE
Support for Italian language

### ISSUE THREAD

**Issue by delitestudio** [shprink/wordpress-hybrid-client#114]
If you can give us directions to translate the application, we will translate it in Italian.

**Comment by shprink** [comment]
Hi, 

You could just copy the english file there https://github.com/shprink/wordpress-hybrid-client/tree/develop/lib/translations and rename it `it.cson`.

Thanks for this.

**Comment by delitestudio** [comment]
Closed in 7177e54ffd707603f49d4e6828886245889ec979
