### ISSUE TITLE
ImgCache is not defined

### ISSUE THREAD

**Issue by imran-monobitstudio** [shprink/wordpress-hybrid-client#118]
Looks like the generated bundle JS has the declared variable ImgCache is after the module.exports = angular.module('wordpress-hybrid-client.cacheImg', []);

ImgCache should be declared before the export.

Thanks

**Comment by shprink** [comment]
tell me more, which version? which OS? This error never happened before.

**Comment by imran-monobitstudio** [comment]
Sorry, I posted the issue in a rush.
The version is v2.0.0-alpha2
OS: Windows 7

I know Windows is not supported but I don't think it has anything to do with the OS. But I could be wrong.
I was able to run the app by moving ImgCache declaration to the top of the bundle JS.

**Comment by shprink** [comment]
yeah it is weird, are you sure it is not a dependency problem? I have just re-installed and it works properly.

Make sure `imgcache.js` is installed in your node_modules.

**Comment by shprink** [comment]
Closing, please feel free to re-open if the error still happens

**Comment by albernaz** [comment]
Shprink, i´m also stucked on this step:

like #107 and this report #118,
i have the"ImgCache is not defined" error on my console and the blank screen.

Yes, imgcache.js is installed on node_modules. and every step of installation runned smothly, like expected, error free.

Version v2.0.0-beta16

Many Thanks in advance

**Comment by shprink** [comment]
Are you on Windows? Windows is not supported. Thanks
