### ISSUE TITLE
Old libraries?

### ISSUE THREAD

**Issue by ang3lx** [shprink/wordpress-hybrid-client#119]
Hello,
during installation of WPHC I see some warnings about plugins
Some are renamed other are outdated

You can find a building log below:

Fetching plugin "org.apache.cordova.dialogs" via npm
WARNING: org.apache.cordova.dialogs has been renamed to cordova-plugin-dialogs. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.dialogs` and `cordova pluWARNING: org.apache.cordova.dialogs has been renamed to cordova-plugin-dialogs. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.dialogs` and `cordova plugin add cordova-plugin-dialogs`.
Fetching plugin "org.apache.cordova.dialogs" via cordova plugins registry
org.apache.cordova.dialogs" will not install due to "/Users/Nello/Documents/PhoneGap/wordpress-hybrid-client/plugins/cordova-plugin-dialogs" being installed.
Fetching plugin "org.apache.cordova.globalization" via npm
WARNING: org.apache.cordova.globalization has been renamed to cordova-plugin-globalization. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.globalization` and `cordova plugin add cordova-plugin-globalization`.
Fetching plugin "org.apache.cordova.globalization" via cordova plugins registry
Fetching plugin "org.apache.cordova.globalization" via cordova plugins registry
org.apache.cordova.globalization" will not install due to "/Users/Nello/Documents/PhoneGap/wordpress-hybrid-client/plugins/cordova-plugin-globalization" being installed.
Fetching plugin "org.apache.cordova.inappbrowser" via npm
WARNING: org.apache.cordova.inappbrowser has been renamed to cordova-plugin-inappbrowser. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.inappbrowser` and `cordova plugin add cordova-plugin-inappbrowser`.
Fetching plugin "org.apache.cordova.inappbrowser" via cordova plugins registry
org.apache.cordova.inappbrowser" will not install due to "/Users/Nello/Documents/PhoneGap/wordpress-hybrid-client/plugins/cordova-plugin-inappbrowser" being installed.
Cross-platform AppRate plugin for Cordova / PhoneGap
Installing "org.pushandplay.cordova.apprate" for ios
Fetching plugin "org.apache.cordova.dialogs" via npm
WARNING: org.apache.cordova.dialogs has been renamed to cordova-plugin-dialogs. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.dialogs` and `cordova plugin add cordova-plugin-dialogs`.
Fetching plugin "org.apache.cordova.dialogs" via cordova plugins registry
org.apache.cordova.dialogs" will not install due to "/Users/Nello/Documents/PhoneGap/wordpress-hybrid-client/plugins/cordova-plugin-dialogs" being installed.
Fetching plugin "org.apache.cordova.globalization" via npm
WARNING: org.apache.cordova.globalization has been renamed to cordova-plugin-globalization. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.globalization` and `cordova plugin add cordova-plugin-globalization`.
Fetching plugin "org.apache.cordova.globalization" via cordova plugins registry
org.apache.cordova.globalization" will not install due to "/Users/Nello/Documents/PhoneGap/wordpress-hybrid-client/plugins/cordova-plugin-globalization" being installed.
Cross-platform AppRate plugin for Cordova / PhoneGap
Fetching plugin "cordova-plugin-x-toast@2.1.1" via npm
Installing "nl.x-services.plugins.toast" for android
Installing "nl.x-services.plugins.toast" for ios
Fetching plugin "nl.x-services.plugins.socialsharing@4.3.19" via npm
WARNING: nl.x-services.plugins.socialsharing has been renamed to cordova-plugin-x-socialsharing. You may not be getting the latest version! We suggest you `cordova plugin rm nl.x-services.plugins.socialsharing` and `cordova plugin add cordova-plugin-x-socialsharing`.

**Comment by mingxia** [comment]
just plugin author‘s tips，in fact，we are use newest version。

**Comment by shprink** [comment]
@ang3lx these warnings may be coming from a dependency, we are already using the right plugin names. You can see the complete list here: https://github.com/shprink/wordpress-hybrid-client/blob/develop/package.json#L25
