### ISSUE TITLE
No iOS statusbar

### ISSUE THREAD

**Issue by xvilo** [shprink/wordpress-hybrid-client#126]
Hello,

I am very new to iOS- and node development, so it could be a silly thing (my apologies in advance), but.
When I generated the iOS xcode project file and build it as described in the docs the status bar is missing. Well, not really missing. When you open the app the status bar is on the splash screen. It turns from black to white and then disappears in the rest of the app. 

I have no idea why this happens. Could be a little bug, could be something I missed. Hope somebody could help me out! 

Thanks in advance,

//Sem

**Comment by shprink** [comment]
It depends on your conf. By default the status bar is hidden.

Try changing your conf

```
"cordova":
    "statubar":
        "show": true
```

**Comment by xvilo** [comment]
Hahaha yes! Thank you, I just found out myself. In the docs you said "ALL your config files are in config/" so I looked everywhere. But needed to change this in config.xml in the root directory!

**Comment by shprink** [comment]
If things are not clear enough, do not hesitate to send me pull requests with documentation addition :)
