### ISSUE TITLE
installWPHC not found

### ISSUE THREAD

**Issue by rafaelborgate** [shprink/wordpress-hybrid-client#127]
Hi,

I am trying to install WPHC but the run npm install PHC command displays the following error:

![captura de tela 2015-12-15 as 11 21 26](https://cloud.githubusercontent.com/assets/16305893/11811675/183b2ad4-a31e-11e5-943d-e84088f3fb83.png)

Help me please.

**Comment by shprink** [comment]
Sorry I made a mistake yesterday on `develop`. It should be fine now
