### ISSUE TITLE
initial black screen on android

### ISSUE THREAD

**Issue by revolunet** [shprink/wordpress-hybrid-client#13]
On android 5, we get a black screen after the splash screen. maybe delay it until the view is fully rendered ?

**Comment by shprink** [comment]
I have it too, thanks for letting me know.

**Comment by abedalzain** [comment]
I did not have it yet, but maybe you have to add :
cordova plugin add cordova-plugin-whitelist

**Comment by shprink** [comment]
Closing cannot reproduce anymore
