### ISSUE TITLE
Problem with dutch translations

### ISSUE THREAD

**Issue by xvilo** [shprink/wordpress-hybrid-client#130]
Just updated everything but for some reason i get this console output... 

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module wordpress-hybrid-client due to:
Error: Cannot find module './nl'.
```

**Comment by shprink** [comment]
I have just merge a new language that's the reason/ I have just pulled develop and I do not have any problem.

You know that `develop` branch is unstable right? Please use tagged version if you do not want to have errors on a daily basis

**Comment by shprink** [comment]
I guess if you reload webpack-dev-server it is gonna be fine. Please close if ok

**Comment by xvilo** [comment]
No, I have reloaded multiple times, also did a `git checkout v2.0.0-alpha2` but i still have the same error...

**Comment by shprink** [comment]
The dutch translation does not exist on `v2.0.0-alpha2` so this must be in your config files.

**Comment by xvilo** [comment]
Ah solved it. File nl.cson was indeed non-existent. hahaha
