### ISSUE TITLE
when I do "sudo npm run devserver", there is a error on "compileevents.js:141"

### ISSUE THREAD

**Issue by yao3060** [shprink/wordpress-hybrid-client#131]
> wordpress-hybrid-client@1.7.3 devserver /Users/yaoyingying/Sites/wphc/v1
> webpack-dev-server --port 8080 --json --progress

  0% compileevents.js:141
      throw er; // Unhandled 'error' event
      ^

**Comment by shprink** [comment]
Why `sudo` ?

I recommend installing your code in your home folder so you will not need sudo. Please try and let me know

**Comment by shprink** [comment]
Closing for lack of response
