### ISSUE TITLE
Remove module from webpack

### ISSUE THREAD

**Issue by Mte90** [shprink/wordpress-hybrid-client#132]
As an example i want that webpack is fast on compiling but i can't  find a way to remove syntax higlight, in the config is disabled but is parsed by webpack.

**Comment by shprink** [comment]
Yep, I have tried several times to filter it if the `enable` option is set to false in the config but I can't make it work (though I know it is possible).

https://github.com/shprink/wordpress-hybrid-client/blob/develop/webpack.config.js#L89

If you happen to make it work please share :)

For the time being it will stay bundled to the app.
