### ISSUE TITLE
"Failed at the wordpress-hybrid-client@2.0.0-alpha5 installWPHC script 'cd scripts && node ./install.js'."

### ISSUE THREAD

**Issue by wessilfie** [shprink/wordpress-hybrid-client#137]
Hi,

I've been trying to follow the installation steps, but keep getting an error during the npm run installWPHC step. Here's the error I keep getting. Had a few other people try to follow the instructions and we all got the same/similiar errors. Any idea how to fix this? 
<img width="774" alt="screen shot 2015-12-24 at 10 59 06 pm" src="https://cloud.githubusercontent.com/assets/10506187/12000828/4a68cbbc-aa92-11e5-9e4c-37eee21465a3.png">

**Comment by Prabhat36** [comment]
set android sdk path to ANDROID_HOME

**Comment by shprink** [comment]
@wessilfie be aware that v2 is in alpha version and under development.

From the screenshot I can see that you run 1.7. Please upgrade to 1.7.3:

```
git checkout v1.7.3
```

**Comment by wessilfie** [comment]
@shprink Thank you, that fixed the error! Also, in the installation guide it says that after running "npm installWPHC" I should have personal files available in a config folder, but I'm not seeing any config folder created by default. Is that supposed to be the case or am I missing something? I also added my site url to config.prod.json (couldn't find a .dev one) but when I run ionic serve I get "Error: ENOENT"  and a comment about the html file. Is this supposed to happen?

**Comment by shprink** [comment]
if you use the v1.7.3 please use the docs at the same version. You can
select the version on the documentation site or on github.

**Comment by wessilfie** [comment]
Fixed a lot of issues, but under the step "npm run devserver" for v1.7.3
<img width="864" alt="screen shot 2015-12-25 at 3 32 15 pm" src="https://cloud.githubusercontent.com/assets/10506187/12004615/c8926a9a-ab1c-11e5-9d11-987a5bc1729b.png">

any tips for debugging this?

**Comment by shprink** [comment]
Unexpected token means your json file is not valid. Please use an online
validator to fix it.
