### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by Mte90** [shprink/wordpress-hybrid-client#140]
I have see that https://github.com/shprink/wp-api-angularjs support the login but that boilerplate don't have a page for that.

**Comment by shprink** [comment]
Yes it is not plain to support login in WPHC. What would you need it for?

**Comment by Mte90** [comment]
To show specific result in the json response.

**Comment by shprink** [comment]
ok, it is a good use case (for custom posts for instance) but we need to make sure the login is secured (oauth2 is not possible with WP-API for now) which I believe is not trivial for single page apps.
I know there is some WP plugins/filters that could allow that but have not put time into yet.
