### ISSUE TITLE
Wants to reduce apk size.. 

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#142]
Dont have any idea how to remove crosswalk plugin please help me.. I'm new to Cordova and ionic project

**Comment by shprink** [comment]
`cordova plugin rm cordova-plugin-crosswalk-webview`

**Comment by Prabhat36** [comment]
![screenshot from 2016-01-20 19-33-58](https://cloud.githubusercontent.com/assets/14105960/12450996/cd31a21a-bfac-11e5-8c71-3f60a9c6ebd4.png)

**Comment by Prabhat36** [comment]
help please

**Comment by shprink** [comment]
With the latest version you can use crosswalk lite instead. The size of the apk will be around 15MB

Docs => https://github.com/shprink/wordpress-hybrid-client/blob/develop/BUILD.md#crosswalk

**Comment by Prabhat36** [comment]
cordova plugin rm cordova-plugin-crosswalk-webview@version
apk size will be 4 or 5 mb
without crosswalk app works more better than with crosswalk.
@shprink you should remove crosswalk plugin from getting install from code

**Comment by shprink** [comment]
>  without crosswalk app works more better than with crosswalk.

it depends on your device. Crosswalk is still highly recommended, but you can remove it if you want.

**Comment by mingxia** [comment]
use crosswalk lite is best! just 15M
