### ISSUE TITLE
sudo run npm build results in error v2.0.0beta01

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#143]
Hi,

when I try to build the iOS App with "sudo run npm build"  the following error occurs:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.3.12
3 info using node@v0.12.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle wordpress-hybrid-client@2.0.0-beta01~prebuild: wordpress-hybrid-client@2.0.0-beta01
6 silly lifecycle wordpress-hybrid-client@2.0.0-beta01~prebuild: no script for prebuild, continuing
7 info lifecycle wordpress-hybrid-client@2.0.0-beta01~build: wordpress-hybrid-client@2.0.0-beta01
8 verbose lifecycle wordpress-hybrid-client@2.0.0-beta01~build: unsafe-perm in lifecycle true
9 verbose lifecycle wordpress-hybrid-client@2.0.0-beta01~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/manufaktur/src/v2.0.0beta1/wordpress-hybrid-client/node_modules/.bin:/Users/manufaktur/.node/bin:/Users/manufaktur/.node/bin:/Users/manufaktur/.node/bin:/Users/manufaktur/local/node/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle wordpress-hybrid-client@2.0.0-beta01~build: CWD: /Users/manufaktur/src/v2.0.0beta1/wordpress-hybrid-client
11 silly lifecycle wordpress-hybrid-client@2.0.0-beta01~build: Args: [ '-c', 'bash ./release.sh' ]
12 silly lifecycle wordpress-hybrid-client@2.0.0-beta01~build: Returned: code: 1  signal: null
13 info lifecycle wordpress-hybrid-client@2.0.0-beta01~build: Failed to exec build script
14 verbose stack Error: wordpress-hybrid-client@2.0.0-beta01 build: `bash ./release.sh`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at EventEmitter.emit (events.js:110:17)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at ChildProcess.emit (events.js:110:17)
14 verbose stack     at maybeClose (child_process.js:1015:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
15 verbose pkgid wordpress-hybrid-client@2.0.0-beta01
16 verbose cwd /Users/manufaktur/src/v2.0.0beta1/wordpress-hybrid-client
17 error Darwin 15.2.0
18 error argv "node" "/usr/local/bin/npm" "run" "build"
19 error node v0.12.7
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error wordpress-hybrid-client@2.0.0-beta01 build: `bash ./release.sh`
22 error Exit status 1
23 error Failed at the wordpress-hybrid-client@2.0.0-beta01 build script 'bash ./release.sh'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wordpress-hybrid-client package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     bash ./release.sh
23 error You can get their info via:
23 error     npm owner ls wordpress-hybrid-client
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shprink** [comment]
If you are around maybe we can discuss on the chat: https://gitter.im/shprink/wordpress-hybrid-client

**Comment by shprink** [comment]
Closing as beta02 should fix that. @yannicfries do not hesitate to reopen if the problem re-appears
