### ISSUE TITLE
Error buildind the app

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#144]
Hi all,

today I tried to build the app in my ubuntu 14.04 64bit but with errors:

steps:

1. git clone https://github.com/shprink/wordpress-hybrid-client.git

2. cd wordpress-hybrid-client
3. npm install
4. npm run installWPHC
5. npm run devserver

up this point, all works fine, and I can see the default julien's blog

now when I try to build for android... first error

6. ionic state restore

You can see the log here
http://pastebin.com/XUCvhmgh

...so I tried to uninstall the cordova-plugin-google-analytics an reinstall by hand all plugins presents in the previous version. Here the list

max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ cordova plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
com.telerik.plugins.nativepagetransitions 0.5.7 "Native Page Transitions"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-crosswalk-webview 1.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-file-transfer 1.4.0 "File Transfer"
cordova-plugin-globalization 1.0.2 "Globalization"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-googleplayservices 19.0.3 "Google Play Services for Android"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-network-information 1.1.0 "Network Information"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-statusbar 2.0.0 "StatusBar"
cordova-plugin-velda-devicefeedback 0.0.2 "DeviceFeedback"
cordova-plugin-whitelist 1.2.0 "Whitelist"
nl.x-services.plugins.socialsharing 4.3.19 "SocialSharing"
nl.x-services.plugins.toast 2.1.1 "Toast"
org.pushandplay.cordova.apprate 1.1.7 "AppRate"
max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ 

then remove the platforms an reinstall android:

max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ cordova platform remove android ios
max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ cordova platform add android 

No errors... but....building

http://pastebin.com/fA9XJUx6

for information... here my system

my ionic is the last 
max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ ionic -v
1.7.12

my android sdk is updated and (I think) complete for this system

![sdk2](https://cloud.githubusercontent.com/assets/5683921/12269758/43fd746a-b953-11e5-805b-b03d20403156.png)

![sdk](https://cloud.githubusercontent.com/assets/5683921/12269765/49f2dc66-b953-11e5-904a-619a74727f1e.png)

someone has found same errors?

MaX

**Comment by shprink** [comment]
Thanks for this details issue!

Can you try changing `cordova-plugin-google-analytics@0.7.1` to `cordova-plugin-google-analytics@0.8.1`

and `ionic state restore` again?

**Comment by shprink** [comment]
there is a problem with this cordova-plugin-google-analytics plugin and googleplayservices

**Comment by maxlinux2000** [comment]
max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ cordova plugin remove cordova-plugin-google-analytics
Uninstalling cordova-plugin-google-analytics from android
Removing "cordova-plugin-google-analytics"
max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ cordova plugin add cordova-plugin-google-analytics@0.8.1
Fetching plugin "cordova-plugin-google-analytics@0.8.1" via npm
Installing "cordova-plugin-google-analytics" for android
max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist@1.0.0
cordova plugin add cordova-plugin-inappbrowser@1.0.1
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-file@2.1.0
cordova plugin add cordova-plugin-file-transfer@1.2.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-network-information@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add org.pushandplay.cordova.apprate@1.1.7
cordova plugin add cordova-plugin-x-toast@2.1.1
cordova plugin add nl.x-services.plugins.socialsharing@4.3.19
cordova plugin add com.ionic.keyboard@1.0.4
cordova plugin add cordova-plugin-googleplayservices@19.0.3
cordova plugin add cordova-plugin-statusbar@1.0.1
cordova plugin add cordova-plugin-google-analytics@0.7.1
cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5 
cordova plugin add phonegap-plugin-push@1.2.3
cordova plugin add cordova-plugin-crosswalk-webview@1.4.0
Restore plugins is complete

Ionic state restore completed

max@U9200:~/XDK/WPHC/wordpress-hybrid-client$ 


:-D

ok, no errors! 
now I try to build

**Comment by maxlinux2000** [comment]
sorry, but there are more errors:

http://pastebin.com/XDm7qKR8

for the moment I won't use google analitic... can I unistall  cordova-plugin-googleplayservices and 
cordova-plugin-google-analytics?

the app can works without there twho plugins?

**Comment by shprink** [comment]
Just remove it for now. Will check this issue, thanks

**Comment by maxlinux2000** [comment]
where is the list of plugins to install used from "ionic state restore" ?

**Comment by shprink** [comment]
at the end of package.json

**Comment by shprink** [comment]
I have updated to the latest google play service and I can reproduce!

**Comment by maxlinux2000** [comment]
good!! :) 
meanwhile I'm compiling without these two plugins. I tried to "cordova build" but although the building reaches the end without errors, then android5, not let me install the apk on my mobile ... strange.

**Comment by maxlinux2000** [comment]
I can build usign "npm run build", sign the apk and install in my phone.
but now... "Error: class cordova not found" and then white screen. :( 

I will investigate how to downgrade in android studio, the google play service

**Comment by shprink** [comment]
how is `npm run android` doing ?

**Comment by maxlinux2000** [comment]
sorry... too late :)
I have just donwgrade the google_play_service to the version 25 and I'm restarting the WPHC environment, in order to see if I can see working WPHC in my phone.

**Comment by maxlinux2000** [comment]
houston, we have a problem :(

downgrading the google_play_service to #25 is not enougth
So I have remove the cordova-plugin-google-analytics from the list.

So I can compile and build without errors... but with
"npm run android" I can read in my phone:

Error Class cordova not found
and then 
Application error the connection to the server was unsucessfull.( file://android_asset/www/index.html)

I'm so sad... :(

**Comment by shprink** [comment]
There is a conflict with push notif plugin. WOrking on it

**Comment by maxlinux2000** [comment]
we are all with you! :D

**Comment by shprink** [comment]
Getting there :P

**Comment by shprink** [comment]
Why do not you join the chat? https://gitter.im/shprink/wordpress-hybrid-client

**Comment by shprink** [comment]
@maxlinux2000 can you please:

Update android dependencies like this:

![image](https://cloud.githubusercontent.com/assets/1388706/12277502/3b0d91d0-b941-11e5-8286-4e07975e48cb.png)

then : 

```
git checkout develop
git pull origin develop
rm -rf plugins/ platforms/ node_modules/
npm install && npm run restore
npm run android (with device plugged in)
```

If it works (works on my side) I will release beta02 right away.

**Comment by maxlinux2000** [comment]
YOU ARE THE CHAMPION!!! YOU ARE THE CHAMPIOOOOON!!!!!

https://45.media.tumblr.com/db40d681639e0e53535e5e57577e7f07/tumblr_n82tqtEc7g1tbx44fo1_500.gif

now the build is working in my phone! :dancer:

**Comment by shprink** [comment]
Haha thanks for your help
releasing beta02 :)
