### ISSUE TITLE
add pages in the app

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#145]
a stupid question.

I want to add some statics pages (in html, css and javascript) to WPHC.... what is the best way?
Put the files in config/templates? or better modifying something in lib?

**Comment by shprink** [comment]
Can't you use WP pages to do that? That's what I did for the about page.

**Comment by maxlinux2000** [comment]
no, is different, because the blog is secondary for my scope.

Actually i'm using the original index.html and I hide the div containig the bundle.xxxx.js with a javascript button that change the css property (display: none/ display:block), so I can use the entire index.html in order to display my stuffs.
Then when I press the button, i switch the stuffs with che wphc in a second.

well... no problems. I will create my own script in order to modify the original www/index.html and merge my stuffs with wphc.

**Comment by shprink** [comment]
Yeah it seems very specific to your app. Closing.
