### ISSUE TITLE
Names in comments are missing

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#146]
Hi, I'm using v2.0.0-beta01 and the app doesn't show names in comments.

![bildschirmfoto 2016-01-20 um 17 22 32](https://cloud.githubusercontent.com/assets/12258469/12455101/9745c53a-bf9a-11e5-9cf6-531e5ef1493f.png)

**Comment by shprink** [comment]
You are right! I suggest you update to beta02

```
git fetch --all
git checkout v2.0.0-beta02
rm -rf platforms/ plugins/ node_modules/
npm install && npm run restore
```

**Comment by yannicfries** [comment]
Oh sorry. Haven't seen that there is already a beta02. My mistake!

**Comment by shprink** [comment]
The issue also happens in beta02 ;)

beta01 has a problem with android, depending on your install. Beta02 is fine

**Comment by yannicfries** [comment]
Oh ok :laughing: I'm just using the iOS App :)

**Comment by shprink** [comment]
Fixed
