### ISSUE TITLE
unfortunately app stopped

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#147]
hi to reduce apk size i change the version code to this in realease.sh 
gulp cordova:release --minSdkVersion=14
  and i have succesfully build the apk of 4.1mb ..
but when i install the app it says "unfortunately app stopped
![screenshot_2016-01-22-15-10-57](https://cloud.githubusercontent.com/assets/14105960/12507258/9785d810-c11a-11e5-8e5b-7cd76ee22add.png)
"
![screenshot_2016-01-22-15-08-40](https://cloud.githubusercontent.com/assets/14105960/12507209/4ff1e070-c11a-11e5-851b-9c8901177a65.png)
ly app has stopped error please help..

**Comment by shprink** [comment]
Hi,

I you have removed crosswalk do not use release.sh. The code is written to take x86 and arm7 architecture files and sign them.

You will need to modify release.sh, this part https://github.com/shprink/wordpress-hybrid-client/blob/develop/release.sh.dist#L24-L30 needs to be changed to target the file created by the build.

For instance `platforms/android/build/outputs/apk/android-x86-release-unsigned.apk` and `platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk` will not exist for you. If they do exist, you are doing something wrong.

You will find a lot of resources on the internet on how to sign your app, just follow them, this is a normal hybrid app like others.

Good luck

**Comment by Prabhat36** [comment]
i have got 3 apk files at this location platforms/android/build/outputs/apk/ 
1.android-x86-release-unsigned.apk= 24mb
2.android-armv7-release-unsigned.apk= 27mb
3.android-release-unsigned.apk=4.1mb
 so i just change realease.sh part like below to singn 4.1mbs apk

jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${ANDROID_KEY_PATH} platforms/android/build/outputs/apk/android-x86-release-unsigned.apk ${ANDROID_KEY_ALIAS}
    jarsigner -verify -certs platforms/android/build/outputs/apk/android-x86-release-unsigned.apk
    ${ANDROID_ZIPALIGN} -vf 4 platforms/android/build/outputs/apk/android-x86-release-unsigned.apk ./build/esamanjas-x86.apk

   jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${ANDROID_KEY_PATH} platforms/android/build/outputs/apk/android-release-unsigned.apk ${ANDROID_KEY_ALIAS}
    jarsigner -verify -certs platforms/android/build/outputs/apk/android-release-unsigned.apk
    ${ANDROID_ZIPALIGN} -vf 4 platforms/android/build/outputs/apk/android-release-unsigned.apk ./build/wphc-android-x86.apk

   jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${ANDROID_KEY_PATH} platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk ${ANDROID_KEY_ALIAS}
    jarsigner -verify -certs platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk
    ${ANDROID_ZIPALIGN} -vf 4 platforms/android/build/outputs/apk/android-armv7-release-unsigned.apk ./build/wphc-android-armv7.apk


but that 4.1mbs app is not working, it giving same error app has stopped.. please help and thanks in advance

**Comment by shprink** [comment]
You should not have 3 packages it is not possible.

When you build the app, android tells you which file it created. Check the terminal dump to know.

Is the crosswalk app working?

**Comment by Prabhat36** [comment]
now i just run this command "npm run buildProdAndroid" apk build with 4.1mb , i have signed the apk manually still when i launch app its saying "app has stopped" i dont knw why? can you give me steps that how can i build app without crosswalk. ?

**Comment by shprink** [comment]
Check why it is crashing by looking at the logs http://developer.android.com/tools/help/logcat.html

Is the crosswalk app working?

**Comment by Prabhat36** [comment]
crosswalk app is working gr8. without crosswalk app is not working..
did you ever try to build apk without crosswalk?

**Comment by Prabhat36** [comment]
when i removed the crosswalk using command. it removed the crosswalk but gives the error 
![screenshot from 2016-01-20 19-33-58](https://cloud.githubusercontent.com/assets/14105960/12534939/60fe2eec-c295-11e5-8b32-1eef52df538b.png)

**Comment by Prabhat36** [comment]
in config.xml there is  sdkVersion=14 , but in my android sdk there is no api 14 available, 
should i need to change it to 15 and install api 15 in android sdk?

**Comment by Prabhat36** [comment]
build log
[build.zip](https://github.com/shprink/wordpress-hybrid-client/files/102235/build.zip)

**Comment by Prabhat36** [comment]
[alogcat.2016-01-24-18-03-28+0530.txt](https://github.com/shprink/wordpress-hybrid-client/files/102337/alogcat.2016-01-24-18-03-28.0530.txt)
