### ISSUE TITLE
Handle Windows Phone

### ISSUE THREAD

**Issue by aloisdg** [shprink/wordpress-hybrid-client#15]
Hello,

It would be nice to add Windows Phone support to the list.

Cheers,

**Comment by shprink** [comment]
If you are interested on testing it, that would be great (need to check ionic/cordova plugins status on Windows Phones) but right now it is not the priority.

Thanks

**Comment by aloisdg** [comment]
I can test it on a Lumia 435, Lumia 820, Lumia 620 and 520 and 930. Keep in touch.

**Comment by shprink** [comment]
1.2 has been released, 1.3 is about to land as well, have you got the time to check Windows support so far @aloisdg ?

**Comment by aloisdg** [comment]
No sorry. I didn't have the time.

**Comment by shprink** [comment]
Closing by lack of input

**Comment by aloisdg** [comment]
Sorry. Good continuation.
