### ISSUE TITLE
System-webview apk

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#154]
$ cordova build --release -- --minSdkVersion=21
used above command and it builds "android-debug-unaligned.apk" and "android-debug.apk" in this path = /platforms/android/build/outputs/apk 

logcat output:
I/Choreographer(20642): Skipped 30 frames!  The application may be doing too much work on its main thread.
W/InputMethodManager(20642): Ignoring onBind: cur seq=681, given seq=680
I/art     (20642): Explicit concurrent mark sweep GC freed 1742(130KB) AllocSpace objects, 0(0B) LOS objects, 48% free, 4MB/8MB, paused 714us total 138.950ms

**Comment by shprink** [comment]
Maybe a question for Cordova itself do not you think?

**Comment by Prabhat36** [comment]
now i started from installation again,, this time i avoid to install cordovas all plugins.. and at the time of build error comes that "failed to find ANDROID_HOME envairmental variable" ,, 


![screenshot from 2016-01-26 20-28-05](https://cloud.githubusercontent.com/assets/14105960/12584002/6e39c364-c46b-11e5-8545-92aa9275931c.png)

**Comment by shprink** [comment]
First of all update your app to Beta02 and the error you have is pretty well known, you have not installed android correctly. You will find a lot of resource about this on Google

**Comment by Prabhat36** [comment]
im using beta02,,, dose the problem is occurring because of i have not istalled cordovas plugins?

**Comment by shprink** [comment]
From what I can see your android SDK is not correctly installed. ANDROID_HOME MUST be defined.

**Comment by Prabhat36** [comment]
sorry im using v2.0.0-alpha2 ... and android sdk is properly installed .. when i run command "android" its execute well..

**Comment by shprink** [comment]
run the command yourself `cordova build android --device --release` and see the result but it is gonna be the same

**Comment by Prabhat36** [comment]
so what should i do now? and thanks for all you are really good

**Comment by shprink** [comment]
switch to beta02

```
git fetch --all
git checkout v2.0.0-beta02
```

re install:

```
rm -rf platforms/ plugins/ node_modules/
npm install && npm run restore
```

then retry: `cordova build android --device --release`

You can also come talk on the chat if that's easier for you https://gitter.im/shprink/wordpress-hybrid-client

**Comment by Prabhat36** [comment]
hahahahahahaha sir finally .... i used this command to remove crosswalk plugin 
"sudo npm run cordova plugin rm cordova-plugin-crosswalk-webview@1.2.0"
and then crosswalk is removed. 
and app is build with system webView..
love you sir..  happyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by shprink** [comment]
Congrats!!!

**Comment by Prabhat36** [comment]
authers image is not displaying in app?

**Comment by shprink** [comment]
Works for me

**Comment by Prabhat36** [comment]
FOR BUILDING  system webView APP USE MY BELOW CODE..

1. APP SIZE = 4MB
2. WORKS FINE WITH ALL VERSION OF ANDROID SELECT MINIMUM SDK =15

# my "install_cordova.sh"  code

#!/bin/sh
# TESTS PLEASE DO NOT USE YET

set -e

path=`dirname $0`
cd $path

read -p "Which platforms do you want to build? (android ios): " platforms
platforms=${platforms:-"android ios"}

# cleanup
echo "removing platforms/ plugins/"
rm -rf platforms/
rm -rf plugins/

# install platforms and plugin
echo "installing platforms "$platforms

if [[ " ${platforms[*]} " == *" android "* ]]; then
    npm run platformAddAndroid
fi

if [[ " ${platforms[*]} " == *" ios "* ]]; then
    npm run platformAddIOS
fi

npm run pluginAddAll

sudo npm run cordova plugin rm cordova-plugin-crosswalk-webview@1.2.0

# **_AND "release.sh" code _**

set -e

ANDROID_ZIPALIGN="/home/prabhat/android-sdk-linux/build-tools/22.0.1/zipalign"
ANDROID_KEY_PATH="/home/prabhat/wordpress-hybrid-client/P.keystore"
ANDROID_KEY_ALIAS="Savi"

read -p "Release major, minor or patch? " version
version=${version:-""}

read -p "Which platforms do you want to build? (android ios): " platforms
platforms=${platforms:-"android ios"}

# updgrade version before release
gulp cordova:release --${version}
#cordova build --release --minSdkVersion=14 
# package the app
npm run dumpprod

if [[ " ${platforms[*]} " == *" android "* ]]; then
   # npm run buildProdAndroid
npm run cordova build --release -- --minSdkVersion=15


fi

if [[ " ${platforms[*]} " == *" ios "* ]]; then
    npm run buildProdIOS

    rm -rf ./build/ios.app
    mv ./platforms/ios/build/device/*.app ./build/ios.app
    xcrun -sdk iphoneos PackageApplication -v $PWD/build/ios.app
    sigh resign ./build/ios.ipa
fi
