### ISSUE TITLE
Refresh on Resume

### ISSUE THREAD

**Issue by DDfakt** [shprink/wordpress-hybrid-client#155]
Hi Julien,

first of all, thank you for your great work!

Now my question:

Is it easily possible to refresh the posts list on app resume?
I know there exists an ionic-function, but i can't get it together ... maybe you or somebody else can help.

Thanks!

**Comment by shprink** [comment]
https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.resume.html

`document.addEventListener("resume", yourCallbackFunction, false);`

If you want to refresh the list of post you can hack the code and call this function upon the resume evetn:

https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/abstract/AbstractList.js#L29-L36
