### ISSUE TITLE
how to add Folder,Tag, twitter, facebook to the post.. 

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#160]
in my app there is only two options at the end of post 1. bookmark 2. Share, how to add folder tag facebook etc options..
![screenshot_2016-02-02-16-26-03](https://cloud.githubusercontent.com/assets/14105960/12747512/65fddc26-c9ca-11e5-8a3e-3da73496450c.png)

**Comment by shprink** [comment]
If your post has categories and tags you should have two more button on the left part of the toolbar.
This toolbar can be customized using custom templates.
