### ISSUE TITLE
npm run android，application error theconnection to the servre..

### ISSUE THREAD

**Issue by xiaoxixiaoxi** [shprink/wordpress-hybrid-client#168]
On mac, npm run android error: application error theconnection to the servre ..
What is the solution?
O (∩_∩) O Thank you @xvilo @andrebalza @CoachBirgit

**Comment by shprink** [comment]
Make sure you have android correctly installed first.

A dump of the terminal trace would be appreciated.

**Comment by mayurss786** [comment]
I also seen this error on slow internet connection, all the apps which are built with ionic are showing this error, so this ionic bug

This is my thought, may be I'm wrong

**Comment by shprink** [comment]
Thanks @mayurss786, closing this :)
