### ISSUE TITLE
Menu 

### ISSUE THREAD

**Issue by uswakamili** [shprink/wordpress-hybrid-client#169]
How do i edit menu and add custom pages and remove some pages ?

**Comment by shprink** [comment]
https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md#configmenujson

**Comment by uswakamili** [comment]
I want to remove Taxonomies type and post type on my menu i can't figure out how even after checking That link kindly assist

**Comment by shprink** [comment]
Just modify the content of `menu.json`, remove the items you do not want or add new ones

**Comment by uswakamili** [comment]
./config/menu.json
Module build failed: SyntaxError: Unexpected end of input
  at Object.parse (native)
  at Object.module.exports (/home/ndugus/app3/node_modules/json-loader/index.js:7:48)
 @ ./lib/config.js 17:22-52

**Comment by shprink** [comment]
If you do not know about json file format you will have hard time using this project or any other BTW.

Make sure your json is valid: http://jsonlint.com/

**Comment by uswakamili** [comment]
Thanks it finally worked. I was trying to remove some pages and pull a buddypress registration page.  When i click on it says open in browser.

**Comment by deepanshu-kumar** [comment]
I want to make login and registration functionality on wordpress hybrid client.How can I do this. Any help would be appreciated.

**Comment by shprink** [comment]
You might find interesting commits about that there https://github.com/bostondv/wordpress-hybrid-client/tree/stand-down-app

You can use JWT auth plugin in WP side.
