### ISSUE TITLE
Too much stored... How to disable Local Storage / Caching ?

### ISSUE THREAD

**Issue by bonatoc** [shprink/wordpress-hybrid-client#170]
Is there a global variable of some kind to avoid caching ?

Right now I'm hacking `get()` from `AbstractItemService` like so : 

    get(id, query) {
        let queryString = JSON.stringify(query);
        let deferred = this.$q.defer();
        let hash =  md5(this.getCacheUniqueString(id, queryString));
        // let itemCache = this.getCache().get(`item-${hash}`);
		
        // if (itemCache) {
        //     deferred.resolve(itemCache);
        // } else {
            this.getHttpPromise(id, query).then((response) => {
                    this.getCache().put(`item-${hash}`, response);
                    deferred.resolve(response);
                })
                .catch((error) => {
                    deferred.reject(error);
                });
        // }
        return deferred.promise;
    }

... but I'm still getting cached data
Is there a way to deactivate caching globally ?

Imagine a news app, you have to be able to query Wordpress on every request, or at least have a very brief cache lifecycle.

**Comment by shprink** [comment]
Cache behavior can be overwritten  in your personal config/config.cson.

Check the default file (search for cache) to know what to overwrite: https://github.com/shprink/wordpress-hybrid-client/blob/develop/config/config.default.cson

If you set all `maxAge` to 0 you won't cache anything

**Comment by bonatoc** [comment]
@shprink — Sorry, a classic case of RTFM... 
Of course it's documented : http://wphc.julienrenaux.fr/getting-started.html

**Comment by shprink** [comment]
No worries :)
