### ISSUE TITLE
Push Notification 

### ISSUE THREAD

**Issue by uswakamili** [shprink/wordpress-hybrid-client#171]
My push notification is not working.. Kindly assist

**Comment by dennisleussink** [comment]
For me its not working on iOS, what OS do you have issues with?

**Comment by uswakamili** [comment]
How did u configure it?

**Comment by uswakamili** [comment]
Android

**Comment by dennisleussink** [comment]
Just read the documentation: https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md

Cant go wrong!

**Comment by uswakamili** [comment]
Where should i put my sender i.d?

**Comment by dennisleussink** [comment]
In /config/config.default.cson

"pushNotifications":
        "enabled": false
        "baseUrl": "http://yourDomain.com/pnfw"
        "android":
            "senderID": ""

**Comment by shprink** [comment]
Thanks @dennisleussink !

I have added the senderID in config.cson so it is more obvious that that's the file you need to modify https://github.com/shprink/wordpress-hybrid-client/commit/6a97d2f12af7aafc1008b6b828ec9ee0e7ccb5d9

**Comment by shprink** [comment]
Every configuration you want to make on the default config must be made in `config/config.cson`. `config/config.default.cson` must remain untouched to avoid conflicts when upgrading

**Comment by uswakamili** [comment]
am getting 

ERROR in ./config/config.cson
Module build failed: [stdin]:20:19: error: missing "
            "alert": true
                  ^

**Comment by shprink** [comment]
you must have a format issue, past your file here

**Comment by uswakamili** [comment]
"title": "VarcityApp"

"api":
    "baseUrl": "http://varcity.co.ke/wp-json"
    "timeout": 10000
    "maxAttempt": 3

"translation":
    "displayed" : ["en", "fr", "zh", "es", "pl", "de", "pt", "it"]
    "prefered": "en"

" "pushNotifications":
        "enabled": false
        "baseUrl": "http://domain/pnfw/register"
        "android":
            "senderID": "733673552878"

**Comment by shprink** [comment]
cson file needs a correct indentation, it is not correct here..

also `" "pushNotifications":` don't you see the problem here?

**Comment by uswakamili** [comment]
I have corrected that but still am not getting push notifications when i post

**Comment by shprink** [comment]
share your baseUrl for both WP-API and Push notif please

**Comment by uswakamili** [comment]
http://varcity.co.ke/wp-json
http://varcity.co.ke/pnfw/register

**Comment by shprink** [comment]
the baseUrl for push notif is wrong: https://github.com/shprink/wordpress-hybrid-client/blob/develop/dist/config.cson#L15

remove `/register`

**Comment by uswakamili** [comment]
still not working I dont Know whats wrong.

**Comment by shprink** [comment]
`enabled` should be `true` you got that right?

**Comment by uswakamili** [comment]
yes and on wp no tokens were found

**Comment by shprink** [comment]
debug using the console, you should see logs releated to push notif

**Comment by uswakamili** [comment]
THis is the only error am getting /home/ndugus/appvar/wordpress-hybrid-client/hooks/after_prepare/030_modify_plist.sh: line 11: /usr/libexec/PlistBuddy: No such file or directory
/home/ndugus/appvar/wordpress-hybrid-client/hooks/after_prepare/030_modify_plist.sh: line 11: /usr/libexec/PlistBuddy: No such file or directory

**Comment by shprink** [comment]
The console, not the terminal

**Comment by uswakamili** [comment]
GET 
http://localhost:8080/cordova.js [HTTP/1.1 404 Not Found 11ms]
WARNING: Tried to load angular more than once. bundle-434bed.js:96328:4
main controller bundle-434bed.js:25887:19
nativepagetransitions is disabled or nativepagetransitions plugin is not present bundle-434bed.js:25887:19
ImgCache initialising bundle-434bed.js:25887:19
INFO: ImgCache initialising bundle-434bed.js:139473:26
WARN: Your browser does not support the html5 File API bundle-434bed.js:139473:26
ImgCache init: error! Check the log for errors bundle-434bed.js:25887:19

reinit load false bundle-434bed.js:25887:19
wphcLoader attempt: 0 bundle-434bed.js:25887:19
cordova socialsharing bundle-434bed.js:25887:19
WARN: ImgCache not loaded yet! - Have you called ImgCache.init() first? bundle-434bed.js:139473:26
WARN: ImgCache not loaded yet! - Have you called ImgCache.init() first? bundle-434bed.js:139473:26
GET 
http://i0.wp.com/wp_user_avatar [HTTP/1.1 400 Bad Request 747ms]
GET 
http://i0.wp.com/wp_user_avatar [HTTP/1.1 400 Bad Request 275ms]
WARN: ImgCache not loaded yet! - Have you called ImgCache.init() first?

**Comment by uswakamili** [comment]
On google on where should i ue gcm input should be?

**Comment by uswakamili** [comment]
on wordpress am getting /pnfw/register API Error (401) from IP address 197.237.75.81: Unauthorized, Parameter oauth_consumer_key is missing.

**Comment by shprink** [comment]
@uswakamili read that https://wordpress.org/support/topic/not-connect-the-android-app-to-wordpress-site-using-register-api
