### ISSUE TITLE
error installing org.pushandplay.cordova.apprate@1.1.7

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#173]
today we have this error:
---------------
$ ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist@1.0.0
cordova plugin add cordova-plugin-inappbrowser@1.0.1
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-file@2.1.0
cordova plugin add cordova-plugin-file-transfer@1.2.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-network-information@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add org.pushandplay.cordova.apprate@1.1.7

/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add org.pushandplay.cordova.apprate@1.1.7":
Fetching plugin "org.pushandplay.cordova.apprate@1.1.7" via npm
Error: Failed to fetch plugin org.pushandplay.cordova.apprate@1.1.7 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/org.pushandplay.cordova.apprate
----------------------------

The problem is that the script stop to work. 
seem that the apprate plugin is not present in the npm repository.

**Comment by maxlinux2000** [comment]
I have deleted the apprate plugin from the list, but again another problem

cordova plugin add nl.x-services.plugins.socialsharing@4.3.19

/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add nl.x-services.plugins.socialsharing@4.3.19":
Fetching plugin "nl.x-services.plugins.socialsharing@4.3.19" via npm
Error: Failed to fetch plugin nl.x-services.plugins.socialsharing@4.3.19 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/nl.x-services.plugins.socialsharing

**Comment by maxlinux2000** [comment]
:(

cordova plugin add com.ionic.keyboard@1.0.4

/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add com.ionic.keyboard@1.0.4":
Fetching plugin "com.ionic.keyboard@1.0.4" via npm
Error: Failed to fetch plugin com.ionic.keyboard@1.0.4 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.ionic.keyboard

**Comment by maxlinux2000** [comment]
for the moment we can clone from github:

cordova plugins add https://github.com/pushandplay/cordova-plugin-apprate.git

cordova plugin add cordova-plugin-x-socialsharing

cordova plugin add ionic-plugin-keyboard

All the names of plugins are changing (again)

**Comment by maxlinux2000** [comment]
Another one:

:compileX86ReleaseSources UP-TO-DATE
:lintVitalX86Release/home/max/XDK/cantando.04/wordpress-hybrid-client/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:555: Error: Expected resource of type id [ResourceType]
                actionButtonContainer.setId(1);
                                            ~
/home/max/XDK/cantando.04/wordpress-hybrid-client/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:563: Error: Expected resource of type id [ResourceType]
                back.setId(2);
                           ~
/home/max/XDK/cantando.04/wordpress-hybrid-client/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:587: Error: Expected resource of type id [ResourceType]
                forward.setId(3);
                              ~
/home/max/XDK/cantando.04/wordpress-hybrid-client/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:610: Error: Expected resource of type id [ResourceType]
                edittext.setId(4);
                               ~
/home/max/XDK/cantando.04/wordpress-hybrid-client/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:633: Error: Expected resource of type id [ResourceType]
                close.setId(5);
                            ~
/home/max/XDK/cantando.04/wordpress-hybrid-client/platforms/android/src/org/apache/cordova/inappbrowser/InAppBrowser.java:679: Error: Expected resource of type id [ResourceType]
                inAppWebView.setId(6);
                                   ~

   Explanation for issues of type "ResourceType":
   Ensures that resource id's passed to APIs are of the right type; for
   example, calling Resources.getColor(R.string.name) is wrong.

6 errors, 0 warnings

occurs both in arm7 and x86

the problem ai that  cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"  is too old.

for the moment I have installed the last version

**Comment by shprink** [comment]
What node and npm version do you run?

**Comment by maxlinux2000** [comment]
$ node -v
v4.3.0

$ npm -v
2.14.12

**Comment by shprink** [comment]
update npm to use 3.x and do not use `ionic state restore`, please follow the doc `npm run restore`

**Comment by maxlinux2000** [comment]
OK, all works fine now.

TNX :)

**Comment by ryan-0** [comment]
Hi, 
I'm having the same initial error. 
<img width="645" alt="screen shot 2016-06-04 at 5 05 12 pm" src="https://cloud.githubusercontent.com/assets/11512435/15802110/90794244-2a76-11e6-83c6-5f9832ce61c7.png">
I'm running npm 3.9.5 and I used `npm run restore ` 
Any idea how to fix this?
Thank you!

**Comment by shprink** [comment]
This is fixed with 2.0.0-beta09. Please use that version

**Comment by tohaitrieu** [comment]
I have some error:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'wordpress-hybrid-client' ]
2 info using npm@4.4.4
3 info using node@v7.8.0
4 silly fetchPackageMetaData wordpress-hybrid-client
5 silly fetchNamedPackageData wordpress-hybrid-client
6 silly mapToRegistry name wordpress-hybrid-client
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'wordpress-hybrid-client',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'wordpress-hybrid-client',
9 silly mapToRegistry   name: 'wordpress-hybrid-client',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/wordpress-hybrid-client
11 verbose request uri https://registry.npmjs.org/wordpress-hybrid-client
12 verbose request no auth needed
13 info attempt registry request try #1 at 2:24:58 PM
14 verbose request id e34913230ee83cca
15 http request GET https://registry.npmjs.org/wordpress-hybrid-client
16 http 404 https://registry.npmjs.org/wordpress-hybrid-client
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Wed, 12 Apr 2017 07:25:00 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-hkg6822-HKG',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1491981899.380199,VS0,VE930',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Wed, 12 Apr 2017 07:25:00 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-hkg6822-HKG',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1491981899.380199,VS0,VE930',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/wordpress-hybrid-client
19 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
19 silly fetchPackageMetaData  error for wordpress-hybrid-client { Error: Registry returned 404 for GET on https://registry.npmjs.org/wordpress-hybrid-client
19 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
19 silly fetchPackageMetaData   pkgid: 'wordpress-hybrid-client',
19 silly fetchPackageMetaData   statusCode: 404,
19 silly fetchPackageMetaData   code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/wordpress-hybrid-client
20 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
20 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
20 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:194:7)
20 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
20 verbose stack     at emitOne (events.js:96:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
21 verbose statusCode 404
22 verbose pkgid wordpress-hybrid-client
23 verbose cwd /Users/tohaitrieu/isach
24 verbose Darwin 16.5.0
25 verbose argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "bugs" "wordpress-hybrid-client"
26 verbose node v7.8.0
27 verbose npm  v4.4.4
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/wordpress-hybrid-client
30 error 404
31 error 404 'wordpress-hybrid-client' is not in the npm registry.
32 error 404 You should bug the author to publish it (or use the name yourself!)
33 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]
`
