### ISSUE TITLE
External links open in app

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#175]
i wants to open my page external links in the app, what should i do ?

**Comment by dennisleussink** [comment]
config/menu.json

That's where the menu can get modified.

They are four types of menu item (internal|external|folder|separator).

internal Can be any page of the application (home|category|tag|parameters)
external Any www website
folder Create a menu sublevel (you can add up to six levels)
separator Separate menu items
NB: The icons must be from ionicons.com

So just use type: external

Source: https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md

**Comment by shprink** [comment]
Thanks @dennisleussink but I think what @Prabhat36 meant is to be able to open external links inside the app using in app browser.

The answer is that is not possible but could be.

the code is here https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/directives/href/href.coffee#L11-L14

**Comment by Prabhat36** [comment]
thanks....
 $cordovaInAppBrowser.open $attrs.href, '_system'
changed to=
 $cordovaInAppBrowser.open $attrs.href, '_self'
so now good news is links are getting loaded into app browser but the app theme is not there..  
![screenshot from 2016-02-21 18-57-55](https://cloud.githubusercontent.com/assets/14105960/13202801/96a2bb1e-d8cd-11e5-8580-d80d93f18c92.png)

**Comment by shprink** [comment]
Try on device

**Comment by shprink** [comment]
You can now decide targets and options of inApp plugin

```
"menu":
    "externalLinkTarget" : null # _self|_blank|_system default: _system https://github.com/apache/cordova-plugin-inappbrowser#cordovainappbrowseropen
    "externalLinkOptions": null # default: 'location=yes'
```

**Comment by justintylermoore** [comment]
Once you browse to the external link via the menu, how does one go back to the menu? On my build, the app UI is gone once you go to an external link. The only way to get back, for me, is to quit app and remove from multitasking to launch fresh.

**Comment by shprink** [comment]
@justintylermoore on iOS?

**Comment by justintylermoore** [comment]
Correct.

**Comment by shprink** [comment]
can you play with different options

```
"menu":
    "externalLinkTarget" : null # _self|_blank|_system default: _system https://github.com/apache/cordova-plugin-inappbrowser#cordovainappbrowseropen
    "externalLinkOptions": null # default: 'location=yes'
```

Let me know what works for you.

thanks

**Comment by justintylermoore** [comment]
Okay. I have tried every possible combination of parameters and it still is launching the link in safari. The plug in is getting loaded with no errors on build and I don't see any console errors on device either. 
There doesn't seem to be any effect on changing these settings. I've even modified the source code in several files to see if maybe they weren't properly loading from config file but nothing. 
I've tried:
 "externalLinkTarget" : '_self'
 "externalLinkOptions": 'location=yes'
 "externalLinkTarget" : '_self'
 "externalLinkOptions": 'location=no'
 "externalLinkTarget" : '_blank'
 "externalLinkOptions": 'location=yes'
 "externalLinkTarget" : '_blank'
 "externalLinkOptions": 'location=no'
 "externalLinkTarget" : '_system'
 "externalLinkOptions": 'location=yes'
 "externalLinkTarget" : '_system'
 "externalLinkOptions": 'location=no'

iPhone 6S Plus - iPad Pro - iOS Simulator - iOS 9.3 - Npm 3.8.5 - node 4.4.2 - Xcode 7.3 - cordova 6.1.1 - ionic 1.7.4 (I updated to 2.0.0b23 last night to test)

**Comment by shprink** [comment]
Which version of WPHC do you use? Also cordova-plugin-inappbrowser was upgraded, please restore your plugins.

**Comment by timhuh** [comment]
seems not work at all :(

**Comment by Prabhat36** [comment]
the links are getting loaded in app but the app UI disappears.. when we press back button in android it take back to app.. is it possible to load link in app with UI present @shprink  @timhuh,

**Comment by shprink** [comment]
You can only play with the options listed in the docs. What do you mean by UI present @Prabhat36 ?
You want the browser as a modal or something?

**Comment by Prabhat36** [comment]
i want to load links in app with taskbar, drawer , instead of loading it like in app browser,
