### ISSUE TITLE
image + short description in the list of posts/pages

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#176]
Hi, plase have a look to this app in playstore:

https://play.google.com/store/apps/details?id=com.martos&hl=fr

below the list of news 

<img src="https://lh3.googleusercontent.com/D6RWg7gaF_AIAtWWWQynUVOSTiRbiMzUZbdHPlxk5zR__3c8uT2-ijxHbiwlZChj4g=h900">

I think that would be very nice have the same preview in wphc. Do you think that is possible?

**Comment by shprink** [comment]
Everything is possible. You have access the sass files and custom templates.

Please read the doc
