### ISSUE TITLE
ion-side menu opend on start

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#177]
Hi,
I need to add to app.js this code:

```
$scope.toggleLeft = function() {
$ionicSideMenuDelegate.toggleLeft();
}
```
from:  https://forum.ionicframework.com/t/open-side-menu-at-app-launch/4667/5

in order to open automactly the side menu when the app start.

where I can this code in WPHC?

regads,
MaX

**Comment by shprink** [comment]
In your own config folder `config/` modify index.js to add a run function:

```
mod.run(($ionicSideMenuDelegate) => $ionicSideMenuDelegate.toggleLeft());
```

that's it
