### ISSUE TITLE
Start app with sidemenu opened

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#178]
Hi 
I need to open the side menu as default when the app start.

I tried to edit the ION-MENU.HTML with:

`<ion-side-menu ng-if="::appLoaded"  side="left" expose-aside-when="(min-width:300px)" view="menu">`

instead:

`<ion-side-menu ng-if="::appLoaded" side="left" expose-aside-when="{{main.exposeAsideWhen}}" ui-view="menu">`

but now the menu does't close anymore  :(

Any idea how to solve it?

**Comment by shprink** [comment]
`exposeAsideWhen` is in the configuration, no need to modify anything:

https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md#menu-object

Just do that => https://github.com/shprink/wordpress-hybrid-client/issues/177
