### ISSUE TITLE
Add Chinese language support

### ISSUE THREAD

**Issue by mingxia** [shprink/wordpress-hybrid-client#18]
HI：

I will add Chinese language support。Yesterday found the top title can be normal Chinese, but the left menu garbled.

like this:

![xianshi](https://cloud.githubusercontent.com/assets/12199412/8269671/91742d92-17e6-11e5-90ef-4d519b6a831e.png)

**Comment by mingxia** [comment]
I look at the language pack files are saved in UTF8 format indeed, but WPHC is UTF8, I could not find the problem

**Comment by shprink** [comment]
Can you please checkout that it is ok now on the pushNotif branch?

**Comment by mingxia** [comment]
thanks，I do it.

**Comment by mingxia** [comment]
@shprink it's ok!!!!!
