### ISSUE TITLE
Featured Image not rendering V2.0.0-beta02

### ISSUE THREAD

**Issue by tjlim86** [shprink/wordpress-hybrid-client#180]
Hi,

I'm very new to AngularJs so pardon me if I sounded like an idiot. I'm currently using the v2.0.0-beta06 and whenever I `npm run devserver` and viewed it on chrome the featured image is not showing.

![screenshot](https://cloud.githubusercontent.com/assets/17420879/13371073/445330ca-dd58-11e5-97d0-959365fa97dd.png)
 
`npm run devserver` returned the following: [http://pastebin.com/DQwudtud](http://pastebin.com/DQwudtud)

The test website can be seen here: [http://testinganapp.ml/](http://testinganapp.ml/) Wordpress Version 4.4.2

Installed plugins:
- WP-API Version 2.0-beta12
- Better REST API Featured Images Version 1.2.0 (already tried disabling it.)

Here's my config.xml and config folder
[config.tar.gz](https://github.com/shprink/wordpress-hybrid-client/files/149213/config.tar.gz)

Any help would be appreciated. Thanks!

**Comment by shprink** [comment]
Have you tried in device? I have not tested WPAPI BETA12 so it could be
related. Beta11 is fine

**Comment by tjlim86** [comment]
Installed the WP-API Version 2.0-beta11 and still no featured image when I 'npm run devserver'.

I'm gonna try to compile and run it on a device and see if the problem still exists.

By the way, thanks for the help.

**Comment by tjlim86** [comment]
Installed the APK into an android device and still no luck.

Tried replacing the baseUrl with your website and it turned out OK so most probably the problem lies on my wordpress installation which is Version 4.4.2 by the way and only have the WP REST API Version 2.0-beta11 plugin installed.

Can I know what version of Wordpress are you using? or did you set any settings on your Wordpress?

**Comment by tjlim86** [comment]
Also made a comparison of the JSONs of both our websites and the only differences are their domains and the two chunk of codes for "/wp/v2/movie" and  "/wp/v2/actor" that I believe you're using for postType (?)

Anyhow, I'm really stuck.

**Comment by tjlim86** [comment]
Hi @shprink 

It appears that the problem lies in both the GD module for php5 and the PHP extension Imagick which I forgot to install on my VPS. Installing both of them appears to have fixed my problem.

[Image Processing (ImageMagick)](http://php.net/manual/en/book.imagick.php)
[Image Processing and GD](http://php.net/manual/en/book.image.php)

Thanks again @shprink

**Comment by hazrpg** [comment]
Hi @tjlim86 I'm having the same problem - initially I thought adding `php5-gd` and `php5-imagick` to my VPS would do the trick, but sadly it didn't. Is there anything else you did?

**Comment by AsadAlihp** [comment]
after giving local storage permission on real device feature images start loading in my case.
