### ISSUE TITLE
Open external App with com.lampa.startapp plugin

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#183]
Hi,
I need to open an external app from the side menu... for example Telegram or Whatsapp.

In others apps I'm using this plugin:

cordova plugin add https://github.com/lampaa/com.lampa.startapp.git

Any way to do the same with WPHC ?

regards
MaX

**Comment by shprink** [comment]
That's not a built in feature but with enough knowledge it should be easy to use it within WPHC.
