### ISSUE TITLE
Google Admob 

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#186]
How can we use google admob in this app?

or the flash ads like google?

**Comment by shprink** [comment]
I do not know, never tried. Let us know if you make it work.

**Comment by Prabhat36** [comment]
ok sure.. thanks for quick reply..

**Comment by alcholever** [comment]
@Prabhat36  I found this ads plugin. I tested my phone. It is working properly. 
https://github.com/appfeel/admob-google-cordova

**Comment by shprink** [comment]
@alcholever would you mind creating a little tutorial on how to use it for the community?

**Comment by Prabhat36** [comment]
@alcholever  thanks brother.. if possible please share your code or as @shprink said create tutorial.. thanks again

**Comment by alcholever** [comment]
Sorry guys. On sunday I got to the university entrance examinations. So impossible

**Comment by AsadAlihp** [comment]
@alcholever come on bro, please share your code

**Comment by AsadAlihp** [comment]
hey guys I am busy in making tutorial in admob........... :)

**Comment by shprink** [comment]
@AsadAlihp created a doc that will not be included in the official docs => https://github.com/shprink/wordpress-hybrid-client/pull/199/files

Will create an admobs module and allow users to use admobs through config file instead.

Thanks @AsadAlihp very much
