### ISSUE TITLE
Featured image Not getting loaded 

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#187]
in the new version of app featured image are not displying in app..
help plz

**Comment by shprink** [comment]
which WP-API version please? latest tested is beta12

**Comment by Prabhat36** [comment]
using beta 12, still  featured image are not getting load,,

**Comment by shprink** [comment]
this version should be fine. What's the network error?

**Comment by Prabhat36** [comment]
![p](https://cloud.githubusercontent.com/assets/14105960/13873551/418c53ba-ed18-11e5-856d-951226e69da4.png)
i have set images to featured image on my wordpress site.  using beta beta 12 ,, still?

**Comment by shprink** [comment]
give me the wp-api address, will try it here

**Comment by Prabhat36** [comment]
http://resulthub.itechjunkie.com/wp-json

**Comment by shprink** [comment]
![image](https://cloud.githubusercontent.com/assets/1388706/13901199/138efb16-ee1c-11e5-9e83-6fe50226df92.png)

Fine here, is it the same thing on device?

**Comment by shprink** [comment]
Check `lib/index.html` if you run an old version. 

it should have:

```
<meta http-equiv="Content-Security-Policy" content="default-src * 'self' data:; img-src * 'self' 'unsafe-inline' 'unsafe-eval' data: blob: filesystem:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
```

for pictures to get displayed

**Comment by AsadAlihp** [comment]
@Prabhat36 bhai Ik baat poochni hai yar apnay icons k colors (blue) kaisay change kiyae?? main bht try kr rha houn par nhi ho rha yar koi idea do na plz

**Comment by shprink** [comment]
?

**Comment by AsadAlihp** [comment]
In image he got blue icons. how did he do that? while we only can use icon from ionic

**Comment by Prabhat36** [comment]
in config folder open config.scss file and use below code 
$palette-secondary-text:#3b5998 !default;

**Comment by Prabhat36** [comment]
@AsadAlihp  
in config folder open config.scss file and use below code 
$palette-secondary-text:#3b5998 !default;

**Comment by Prabhat36** [comment]
@shprink  thanks,, i have made change as u said in index.html now when i open any post it showing featured image but when at posts it still not showing ..

**Comment by shprink** [comment]
Cannot reproduce

**Comment by hazrpg** [comment]
I'm also having this problem, is there anything I can do to help you be able to reproduce this?

- I'm using `v2.0.0-beta08` of WPHC.
- I used `$ chromium-browser --disable-web-security` to make sure that external images can be pulled.
- `$ npm --version` gives `3.8.5`.
- `$ node --version` gives `v0.10.25`.
- OS: `Ubuntu 14.04`.
- `lib/index.html` has the line you mentioned above.
- I followed the guide here: [https://github.com/shprink/wordpress-hybrid-client/blob/v2.0.0-beta08/INSTALLATION.md](https://github.com/shprink/wordpress-hybrid-client/blob/v2.0.0-beta08/INSTALLATION.md)
- Browser network error: `http://localhost:8080/cordova.js` returns `404 Not Found` (although this is expected in the browser and not a build of cordova).
- Browser network error: `https://secure.gravatar.com/avatar/58f112388eef616f919ca4ee8a030c9f?s=96&d=retro&r=g` returns `(cancelled)`. Now although this returns as cancelled, there's a later one of the same image but in a different location that works fine at `filesystem:http://localhost:8080/temporary/imgcache/187d8faa4479c50bbfceb64d56e7d8e9d5a45fc0`. This appears to be the only image that seems to show fine.
- JSON feed found here: `https://www.hazrpg.co.uk/wp-json`
- Screenshot attached:
![image](https://cloud.githubusercontent.com/assets/115112/14268626/08acfc00-fad5-11e5-9d9a-3d29ff8f1bc5.png)

**Comment by shprink** [comment]
Try upgrading to the lastest version of WPHC first. It is just a git fetch and a checkout.

**Comment by hazrpg** [comment]
@shprink I assume you mean the develop branch instead of the release tags? I will give that a go and report back.

**Comment by shprink** [comment]
no no I meant if you do not run the latest then upgrade.

How is this behaving on device? Is it the same (with my web service it works and with yours it does not)?

**Comment by hazrpg** [comment]
Oh, in that case... I already had the latest. Seems the same problem happens in the develop branch too. However, I have not tried compiling to a native app so I will try that next. The behaviour locally using `npm run devserver` however is that it works with your web service, but not mine. When inspecting the elements it seems the img src attribute is blank (on mine) - which is bizarre, considering the json feed definitely has a url to the image.
