### ISSUE TITLE
Beta 06 on iOS doesn't generate Tokens for Push Notifications

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#188]
Hi,

i wanted to update from beta 1 to beta 6 but no tokens are generated for new iOS users anymore. #

EDIT: The token seems to be generated after I quit the app and open it again.

**Comment by yannicfries** [comment]
And on iOS it always shows the badge for a new message.

**Comment by shprink** [comment]
For badges the code is here:

https://github.com/shprink/wordpress-hybrid-client/blob/1371533e476d4a657fe583f0ceba49092903548b/lib/params/pushNotifications/service.js#L97

I will have a look this week

**Comment by delitestudio** [comment]
Please keep in mind that the badge count sent by our plugin is the number of posts "unread".
We inject a flag into the WP REST API that states if a post has been read, it may be useful to use it to mark the unread posts in some way into the application (for example with a badge, a different color, etc...).

**Comment by yannicfries** [comment]
Still not generating Tokens on iOS

**Comment by shprink** [comment]
@yannicfries we know that this feature works. Please check the known issues: https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#known-issues
