### ISSUE TITLE
Adding bbpress support

### ISSUE THREAD

**Issue by pavanpatharde** [shprink/wordpress-hybrid-client#190]
Hi Julien,

I am planning to use this package to develop an application which will mainly support forum,topic and reply custom post types.

I am a beginner with cordova and angular js. Can you please recommend me on what procedure should i follow to achieve the same ?

Thanks,
Pavan

**Comment by shprink** [comment]
If you are a beginner keep in mind that this project does not use the Ionic way.

It uses Webpack, ES6 modules and is therefore a little less easy to understand for beginner.

This article could help you http://julienrenaux.fr/2015/08/17/modular-angularjs-and-ionic-architecture-a-first-step-towards-angularjs-2/

Good luck,
Julien
