### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by medrockstar** [shprink/wordpress-hybrid-client#194]
Hi,

Can you give us an authentification example with wordpress-hybrid-client.

Merci infiniment.

**Comment by AsadAlihp** [comment]
@shprink is already working on that or will work

**Comment by shprink** [comment]
Someone is working on adding this feature to WPHC.

We will use https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/ and https://github.com/shprink/wp-api-angularjs that now supports all HTTP methods.

Will update here. Subscribe

**Comment by medrockstar** [comment]
Any news ?

**Comment by AsadAlihp** [comment]
@medrockstar Not yet

**Comment by shprink** [comment]
@bostondv how is this going in your app? Do you have a timeline on Open Sourcing this part?

thanks

**Comment by bostondv** [comment]
Hey! Our app is done but I haven't had the time yet to convert the auth and
possibly some other smaller parts into a state they can be contributed.
Hopefully will be able to work on it in the next week or two.

**Comment by shprink** [comment]
I can help if you need.

**Comment by bostondv** [comment]
That'd be great, thanks. I'll post a link once I get my branch up on github.

**Comment by shprink** [comment]
Closing in favor of #141
