### ISSUE TITLE
Failed to find 'ANDROID_HOME'

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#195]
facing the same error again.. i have properly set  environment variable.. 
in another drive of my system i hv wphc v 1.7 and it builds properly no error. 
![androiderr](https://cloud.githubusercontent.com/assets/14105960/13981277/285d83b0-f109-11e5-8027-b321f021dcfb.png)

**Comment by shprink** [comment]
IDK man, try running the cordova command instead see if it changes anything

**Comment by Prabhat36** [comment]
sudo cordova command works fine, but when i run "sudo npm run build" it gives above image error.

**Comment by shprink** [comment]
Use cordova command then.

**Comment by Prabhat36** [comment]
![cordova](https://cloud.githubusercontent.com/assets/14105960/14110483/42fe3ffe-f5e4-11e5-96ad-ed8dde448d4d.png)

still not working.. everything is ok in system but why getting error

**Comment by shprink** [comment]
you told me:

> sudo cordova command works fine

it appears that it does not work either!

**Comment by Prabhat36** [comment]
![pr](https://cloud.githubusercontent.com/assets/14105960/14110792/a198486a-f5e5-11e5-8180-00151cc6915b.png)

its working, but at the time of build it gives error

**Comment by shprink** [comment]
I cannot help you but encouraging you to google your error.

if `echo $ANDROID_HOME` display the path to your sdk then something else is wrong on your machine.

**Comment by Prabhat36** [comment]
thanks aneway.

**Comment by Prabhat36** [comment]
in    /home/wordpress-hybrid-client/platforms/android/cordova/lib
       there is a file "check_reqs.js" 
i did set-
maybeSetAndroidHome(path.join(process.env['HOME'], 'android-sdk-linux'));

instead of below-
maybeSetAndroidHome(path.join(process.env['HOME'], 'android-sdk-macosx'));

the problem solved ..
