### ISSUE TITLE
Change title homepage

### ISSUE THREAD

**Issue by CreacionesJA** [shprink/wordpress-hybrid-client#196]
How can I change the title of the homepage? I want to be called 'Noticias' instead of 'Posts'. I could make the change in the menu perfectly but the title can not find the option to change 'Posts' to 'Noticias'.

Sorry for my bad English, I'm Spanish.

**Comment by alcholever** [comment]
Hi @CreacionesJA. You can change es.cson under "lib/translations/es.cson"
