### ISSUE TITLE
How to add page completely offline

### ISSUE THREAD

**Issue by CreacionesJA** [shprink/wordpress-hybrid-client#197]
How to add a page completely offline? I want to add a page called 'About Us' and do not want to add that page in WordPress because the Blog belongs to a client that I am developing the application of his WordPress Blog. On this page I want to show information about me as a developer. In addition it adds that this application is developed with Wordpress Hybrid Client and finally a link to GitHub of your project.

I'm pretty novice in Node.js, Angular.js, Ionic, etc. and do not really understand how the application works.

Sorry for my bad English, I'm Spanish.

**Comment by shprink** [comment]
Why not creating this page on your client WP? The page will not be public in WP (as there is no way to list all pages) except for people knowing the url. That's the simplest way.

v1 had the feature you are talking about but it has been removed since we can use pages in v2.
