### ISSUE TITLE
 25% 9/35 build modulesBus error (core dumped)

### ISSUE THREAD

**Issue by hillerliao** [shprink/wordpress-hybrid-client#198]
`/wordpress-hybrid-client/node_modules/cson/node_modules/extract-opts/node_modules/typechecker/source/index.js:17
export function getObjectType (value /* :mixed */) /* :string */ {
^^^^^^
  0% compilehttp://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /home/hillerliao/KuaiPan/nodejs-prj/wordpress-hybrid-client
 25% 9/35 build modulesBus error (core dumped)

npm ERR! wordpress-hybrid-client@2.0.0-beta07 devserver: `webpack-dev-server --port 8080 --json --progress`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta07 devserver script.
npm ERR! This is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8080 --json --progress
npm ERR! You can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-56-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "devserver"
npm ERR! cwd /my/path/wordpress-hybrid-client
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
`

**Comment by shprink** [comment]
Your node and npm versions are old. Please update and re install.

**Comment by hillerliao** [comment]
hillerliao@hillerliao-ThinkPad-E420:~/KuaiPan/nodejs-prj/wordpress-hybrid-client$ npm run devserver

> wordpress-hybrid-client@2.0.0-beta07 devserver /home/hillerliao/KuaiPan/nodejs-prj/wordpress-hybrid-client
> webpack-dev-server --port 8080 --json --progress

  0% compilehttp://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /home/hillerliao/KuaiPan/nodejs-prj/wordpress-hybrid-client
 25% 9/35 build modulesBus error (core dumped)

npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "devserver"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta07 devserver: `webpack-dev-server --port 8080 --json --progress`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta07 devserver script 'webpack-dev-server --port 8080 --json --progress'.
npm ERR! This is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8080 --json --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hillerliao/KuaiPan/nodejs-prj/wordpress-hybrid-client/npm-debug.log

**Comment by hillerliao** [comment]
On my Mac @shprink 

`wordpress-hybrid-client git:(744ad27) ✗ npm run devserver

> wordpress-hybrid-client@2.0.0-beta05 devserver /Users/hillerliao/kuaipan/node-prj/wordpress-hybrid-client
> webpack-dev-server --port 8080 --json --progress

  0% compileevents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
  at Object.exports._errnoException (util.js:870:11)
  at exports._exceptionWithHostPort (util.js:893:20)
  at Server._listen2 (net.js:1231:14)
  at listen (net.js:1267:10)
  at net.js:1376:9
  at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)


npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "devserver"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta05 devserver: `webpack-dev-server --port 8080 --json --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta05 devserver script 'webpack-dev-server --port 8080 --json --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8080 --json --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hillerliao/kuaipan/node-prj/wordpress-hybrid-client/npm-debug.log`

**Comment by hillerliao** [comment]
something changed.

`ERROR in dlopen(/Users/hillerliao/kuaipan/node-prj/wordpress-hybrid-client/node_modules/node-sass/vendor/darwin-x64-46/binding.node, 1): no suitable image found.  Did find:
	/Users/hillerliao/kuaipan/node-prj/wordpress-hybrid-client/node_modules/node-sass/vendor/darwin-x64-46/binding.node: truncated mach-o error: segment __LINKEDIT extends to 2493268 which is past end of file 1820763
 @ ./lib/scss/bootstrap.scss 4:14-176

ERROR in dlopen(/Users/hillerliao/kuaipan/node-prj/wordpress-hybrid-client/node_modules/node-sass/vendor/darwin-x64-46/binding.node, 1): no suitable image found.  Did find:
	/Users/hillerliao/kuaipan/node-prj/wordpress-hybrid-client/node_modules/node-sass/vendor/darwin-x64-46/binding.node: truncated mach-o error: segment __LINKEDIT extends to 2493268 which is past end of file 1820763
 @ ./lib/font/font.scss 4:14-171
webpack: bundle is now VALID.`

**Comment by hillerliao** [comment]
finally fixed. the GFW made me failding to install node-sass
