### ISSUE TITLE
"ERROR in Object.keys called on non-object" while running  "npm run-script dumpdev"

### ISSUE THREAD

**Issue by gau1991** [shprink/wordpress-hybrid-client#20]
Hello,
I was trying to build Android App, in `config.json` file only changed parameter was `baseUrl`

I got following error:
```
╭─gaurav at Gaurav in ~/github/wordpress-hybrid-client-1.1.0 using 15-06-21 - 22:33:00 
╰─○ npm run-script dumpdev

> wordpress-hybrid-client@1.1.0 dumpdev /home/gaurav/github/wordpress-hybrid-client-1.1.0
> gulp build

[22:33:08] Using gulpfile ~/github/wordpress-hybrid-client-1.1.0/gulpfile.js
[22:33:08] Starting 'cleanWww'...
[22:33:08] Starting 'webpack:dev'...
[22:33:08] Finished 'cleanWww' after 36 ms
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

[22:34:59] Version: webpack 1.9.11
                  Asset       Size  Chunks             Chunk Names
       fonts/Roboto.ttf    19.9 kB          [emitted]  
     fonts/Roboto.woff2    10.3 kB          [emitted]  
      fonts/Roboto.woff    13.3 kB          [emitted]  
     fonts/ionicons.eot     121 kB          [emitted]  
     fonts/ionicons.ttf     189 kB          [emitted]  
    fonts/ionicons.woff    67.9 kB          [emitted]  
     fonts/ionicons.svg     334 kB          [emitted]  
img/post-img-border.png  497 bytes          [emitted]  
       bundle-da14b3.js    3.12 MB       0  [emitted]  main
             index.html   43 bytes          [emitted]  

ERROR in Object.keys called on non-object
[22:34:59] Finished 'webpack:dev' after 1.85 min
[22:34:59] Starting 'build'...
[22:34:59] Finished 'build' after 6.11 μs
```

I was using WordPress-hybrid-client 1.1.0

**Comment by shprink** [comment]
Hi,

It is a problem with Webpack version.

Checkout the develop branch, remove node_modules folder and ```npm install``` again.

It should install Webpack 1.7.3 and the build should be fine.

Let me know if it works.

**Comment by gau1991** [comment]
Thanks, now with develop branch, no error, but its showing only plain white page, 
![selection_028](https://cloud.githubusercontent.com/assets/1296181/8272811/edcbd0ca-186f-11e5-867d-08d38a2734b3.png)

Same is happening with android App also, first splash screen, after that white page

**Comment by shprink** [comment]
Open the console and past the errors please.

**Comment by gau1991** [comment]
Following is the error at console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/[object%20Object] Failed to load resource: the server responded with a status of 404 (Not Found)
bundle-ca5aa2.js:54464 Uncaught Error: [$injector:modulerr] Failed to instantiate module wordpress-hybrid-client due to:
Error: [$injector:modulerr] Failed to instantiate module wp-api-angularjs due to:
Error: [$injector:modulerr] Failed to instantiate module wp-api-angularjs.provider due to:
Error: [$injector:modulerr] Failed to instantiate module restangular due to:
ReferenceError: _ is not defined
    at Object.a.init (http://localhost:8080/bundle-ca5aa2.js:13810:713)
    at new <anonymous> (http://localhost:8080/bundle-ca5aa2.js:13810:10275)
    at invoke (http://localhost:8080/bundle-ca5aa2.js:54529:18)
    at Object.instantiate (http://localhost:8080/bundle-ca5aa2.js:54537:28)
    at provider (http://localhost:8080/bundle-ca5aa2.js:54372:37)
    at Object.provider (http://localhost:8080/bundle-ca5aa2.js:54364:17)
    at runInvokeQueue (http://localhost:8080/bundle-ca5aa2.js:54435:36)
    at http://localhost:8080/bundle-ca5aa2.js:54443:12
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=restangular&p1=Refe…oadModules%20(http%3A%2F%2Flocalhost%3A8080%2Fbundle-ca5aa2.js%3A54425%3A6)
    at http://localhost:8080/bundle-ca5aa2.js:50154:13
    at http://localhost:8080/bundle-ca5aa2.js:54464:16
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
    at http://localhost:8080/bundle-ca5aa2.js:54442:41
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
    at http://localhost:8080/bundle-ca5aa2.js:54442:41
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=wp-api-angularjs.pr…oadModules%20(http%3A%2F%2Flocalhost%3A8080%2Fbundle-ca5aa2.js%3A54425%3A6)
    at http://localhost:8080/bundle-ca5aa2.js:50154:13
    at http://localhost:8080/bundle-ca5aa2.js:54464:16
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
    at http://localhost:8080/bundle-ca5aa2.js:54442:41
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
    at http://localhost:8080/bundle-ca5aa2.js:54442:41
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=wp-api-angularjs&p1…oadModules%20(http%3A%2F%2Flocalhost%3A8080%2Fbundle-ca5aa2.js%3A54425%3A6)
    at http://localhost:8080/bundle-ca5aa2.js:50154:13
    at http://localhost:8080/bundle-ca5aa2.js:54464:16
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
    at http://localhost:8080/bundle-ca5aa2.js:54442:41
    at forEach (http://localhost:8080/bundle-ca5aa2.js:50422:21)
    at loadModules (http://localhost:8080/bundle-ca5aa2.js:54425:6)
    at createInjector (http://localhost:8080/bundle-ca5aa2.js:54351:12)
    at doBootstrap (http://localhost:8080/bundle-ca5aa2.js:51707:21)
    at bootstrap (http://localhost:8080/bundle-ca5aa2.js:51728:13)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=wordpress-hybrid-cl…bootstrap%20(http%3A%2F%2Flocalhost%3A8080%2Fbundle-ca5aa2.js%3A51728%3A13)
```

**Comment by shprink** [comment]
The 404 error is no big deal.

Your problem is that the project cannot find undescorejs/lodash that is supposed to be bundled within the lib "wp-api-angularjs". I actually updated this lib last week so it is related. Make sure that you have "wp-api-angularjs" 1.0.0-beta1 installed instead of 1.0.0. 

```npm install wp-api-angularjs@1.0.0-beta1```

Sorry about that I am gonna make a fix for it.

**Comment by gau1991** [comment]
HI, npm is not able to find `wp-api-angularjs@1.0.0-beta1`

```
╭─gaurav at Gaurav in ~/github/wordpress-hybrid-client on develop✘✘✘ using 15-06-22 - 0:18:05 
╰─○ npm install wp-api-angularjs@1.0.0-beta1
npm WARN package.json path@0.4.10 path is also the name of a node core module.
npm WARN package.json util@0.10.3 util is also the name of a node core module.
npm ERR! Error: version not found: wp-api-angularjs@1.0.0-beta1
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-41-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "wp-api-angularjs@1.0.0-beta1"
npm ERR! cwd /home/gaurav/github/wordpress-hybrid-client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gaurav/github/wordpress-hybrid-client/npm-debug.log
npm ERR! not ok code 0
```

**Comment by shprink** [comment]
Try with the prefix v. E.g "v1.0.0-beta1"

**Comment by gau1991** [comment]
Still no luck
```
╭─gaurav at Gaurav in ~/github/wordpress-hybrid-client on develop✘✘✘ using 15-06-22 - 0:30:40 
╰─○ npm install wp-api-angularjs@v1.0.0-beta1
npm WARN package.json path@0.4.10 path is also the name of a node core module.
npm WARN package.json util@0.10.3 util is also the name of a node core module.
npm ERR! Error: version not found: wp-api-angularjs@1.0.0-beta1
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-41-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "wp-api-angularjs@v1.0.0-beta1"
npm ERR! cwd /home/gaurav/github/wordpress-hybrid-client
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gaurav/github/wordpress-hybrid-client/npm-debug.log
npm ERR! not ok code 0
```

**Comment by shprink** [comment]
Lol OK then open pushNotif branch and re install. It should be fine ;)

**Comment by shprink** [comment]
I'll fix and release 1.0.1 in a couple of hours

**Comment by shprink** [comment]
Sorry 1.1.1

**Comment by gau1991** [comment]
Thanks, Tried pushNotif branch, working fine :)
One bug though, my website post tiles and content are in Marathi language, though its handling posts title on home page correctly, on posts page its showing something weird.

![selection_030](https://cloud.githubusercontent.com/assets/1296181/8273100/503e3fb6-187c-11e5-8fde-321912663e3c.png)

it might be related with #18

**Comment by shprink** [comment]
Fixed https://github.com/shprink/wordpress-hybrid-client/tree/v1.2.0

Thanks mate :)

**Comment by jararuben** [comment]
build error?
info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'installCordova' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'preinstallCordova', 'installCordova', 'postinstallCordova' ]
6 info preinstallCordova wordpress-hybrid-client@1.5.2
7 info installCordova wordpress-hybrid-client@1.5.2
8 verbose unsafe-perm in lifecycle true
9 info wordpress-hybrid-client@1.5.2 Failed to exec installCordova script
10 verbose stack Error: wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid wordpress-hybrid-client@1.5.2
12 verbose cwd /home/ruben/Apps-Android/betas/futbolpy
13 error Linux 3.19.0-15-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "installCordova"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
18 error Exit status 1
19 error Failed at the wordpress-hybrid-client@1.5.2 installCordova script 'bash ./install_cordova.sh'.
19 error This is most likely a problem with the wordpress-hybrid-client package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     bash ./install_cordova.sh
19 error You can get their info via:
19 error     npm owner ls wordpress-hybrid-client
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'installCordova' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'preinstallCordova', 'installCordova', 'postinstallCordova' ]
6 info preinstallCordova wordpress-hybrid-client@1.5.2
7 info installCordova wordpress-hybrid-client@1.5.2
8 verbose unsafe-perm in lifecycle true
9 info wordpress-hybrid-client@1.5.2 Failed to exec installCordova script
10 verbose stack Error: wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid wordpress-hybrid-client@1.5.2
12 verbose cwd /home/ruben/Apps-Android/betas/futbolpy
13 error Linux 3.19.0-15-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "installCordova"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
18 error Exit status 1
19 error Failed at the wordpress-hybrid-client@1.5.2 installCordova script 'bash ./install_cordova.sh'.
19 error This is most likely a problem with the wordpress-hybrid-client package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     bash ./install_cordova.sh
19 error You can get their info via:
19 error     npm owner ls wordpress-hybrid-client
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'installCordova' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'preinstallCordova', 'installCordova', 'postinstallCordova' ]
6 info preinstallCordova wordpress-hybrid-client@1.5.2
7 info installCordova wordpress-hybrid-client@1.5.2
8 verbose unsafe-perm in lifecycle true
9 info wordpress-hybrid-client@1.5.2 Failed to exec installCordova script
10 verbose stack Error: wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid wordpress-hybrid-client@1.5.2
12 verbose cwd /home/ruben/Apps-Android/betas/futbolpy
13 error Linux 3.19.0-15-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "installCordova"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
18 error Exit status 1
19 error Failed at the wordpress-hybrid-client@1.5.2 installCordova script 'bash ./install_cordova.sh'.
19 error This is most likely a problem with the wordpress-hybrid-client package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     bash ./install_cordova.sh
19 error You can get their info via:
19 error     npm owner ls wordpress-hybrid-client
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'installCordova' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'preinstallCordova', 'installCordova', 'postinstallCordova' ]
6 info preinstallCordova wordpress-hybrid-client@1.5.2
7 info installCordova wordpress-hybrid-client@1.5.2
8 verbose unsafe-perm in lifecycle true
9 info wordpress-hybrid-client@1.5.2 Failed to exec installCordova script
10 verbose stack Error: wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid wordpress-hybrid-client@1.5.2
12 verbose cwd /home/ruben/Apps-Android/betas/futbolpy
13 error Linux 3.19.0-15-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "installCordova"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error wordpress-hybrid-client@1.5.2 installCordova: `bash ./install_cordova.sh`
18 error Exit status 1
19 error Failed at the wordpress-hybrid-client@1.5.2 installCordova script 'bash ./install_cordova.sh'.
19 error This is most likely a problem with the wordpress-hybrid-client package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     bash ./install_cordova.sh
19 error You can get their info via:
19 error     npm owner ls wordpress-hybrid-client
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by mingxia** [comment]
Preriquisites
    NodeJS (tested on v0.10.33)
    NPM (tested on 2.1.9)

**Comment by jararuben** [comment]
Ubuntu 14.04 LTS
NodeJs v0.10.33 and/or V.0.10.37
Npm v2.1.9
npm run ionic run android ERROR
comand line error

Upgrade warning - for the CLI to run correctly,      
 it is highly suggested to upgrade the following:     

 Please update your Node runtime to version  >=0.12.x

******************************************************
Running command: /home/ruben/Escritorio/Apps-Android/betas/wordpress-hybrid-client/platforms/android/cordova/run 
ERROR: Error: ANDROID_HOME is not set and "android" command not in your PATH. You must fulfill at least one of these conditions.
ERROR running one or more of the platforms: Error: /home/ruben/Escritorio/Apps-Android/betas/wordpress-hybrid-client/platforms/android/cordova/run: Command failed with exit code 2
You may not have the required environment or OS to run this project

to run only android in the terminal, it works. android sdk path without problems.

**Comment by shprink** [comment]
ANDROID_HOME must be set. https://www.airpair.com/javascript/posts/a-year-using-ionic-to-build-hybrid-applications#android
