### ISSUE TITLE
Strip Shortcodes from WP content?

### ISSUE THREAD

**Issue by justintylermoore** [shprink/wordpress-hybrid-client#200]
First, AMAZING job. I am excited to start using your solution for several projects I have coming up. Kudos on a great job. 

How would one go about stripping the shortcodes that a theme uses? Our site uses the Divi theme and there are several shortcodes that get passed into the App. It would be nice to either get rid of them, or have them rendered in the App. 

I thought about just adding the non-shortcoded content in the excerpt field and only pulling the excerpts, but that would be one more step for non-tech people to worry about when creating posts on our site. 

For example, this is what is displayed on our newsletter pages in the App:

> [et_pb_section admin_label="section" background_image="https://www.xxxxxxx.xom/xxxxx.jpg" transparent_background="off" allow_player_pause="off" inner_shadow="off" parallax="off" parallax_method="off" padding_mobile="off" make_fullwidth="off" use_custom_width="off" width_unit="on" make_equal="off" use_custom_gutter="off"][et_pb_row admin_label="row" make_fullwidth="on" use_custom_width="off" width_unit="on" use_custom_gutter="off" padding_mobile="off" allow_player_pause="off" parallax="off" parallax_method="off" make_equal="off" column_padding_mobile="on" parallax_1="off" parallax_method_1="off" parallax_2="off" parallax_method_2="off"][et_pb_column type="1_4"][et_pb_team_member admin_label="Davids Bio" name="David" position="President" image_url="https://www.xxxxxxx.xom/xxxxx.jpg" animation="off" background_layout="dark" use_border_color="off" border_color="#ffffff" border_style="solid"]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla gravida commodo mi, ut auctor lacus. Maecenas dui nibh, pretium quis porta sed, luctus quis ante. Nullam erat ex, malesuada ac mi ut, accumsan tristique metus. Nunc ac tincidunt odio. Donec sit amet justo in lorem rhoncus gravida. Cras lacinia arcu ultrices interdum sodales. In hac habitasse platea dictumst.
[/et_pb_team_member][et_pb_sidebar admin_label="Subscribe" orientation="left" area="et_pb_widget_area_10" background_layout="dark" remove_border="off"] [/et_pb_sidebar]

If it is possible to render the shortcodes in the App, what file would be best to add the code and styling to?

**Comment by shprink** [comment]
Thanks for the kind words.

You could create a angular filter to remove them before display. You could overwrite the existing templates and add this filter. Check out the configuration.md docs to do that.

Your new filter can live in `config/index.js`

If you want to render specific shortcodes it will be much more work but doable as well using filters.

**Comment by justintylermoore** [comment]
Excellent. Thank you for the reply!
