### ISSUE TITLE
allow different custom posts to be configured

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#204]
Today we can configure the custom posts queries but it will be applied to ALL custom posts not just one.

```
"customPosts":
    "query":
        "per_page": 5
        "filter[orderby]": "date"
        "filter[order]": "desc"
```

**Comment by henmaker** [comment]
What about post that query from taxonomies, i notice this is only work if it is custom posts, but if the listing is from taxonomies it doesn't work.

**Comment by shprink** [comment]
try with `taxonomiesPosts` instead of `customPosts`

**Comment by henmaker** [comment]
Thank you~ taxonomiesPosts work!

**Comment by jasonkruit** [comment]
Is there any way to pass a custom query based on the $stateParams.slug?

**Comment by shprink** [comment]
Now custom posts or taxo will get the conf of the `type` it displays.

For instance if your custom post is `movie` or the custom taxo post type is `movie`, both will read this config:

```
"movie":
    "query":
        "per_page": 2
```
