### ISSUE TITLE
Push notifcations stop working after beta5

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#205]
As tittle,  all release after beta5 can not register itself to the WP delite plugin, so the app, can not receive the notifications.

regards
MaX

**Comment by shprink** [comment]
It is working for me and others as far as I know.

What does the HTTP request that register your device say?

**Comment by maxlinux2000** [comment]
Hi shprink, sorry for the delay

today I have build a beta8 with a new fresh wp site for porpouse testing.

the app, can't registe itself the token in the wp site, and inspecting the app installed in my phone using chrome, in the console i can see this bug:

`Failed to update emulated device list. Error: Emulated device is missing required property 'page-rect'`

.... perhaps a wrong device plugin version?

tomorrow I will downgrade to beta5 in order to check if the configuration of the wp site and config.cson is correct.

ciao
MaX

**Comment by shprink** [comment]
I do not think the WPHC version will change anything. `page-rect` is not a WPHC dependency.

Why does it say `Emulated device`? Are you on real device or emulator? Push notifications do not work on Emulators BTW.

**Comment by maxlinux2000** [comment]
...in a real device (a motog2 with oficial android 6.0)

**Comment by maxlinux2000** [comment]
OK, my fault. The push notifications works fines in beta8.
I was a copy/paste error in the api of push notification plugin.
closing

**Comment by ronyrun** [comment]
Hey did you find any solutions for the 

`Failed to update emulated device list. Error: Emulated device is missing required property 'page-rect'` error ?

**Comment by shprink** [comment]
@maxlinux2000 he is asking you ;)

**Comment by maxlinux2000** [comment]
Hi,

the error:
Failed to update emulated device list. Error: Emulated device is missing required property 'page-rect'

...still occurs in beta9, but the app per se, works fine.

I've tried with android 4.2 and 6.0 and both works as expected for the users, but in the inspector console appear this error.

my system is a ubuntu 14.04 with
$ cordova -v
6.1.1
$ npm -v
2.15.1

![x1](https://cloud.githubusercontent.com/assets/5683921/15581849/6c47538e-236e-11e6-99a5-da46fc683d2c.png)
![x2](https://cloud.githubusercontent.com/assets/5683921/15581848/6c43908c-236e-11e6-8463-1c899674fc6f.png)
![x3](https://cloud.githubusercontent.com/assets/5683921/15581850/6c4a1240-236e-11e6-918b-3b4ca6a92f3b.png)


I don't know if this error was important or not, but, shprink, I noted that in order to build using "cordova build", instead "npm build", I need to upgrade android and a plugin 

```
cordova platform  remove android
cordova platform  add android
cordova plugin remove nl.x-services.plugins.socialsharing
cordova plugin add cordova-plugin-x-socialsharing
cordova prepare
```

I thinks that we need to upgrade all plugins starting from crosswalk-webview.

**Comment by ronyrun** [comment]
Thank you very much for this Post !

**Comment by shprink** [comment]
I have uninstall/install several times and cannot reproduce. I am releasing a new version with cordova-android 5.x and API-23. Please check with it and let me know
