### ISSUE TITLE
White screen of death after release mode android

### ISSUE THREAD

**Issue by keegho** [shprink/wordpress-hybrid-client#207]
iOS is perfect. But in android after building the app and trying it on android cell phones with the debug mode armv7 it is working perfectly. But the released on after splash screen get a white screen then nothing happens. I tried to search a lot about this issue. But found nothing useful. Because the app is working already on the phone but the release armv7 isnt working. Even after uploading it on the play store and being published the app hangs with a white screen after splash screen. Any tips or hints.
Thanks

**Comment by shprink** [comment]
Have you uploaded both arm and x86 apks?

**Comment by keegho** [comment]
I tried to run on the simulator the x86 release apk it did the same white screen after splash. But the x86 debug is working fine on simulator. Exactly the same with armv7. Armv7 debug works great on phone but the release version gets the splash screen then white screen.

**Comment by shprink** [comment]
You can test the JS in prod mode by running `npm run dumpprod` then by running it on device. If you have a white screen then you will have some hints on the console for sure.

**Comment by keegho** [comment]
Thanks yes i had an error and i resolved it. Thanks julien. I can see you are in toulouse. I will be there in aout. Maybe we can meet if we had the chance. (Y) have a great day.

**Comment by shprink** [comment]
Yes let me know when you are here :)
