### ISSUE TITLE
Support for old android versions

### ISSUE THREAD

**Issue by gau1991** [shprink/wordpress-hybrid-client#21]
Hi,
In AndroidManifest.xml, I am able to see that `minSdkVersion="17"`,i.e. minimum supported android version is 4.2.2. 
IONIC supports 4.0+. Ref: http://ionicframework.com/docs/guide/installation.html
Is minimum 4.2.2 support intentional? Is it possible to support lesser versions as IONIC supports for same?

**Comment by shprink** [comment]
I tested on < 4.2.2 and it did not work at the time. Did not want to dig deeper. It is up to you to change it in your config.xml.
