### ISSUE TITLE
Display taxonomy name instead of the term itself from nav-bar-title

### ISSUE THREAD

**Issue by henmaker** [shprink/wordpress-hybrid-client#212]
i try to figure out how to display taxonomy name instead of term itself from nav-bar-title, by tweaking this file:
/lib/taxonomies/controller.js
line 18:      this.setTitle($stateParams.term);

To display the term name/title, but no luck. Can you look into this?
Example: If without changing this, it will display as "attraction-type", instead, it should display as "Attraction Type" if i want that taxonomy title to be display.

**Comment by shprink** [comment]
#59 should have resolved this. Which version of WPHC do you use?

**Comment by henmaker** [comment]
I'm using the latest version which just installed yesterday, the one you referring underposts.controller.js, i already checked that, it is the same version, i'm referring the one at the top, referring to screen capture. I notice this is from /lib/taxonomies/controller.js

![screen shot 2016-04-21 at 6 04 11 am](https://cloud.githubusercontent.com/assets/18576404/14692040/376d7e16-0787-11e6-9508-e201c16f2226.jpg)

**Comment by shprink** [comment]
the problem is that you do not know the title. We only know the slug which is the unique identifier for a taxo. 
We know the title as soon as the server respond but not before.

**Comment by henmaker** [comment]
I see, in that's the case, is there a way we can pass our own define name from menu.json like this:
        "route": "public.taxonomies({ term: 'attractions_type', name: 'Attraction Type', postType: 'attraction'})",

At least, that allow us to have option to define the name by our own via Menu.json

Thank you for looking into this.

**Comment by shprink** [comment]
Sorry to answer that late but this is doable via translation files

If you add this on the languages you use:

```
"attractions_type": "Attraction Type"
```

then the page title will be `Attraction Type`
