### ISSUE TITLE
Different taxonomies are not refreshing when switch from Menu

### ISSUE THREAD

**Issue by henmaker** [shprink/wordpress-hybrid-client#213]
If you have two different taxonomies, and using two different Menu, when tap and switch from one to another, the 2nd one not refresh and still showing the previous taxonomy terms, have to manually pull to refresh, which doesn't make sense, can you please look into this? Thank you

**Comment by shprink** [comment]
which version of WPHC?

**Comment by henmaker** [comment]
2.0.0-beta08
