### ISSUE TITLE
npm run devserver Doesn't work

### ISSUE THREAD

**Issue by davidgaldon** [shprink/wordpress-hybrid-client#215]
Hi Julien, first of all thanks a lot for sharing your knowledge with us. Your tutorial is great.
I'm having some troubles to get it running. When I try: npm run devserver, I get the following error:

> wordpress-hybrid-client@2.0.0-beta08 devserver /Users/davidgaldonhernandez/Documents/AppsMaster/MyApps/WP1/wordpress-hybrid-client
> webpack-dev-server --port 8080 --json --progress

  0% compileevents.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
  at Object.exports._errnoException (util.js:856:11)
  at exports._exceptionWithHostPort (util.js:879:20)
  at Server._listen2 (net.js:1227:14)
  at listen (net.js:1263:10)
  at net.js:1372:9
  at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "devserver"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta08 devserver: `webpack-dev-server --port 8080 --json --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta08 devserver script 'webpack-dev-server --port 8080 --json --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8080 --json --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/davidgaldon/Documents/AppsMaster/MyApps/WP1/wordpress-hybrid-client/npm-debug.log

And if even after the error I go to http://localhost:8080/webpack-dev-server/  I get the following error:

Cannot find module 'node-sass'
 @ ./lib/scss/bootstrap.scss 4:14-435

Not sure if the error is clear for your.
Any idea? I've tried with a fresh "npm install", also with "killall node", and it seems there is nothing running in the same port. I've also tried with "sudo", but nothing works and I'm stuck.
Thanks a lot in advance! I will really appreciate any help.

**Comment by shprink** [comment]
Your port 8080 is already in use

**Comment by davidgaldon** [comment]
You were absolutely right. I don't know why I though this port was free. Another version of the same app was in 8080. Thank you so much!
Just in case someone has the same error:
You can find what is in the 8080 with:
lsof -i :8080 | grep LISTEN

Then you get a pid, and you can see what this pid is with:
ps -ef (your_pid)

If the pid is not an important process, you can kill it with:
kill (your_pid)

Then try again "npm run devserver" and hopefully it will works.
