### ISSUE TITLE
Proble with npm run restore

### ISSUE THREAD

**Issue by toorbye** [shprink/wordpress-hybrid-client#217]
Hello, when I try "run npm restore" , I've errors:
`npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "restore"
npm ERR! node v4.4.4
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta08 restore: `ionic state restore`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta08 restore script 'ionic state restore'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
`
I try with debian jessi and Macox El capitan.

npm -v -> 3.8.9
node -v -> 4.4.4
WPHC -> 2.0.0-BETA08

I also try this commands:
rm -rf node_modules && npm install
cordova plugin add cordova-plugin-whitelist@1.0.0

but the problem persists
Thanks a lot

**Comment by shprink** [comment]
why do you add the whitelist plugin?

Any errors during `npm install`? Try installing ionic globally and run `ionic
state restore` yourself.

Julien Renaux
Software Engineer
Blog <http://julienrenaux.fr/> - Twitter <https://twitter.com/julienrenaux>
- Hire me on Toptal
<http://www.toptal.com/resume/julien-renaux#select-just-supreme-hackers>

**Comment by toorbye** [comment]
hi. 
I add the whistlist plugin becouse this post https://github.com/shprink/wordpress-hybrid-client/issues/185

I install ionic globally-> npm install -g ionic

I run "ionice state restore" but...

`cordova plugin add cordova-plugin-whitelist@1.0.0
cordova plugin add cordova-plugin-inappbrowser@1.3.0
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-file@2.1.0
cordova plugin add cordova-plugin-file-transfer@1.2.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-network-information@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add org.pushandplay.cordova.apprate@1.1.7

/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add org.pushandplay.cordova.apprate@1.1.7":
Fetching plugin "org.pushandplay.cordova.apprate@1.1.7" via npm
Error: Failed to fetch plugin org.pushandplay.cordova.apprate@1.1.7 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/org.pushandplay.cordova.apprate
`

**Comment by toorbye** [comment]
Solved!
I change the old plugins in package.json

"cordova-plugin-whitelist@1.0.0",
"cordova-plugin-inappbrowser@1.3.0",
"cordova-plugin-splashscreen@2.1.0",
"cordova-plugin-file@2.1.0",
"cordova-plugin-file-transfer@1.2.1",
"cordova-plugin-device@1.0.1",
 "cordova-plugin-globalization@1.0.1",
 "cordova-plugin-console@1.0.1",
 "cordova-plugin-network-information@1.0.1",
 "cordova-plugin-dialogs@1.1.1",
 **"org.pushandplay.cordova.apprate@1.1.7",**
 "cordova-plugin-x-toast@2.1.1",
**"nl.x-services.plugins.socialsharing@4.3.19",**
 **"com.ionic.keyboard@1.0.4",**
 "cordova-plugin-statusbar@1.0.1",
 "cordova-plugin-google-analytics@0.8.1",
    {
      "locator": "https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5",
      "id": "com.telerik.plugins.nativepagetransitions"
    },
    "phonegap-plugin-push@1.5.3",
    "cordova-plugin-crosswalk-webview@1.4.0",
    "cordova-plugin-spinner-dialog@1.3.1",
    "cordova-plugin-admobpro@2.14.0"

**Comment by shprink** [comment]
the fix #222 will be released in next version (within few hours)
