### ISSUE TITLE
Cannot play iframe videos

### ISSUE THREAD

**Issue by oparidae** [shprink/wordpress-hybrid-client#218]
on the dev server, if the wordpress has any dailymotion iframe it plays correctly
on android or ios, nothing is played, even if I whitelist all origins and domains

Is there some option to allow/disallow that ?

Best Regards

**Comment by shprink** [comment]
I guess it depends on how you embed your video.

You can download my app and check the Angular2 Router post. The Youtube video works fine. I use iframely or the native embed syntax https://codex.wordpress.org/Embeds
