### ISSUE TITLE
Open the Pages as default

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#219]
Hi,
I need to open as default the Pages instead the Posts when WPHC start. 
Below you can see that I'm putting the Pages to first position and Post in second... but the app, still open the Post as default.
There is a way to change this behaviour?

```
[{
    "type": "internal",
    "trans": "menu.home",
    "route": "public.pages",
    "icon": "icon ion-images"
},

{
    "type": "internal",
    "trans": "menu.posts",
    "route": "public.posts",
    "icon": "icon ion-ios-paper"
},
....

```

**Comment by alcholever** [comment]
"menu":
    "defaultState":
        "state": "public.pages"
        "params": {}

**Comment by alcholever** [comment]
Paste this code into config file

**Comment by maxlinux2000** [comment]
TNX, It's works fine!!
```

# MENU
"menu":
    "defaultState":
        "state": "public.pages"
        "params": {}
```
