### ISSUE TITLE
Load the post of a category in home.

### ISSUE THREAD

**Issue by toorbye** [shprink/wordpress-hybrid-client#220]
I need load the post of a category in home. This is possible? I can not find the way?
I have two categories, news and events.
Thanks

**Comment by shprink** [comment]
Totally doable:

Docs => https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md#how-to-change-the-home-page

**Comment by toorbye** [comment]
Correct, 

# MENU (Default)
"menu":
    "defaultState":
        "state": "public.posts"
        "params": {"slug": "events"}

but not filtered by slug, shows all post

This is the response wp-json:

slug":"events","type":"post","link":"http:\/\/dev.test.locall\/eventos\/eventos\/","title":

**Comment by shprink** [comment]
If you check the default menu you can get the state.

for instance the uncategorized posts page is https://github.com/shprink/wordpress-hybrid-client/blob/develop/dist/menu.json#L64

```
public.taxonomies.slug({ term: 'category', slug: 'uncategorized', postType: 'post' })
```

if you translate that in state and params it is:

```
"state": "public.taxonomies.slug"
"params": {{ "term": "category", "slug": "uncategorized", "postType": "post" }}
```

in your case:

```
"state": "public.taxonomies.slug"
"params": {{ "term": "category", "slug": "events", "postType": "post" }}
```

**Comment by toorbye** [comment]
thanks, but in config.cson, doesn't work:
```
#MENU
"menu":
    "defaultState":
        "state": "public.taxonomies.slug"
        "params": { "term": "category", "slug": "events", "postType": "post" }
```

but in menu.json work
`"route": "public.taxonomies.slug({ term: 'category', slug: 'events', postType: 'post' })",`

I was interested in that load at Home....any ideas?

Thanks a lot

**Comment by toorbye** [comment]
Great! my fault!! Now is right! thank you very much!

**Comment by Genemes** [comment]
I tried uploading posts from a certain category, but to no avail.
When using:
"state": "public.taxonomies.slug"
"params": {{"term": "category", "slug": "mycategory", "postType": "post"}}

The following error appears:
$stateNotFound

What could be happening?

**Comment by Genemes** [comment]
It worked! I did the search by passing the id as parameter
