### ISSUE TITLE
Error: connect ETIMEDOUT 50.17.177.14:80 on "npm run restore"

### ISSUE THREAD

**Issue by devadattas** [shprink/wordpress-hybrid-client#221]
When I run "npm run restore", I get the following error:

    > wordpress-hybrid-client@2.0.0-beta08 restore wordpress-hybrid-client
    > ionic state restore

    Attempting to restore your Ionic application from package.json

    Restoring Platforms

    cordova platform add android
    cordova platform add ios

    Restore platforms is complete

    Restoring Plugins

    cordova plugin add cordova-plugin-whitelist@1.0.0
    cordova plugin add cordova-plugin-inappbrowser@1.3.0
    cordova plugin add cordova-plugin-splashscreen@2.1.0
    cordova plugin add cordova-plugin-file@2.1.0
    cordova plugin add cordova-plugin-file-transfer@1.2.1
    cordova plugin add cordova-plugin-device@1.0.1
    cordova plugin add cordova-plugin-globalization@1.0.1
    cordova plugin add cordova-plugin-console@1.0.1
    cordova plugin add cordova-plugin-network-information@1.0.1
    cordova plugin add cordova-plugin-dialogs@1.1.1
    cordova plugin add org.pushandplay.cordova.apprate@1.1.7

    wordpress-hybrid-client/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
            throw 'Error executing "' + pluginCommand + '":\n' + output;
            ^
    Error executing "cordova plugin add org.pushandplay.cordova.apprate@1.1.7":
    Fetching plugin "org.pushandplay.cordova.apprate@1.1.7" via npm
    Fetching plugin "org.pushandplay.cordova.apprate@1.1.7" via cordova plugins registry
    Error: Failed to fetch plugin org.pushandplay.cordova.apprate@1.1.7 via registry.
    Probably this is either a connection problem, or plugin spec is incorrect.
    Check your connection and plugin name/version/URL.
    Error: connect ETIMEDOUT 50.17.177.14:80

**Comment by shprink** [comment]
Closing in favor of #217

**Comment by pinkasey** [comment]
Thanks for the fix!
I really appreciate it.
And also learn from it.
