### ISSUE TITLE
iOS: ports 2195 and 2196

### ISSUE THREAD

**Issue by kolorobos** [shprink/wordpress-hybrid-client#226]
Hi,
I've faced the problem recently - can't get any pushes, all of them failing with `Unable to connect to 'ssl://gateway.push.apple.com:2195': (0)` for prod and `Unable to connect to 'ssl://gateway.sandbox.push.apple.com:2195'` for sandbox. In your manual I can clearly see 

> Push Notifications for WordPress can't receive inbound and outbound TCP packets over ports 2195 and 2196.

And I'm stuck on it. What should I do to move from 2195/2196?

**Comment by shprink** [comment]
Sounds like a problem with your key. recreate the .pub keys and you should be fine.

**Comment by kolorobos** [comment]
I'm really sorry as the question may be dumb, but I don't think I get you - as an iOS developer I've created .pem certificates just as described in your guide. What does .pub keys stands for? Who/how should recreate it?

**Comment by dennisleussink** [comment]
@kolorobos just follow this guide: http://www.delitestudio.com/wordpress/push-notifications-for-wordpress/configuring-ios-push-notifications/

And make sure that you have both ports opened by your hosting provider, or if you can do it yourself.

**Comment by kolorobos** [comment]
Thanks guys, I really appreciate your help 🙏

**Comment by dennisleussink** [comment]
You are welcome, I also struggled a long time with push notifications and after a lot work I got it working and managed to have 900 push notifications during an event.
