### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by jdunhin** [shprink/wordpress-hybrid-client#227]
Hi

Images not showing after app published on store. When it was tested on device it worked but after store upload images does not show. Nothing changed on my website and when I run app again on devserver it also works.

any ideas why images does not show?

**Comment by shprink** [comment]
That's weird, have you tried on several devices?

**Comment by jdunhin** [comment]
Yes. I tested again by deleting app from phone (andriod) the upload the apk instead of download it from store. Then it work 100%. Lol weird.... Tested on ipad also working.  

I keep testing. I starting to think it is wp issue not giving permision to the images or somthing

**Comment by shprink** [comment]
IDK. closing

**Comment by jdunhin** [comment]
Found the problem images have this "class="aligncenter size-full wp-image-13968" when i remove it all works good!!

Now app is perfect thank you for great app!!!
