### ISSUE TITLE
Unauthorized, Parameter oauth_consumer_key is missing

### ISSUE THREAD

**Issue by gitHubLie** [shprink/wordpress-hybrid-client#228]
this is debug log , need i config something?

/wordpress/pnfw/register API Error (401) from IP address 192.168.1.105: Unauthorized, Parameter oauth_consumer_key is missing.	
五月 21, 2016 2:20 上午
/wordpress/pnfw/categories/?os=iOS&token=06b52f43ff108029a064fd15ccaa30ddf1f89e320061823f7cb10c4bfe35b24c API Error (401) from IP address 192.168.1.105: Unauthorized, Parameter oauth_consumer_key is missing.

**Comment by shprink** [comment]
Sounds familiar ? https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#parameter-oauth_consumer_key-is-missing

**Comment by gitHubLie** [comment]
ok .fix it.
