### ISSUE TITLE
user Image can't get.

### ISSUE THREAD

**Issue by gitHubLie** [shprink/wordpress-hybrid-client#229]
this is request URL ,and this not work.
http://1.gravatar.com/avatar/a8af267f99ea0e9d1b41e12d9d17959f?s=96&d=wp_user_avatar&r=x

return info is 
Sorry, the parameters you provided were not valid.

and I try to change this request URL like that.
http://1.gravatar.com/avatar/a8af267f99ea0e9d1b41e12d9d17959f?s=96
test from chrome is ok . it can get image.

how to fix it? I need to change WP REST API V2  ?  i user last version.
help me .brothers

**Comment by shprink** [comment]
which version?

**Comment by gitHubLie** [comment]
v2.0.0-beta08   WP REST API V2

**Comment by shprink** [comment]
v2 betaXX ?

**Comment by shprink** [comment]
Closing, feel free to reopen

**Comment by mAlaliSy** [comment]
I have the same problem.. I am using 2.0-beta15 version.
