### ISSUE TITLE
White page on Android

### ISSUE THREAD

**Issue by gau1991** [shprink/wordpress-hybrid-client#23]
Hi,
I was playing with WordPress-hybrid-client 1.2.0, 
With devserver its working fine, but on android app, its showing only white page, tested on three different devices having different android version.

**Comment by shprink** [comment]
Could you please dump console errors. It is hard to tell what's wrong without it, it could be anything.

https://github.com/shprink/wordpress-hybrid-client/blob/develop/BUILD.md#debug

**Comment by gau1991** [comment]
Sorry, I missed logs,
Here are are complete error:
```
 Uncaught TypeError: Cannot read property 'getPreferredLanguage' of undefined 
```
Showing error for following block:
```
	      getPreferredLanguage: function () {
	        var q = $q.defer();

	        navigator.globalization.getPreferredLanguage(function (result) {
	            q.resolve(result);
	          },
	          function (err) {
	            q.reject(err);
	          });
	        return q.promise;
	      },
```

**Comment by shprink** [comment]
Ok then you miss a plugin https://github.com/shprink/wordpress-hybrid-client/blob/develop/package.json#L104

Re install it

```
cordova plugin rm org.apache.cordova.globalization
cordova plugin add org.apache.cordova.globalization
```

It happens often that plugins are not correctly installed with Cordova.

**Comment by gau1991** [comment]
Thanks now app is working,  but getting this error now:

```
Request URL: http://example.com/wp-json/posts?filter%5Borderby%5D=desc&filter%5Bpost_status%5D=publish&filter%5Bposts_per_page%5D=6&page=1
Request Method:GET
Status Code:404 Not Found (from cache)
```
Note: Here http://example.com/wp-json/posts?filter%5Borderby%5D=desc&filter%5Bpost_status%5D=publish&filter%5Bposts_per_page%5D=6&page=1 is working fine in browser.
Is it cache issue?

**Comment by shprink** [comment]
Give me a link to your WP blog. http://example.com can't be it!

**Comment by gau1991** [comment]
Hi.. Following is actual URL:


http://linuxontheheads.com/wp-json/posts?filter[orderby]=desc&filter[post_status]=publish&filter[posts_per_page]=6&page=1

**Comment by shprink** [comment]
Ok so if I understand correctly the request works on the browser but not on Android? 

Are you sure your device is online? I am not sure what can cause that.

**Comment by gau1991** [comment]
> Ok so if I understand correctly the request works on the browser but not on Android? 
Yes, on browser works fine, but on android getting this error.
>Are you sure your device is online? 
Yes my device is online, my device and laptop are connected to same wifi 

I also observed server logs, request is not coming to server. I fear that it might the cache issue as on logs its showing 
```
Status Code:404 Not Found (from cache)
Request Headers
```

**Comment by shprink** [comment]
I have never had this problem. I would appriate if you investigate further and let me know what you can find. Thanks @gau1991 :)

**Comment by shprink** [comment]
It could be related to the domain white list but I specified *

https://github.com/shprink/wordpress-hybrid-client/blob/develop/config.xml.dist#L11

**Comment by gau1991** [comment]
Hi, Following steps worked for me:
```
cordova plugin add cordova-plugin-whitelist
```
and add `<allow-navigation href="http://*/*" />` into config.xml

**Comment by shprink** [comment]
I created #24 for this problem. Thanks for your help :)

**Comment by shprink** [comment]
@gau1991 

I am having problems installing this plugin on iOS:

```
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" for android
Installing "cordova-plugin-whitelist" for ios
Failed to install 'cordova-plugin-whitelist':CordovaError: Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.7.0, failed version requirement: >=4.0.0-dev
    at checkEngines (/Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:116:29)
    at /Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:289:16
    at _fulfilled (/Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/shprink/Sites/wordpress-hybrid-client/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
Plugin doesn't support this project's cordova-ios version. cordova-ios: 3.7.0, failed version requirement: >=4.0.0-dev
```

I will have to find another solution.
