### ISSUE TITLE
Problem when pull to refresh

### ISSUE THREAD

**Issue by toorbye** [shprink/wordpress-hybrid-client#230]
Hello, I have problems when pull to refresh. No refresh new post, and changes in pages.
I test in android phone and in chrome navigator. if I want to see new post or updates in pages, I have to delete cache in the phone or in navigator.

I set maxAge to 0 in config.cson.
What is the problem?
Thanks a lot!

# CACHE
"cache":
    "img":
        "localCacheFolder": "imgcache"
        "useDataURI": false
        "chromeQuota": 10485760
        "usePersistentCache": true
        "cacheClearSize": 0
        "headers": {}
        "skipURIencoding": false
    "data":
        "capacity": 100
        **"maxAge": 0**
        "deleteOnExpire": "aggressive"
        "recycleFreq": 1000
        "cacheFlushInterval": null
        "storageMode": "localStorage"

# BOOKMARK PAGE
"bookmark":
    "cache":
        "capacity": 10

# POST PAGES
"post":
    "comments":
        "enabled": true
        "depth": 2
        "per_page": 50
    "cache":
        **"maxAge": 0**
        "capacity": 10

# PAGES PAGE
"pages":
    "query":
        "per_page": 5
        "filter[orderby]": "date"
        "filter[order]": "desc"
    "cache":
        "capacity": 10
        **"maxAge": 0**

# POSTS PAGE
"posts":
    "query":
        "per_page": 5
        "filter[orderby]": "date"
        "filter[order]": "desc"
        "filter[post_status]": "publish"

    "cache":
        "capacity": 25
        **"maxAge": 0**

**Comment by alcholever** [comment]
try this value "maxAge": 10800000

**Comment by shprink** [comment]
If it is v1, close the app and re open it to see new posts. 

In v2 the pull to refresh works as expected.

**Comment by toorbye** [comment]
I understand that I can not do wrong. I'm going crazy!
I'm using v2 beta 09.
For example If I turn off the Wifi phone, and open the app does not display the "connection error-retry", the information obtained the first time I run still it appears.
I have to go to management of applications and delete the data to retrieve new information again.
I do not understand!
any suggestions?
thanks a lot!

**Comment by shprink** [comment]
1. I open my app, posts are loaded
1. I release a new post
1. I pull to refresh => I can see the new post

Can you try that and let me know.

**Comment by MariusMez** [comment]
Hi,
I think I've the same "behavior" in my app. But only for the Android version and only for devices running android 5 and 6, it works well for the IOS version and devices running Android 4. I don't know why...

**Comment by toorbye** [comment]
tomorrow, I'll check if it works properly in ios, I also will check wordpress. I keep you informed. Thank you

**Comment by toorbye** [comment]
definitely a problem with my wordpress. Now it works properly.

**Comment by MariusMez** [comment]
Which problem ? Can you explain how you fix it ?

**Comment by toorbye** [comment]
Problem with parameter of push notifications. Set push in false, and work fine!
