### ISSUE TITLE
maintaining header when opening link

### ISSUE THREAD

**Issue by toorbye** [shprink/wordpress-hybrid-client#232]
Is posible maintaining header when opening links inserted in a page(no in external link on menu). I try to modify href.coffee, but I can not do
thanks!

**Comment by shprink** [comment]
What do you mean by "maintaining"?

**Comment by toorbye** [comment]
I want to show the menu bar when I open a link in a page.
For example now have a page with events, when I click on a links now opens external browser.
I want you to open the event show the menu bar

**Comment by alcholever** [comment]
https://github.com/shprink/wordpress-hybrid-client/blob/develop/config/config.default.cson#L45-L48

**Comment by toorbye** [comment]
I do not mean links on the menu, I mean links in the content of a page.
Thanks.

**Comment by shprink** [comment]
Yes @alcholever is right you can Achieve that through the conf.

Check the link and use the right config https://github.com/apache/cordova-plugin-inappbrowser#cordovainappbrowseropen
