### ISSUE TITLE
is it possible to add ionic material design into this app?

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#239]
http://ionicmaterial.com/demo/ 
i just love the look and feel of material design .. if it is possible to change our app look like material design . please give me short tutorial on it..

**Comment by shprink** [comment]
I have no idea sorry, I guess it is exactly the same as if you used the lib
for any other ionic app.

**Comment by Prabhat36** [comment]
yes, we need to change the lib folder, but i dont knwo how to do that?
here is the github link = https://github.com/zachfitz/Ionic-Material

**Comment by Prabhat36** [comment]
this will gonna be a great achievement if we can add material design into app..

**Comment by Prabhat36** [comment]
@shprink

**Comment by shprink** [comment]
What happen if you follow the installation process?

**Comment by Prabhat36** [comment]
stuck at 4th step.. dont know where to put this code?

Step 4: Inject Ionic & Ionic Material into your Ionic App

    var app = angular.module('YOUR_APP_NAME', ['ionic', 'ionic-material']);

**Comment by shprink** [comment]
add it there => https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/index.coffee#L35-L65

**Comment by Prabhat36** [comment]
oh thanks , so i will just delete highlighted code and paste above code.. so it will be done, right?

**Comment by shprink** [comment]
do not delete anything lol!

just add `ionic-material`

**Comment by Prabhat36** [comment]
heheh sorry im new to this code.. thanks

**Comment by lddd** [comment]
Did anyone managed to add the material design ?
