### ISSUE TITLE
How to hide a single Page from the list?

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#242]
Hi all, 
I need to hide a single page from the list in lib/template/directive/pages.html.
I need something like below in the config/menu.json, but conversely, and that working in Pages.html 

        "type": "internal",
        "route": "public.pages.id({ id: 43 })"

It's possible?

**Comment by shprink** [comment]
You can use this hook to filter the response:

```
 onDataLoaded(response){
// filter here
    }
```

in this file https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/pages/pages.controller.js
