### ISSUE TITLE
No -tsa or -tsacert is provided and this jar is not timestamped.

### ISSUE THREAD

**Issue by xvilo** [shprink/wordpress-hybrid-client#244]
I followed all the steps for building an Android APK. But when testing it on the Emulator everything works fine. But as soon as I want to build it, and it gets to the signing part I get the following error:
```

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2043-10-27) or after any future revocation date.
jar verified.

Warning: 
This jar contains entries whose certificate chain is not validated.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2043-10-27) or after any future revocation date.

Re-run with the -verbose and -certs options for more details.
./release.sh: line 26: /path/to/Android/sdk/build-tools/21.1.2/zipalign: No such file or directory
```

I'm running it on Mac OS X 10.11.5 and followed all the steps in the documentation. What is going on here?

**Comment by shprink** [comment]
> /path/to/Android/sdk/build-tools/21.1.2/zipalign: No such file or directory

It is pretty clear that have not changed the path to zipalign.

Please read the docs => https://github.com/shprink/wordpress-hybrid-client/blob/fa73bd6c87e30ffb52b5f03bae84e2a94f95dcc0/RELEASE.md#android
