### ISSUE TITLE
Facing problems on build section 

### ISSUE THREAD

**Issue by bhushangautam01** [shprink/wordpress-hybrid-client#245]
Hi , thank you very much for all your hard work it is much appreciated. i am facing some problems on building project can you please help me ?

I am new on this platform ..i follow your all the guidelines   i am facing problems on build  whenever i run this code ( brew install ant ) shows command not found   error

**Comment by shprink** [comment]
Please come to the chat https://gitter.im/shprink/wordpress-hybrid-client

brew is a OSX package manager that you need to install.
