### ISSUE TITLE
Removing open in browser button

### ISSUE THREAD

**Issue by keegho** [shprink/wordpress-hybrid-client#246]
I was trying to find a way to remove the open in browser button in the footer. But i deleted the whole footer from the posts.html but nothing happend. Can you help me in this. Thanks.

**Comment by alcholever** [comment]
Remove this lines
https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/templates/directive/post.html#L14L18

**Comment by keegho** [comment]
That is what i did nothing happend...I deleted the whole footer and it was still there.

**Comment by keegho** [comment]
Done thanks...
