### ISSUE TITLE
Testing Push Notifications

### ISSUE THREAD

**Issue by lddd** [shprink/wordpress-hybrid-client#249]
Hello,

it says "You CANNOT test push notification on emulators. Please use real devices."

So how to use a real device to test the app without submitting it?

**Comment by Accesources** [comment]
provision your app using adhoc

**Comment by shprink** [comment]
`npm run ios` will build the app and run it into the device. You need to register your device and provisioning profile but you will find docs for that on Google if the docs is not sufficient on these points.

Thanks

**Comment by lddd** [comment]
Thanks
