### ISSUE TITLE
Push Notifications: OneSignal.com

### ISSUE THREAD

**Issue by yannicfries** [shprink/wordpress-hybrid-client#251]
Hi, is it possible to use onesignal.com for push notifications? I bought the delitestudio pro version but with thousands of notifications our server goes down all the time. It would be better to sent the notifications on another server.

**Comment by shprink** [comment]
@delitestudio 

If you use another service you will need to modify the code a little bit. 

You will need to change the logic of `hasBeenRegistered` `registerWebService` `unregisterWebService`  in https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/pushNotifications/service.js

**Comment by shprink** [comment]
@delitestudio can you guys add an option to send a maximum of X push notification per minute?
