### ISSUE TITLE
Is there a way to cache media content from the bookmarked items (videos, pdfs, others)? 

### ISSUE THREAD

**Issue by amiltonpaglia** [shprink/wordpress-hybrid-client#252]
I'm working on a project that needs to storage media files such as .mp4 files and .pdfs. Is there a way to force the cache for this kind of files as well?

Thank you!

**Comment by shprink** [comment]
Doable by using the cordova file plugin http://ngcordova.com/docs/plugins/file/ but you will need to develop this part as it is not supported.
