### ISSUE TITLE
Npm Error

### ISSUE THREAD

**Issue by r4ksai** [shprink/wordpress-hybrid-client#255]
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm WARN deprecated conventional-changelog@0.0.11: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
⸨      ░░░░░░░░░░░░⸩ ⠏ fetchMetadata: WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

**Comment by shprink** [comment]
these are just warnings, no big deal.
