### ISSUE TITLE
Windows Phone / UWP Build

### ISSUE THREAD

**Issue by InigoEzcurdia** [shprink/wordpress-hybrid-client#256]
WPHC is amazing, great work!

Knowing that it's based on Ionic and cordova, could it be possible to build our apps like on Ionic so they can be used as Universal Windows Platforms apps. (WP devices, windows desktops, xbox...)

Thanks.

**Comment by shprink** [comment]
if you can do it with Ionic, you can do it with WPHC.

**Comment by ugurcandede** [comment]
If you do with WPHC share us. :D
