### ISSUE TITLE
hackishlyHidesInputAccessoryView

### ISSUE THREAD

**Issue by koboldsp** [shprink/wordpress-hybrid-client#258]
Error compiling:

/Plugins/com.ionic.keyboard/IonicKeyboard.m:75:22: Property 'hackishlyHidesInputAccessoryView' not found on object of type 'UIView *'

**Comment by knolaust** [comment]
Same. Did you find a fix?

**Comment by pavini** [comment]
I have same problem when I try to build for iOS!

**Comment by shprink** [comment]
Will try a fresh install and let you know but have you tried a different version of the keyboard plugin?

**Comment by pavini** [comment]
shprink, I already try a fresh install, but not a different version of keyboard plugin. I´ll try.. tks

**Comment by shprink** [comment]
I have built from scratch on android 7 and ios 9.2 without any problems. I use Xcode Version 7.3. Will try iOS 10 soon

**Comment by koboldsp** [comment]
Dear shprink, I get a fresh install, and before run "npm run restore", i can build ios. After run it, I get the error.

**Comment by shprink** [comment]
How can you build iOS if you have not ran `npm run restore` ? does not make sense.

**Comment by shprink** [comment]
what command do you run to have this error?

**Comment by shprink** [comment]
which Xcode version do you have?

**Comment by koboldsp** [comment]
XCode: 7.3.1 (7D1014)

I download the lasted fresh install (Version 2)
run the command: npm install && npm run installWPHC
after run the command : cordova platform add ios

Then I go to /platform/ios and open the project in Xcode. At this time, I can build it.

So, if a run the command npm run restore, I can´t build ios anymore.

P.S shprink, sorry about my english and taghkyou for your patience.

**Comment by shprink** [comment]
ok first of all do not use commands that are not in the docs. `cordova platform add ios` is not.

https://github.com/shprink/wordpress-hybrid-client/blob/develop/BUILD.md

remove platform and plugins `rm -rf platforms/ plugins` then run `npm run restore`. The difference is that it uses internal cordova which could be a different version from the one installed globally on your system.

once this is done run `npm run ios` with your device connected or `npm run iosEmulator` if your emulator is setup

**Comment by koboldsp** [comment]
I run `cordova platform add ios` because if I run only `npm run restore`, I get this message:

```
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android@5.x
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist@1.0.0
cordova plugin add cordova-plugin-inappbrowser@1.3.0
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-file@2.1.0
cordova plugin add cordova-plugin-file-transfer@1.2.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-network-information@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate#v1.1.7
cordova plugin add cordova-plugin-x-toast@2.1.1
cordova plugin add https://github.com/driftyco/ionic-plugin-keyboard#v2.2.0
cordova plugin add cordova-plugin-statusbar@1.0.1
cordova plugin add cordova-plugin-google-analytics@0.8.1
cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5
cordova plugin add phonegap-plugin-push@1.5.3
cordova plugin add cordova-plugin-crosswalk-webview@1.6.0
cordova plugin add cordova-plugin-spinner-dialog@1.3.1
cordova plugin add cordova-plugin-admobpro@2.14.0
cordova plugin add cordova-plugin-x-socialsharing@5.1.1
Restore plugins is complete

Ionic state restore completed
```

Everything looks like OK, but in my platform folder the ios platform was not created :(

This is the reason that I use the cordova add platform.

**Comment by shprink** [comment]
I am trying a new keyboard version...

**Comment by shprink** [comment]
v2.0.0-beta11 released with the keyboard plugin updated. Please let me know if you still have the error after running:

`rm -rf node_modules/ platforms/ plugins/ && npm run restore`

**Comment by koboldsp** [comment]
Perfect! tks! Now its working
