### ISSUE TITLE
Just white screen on Android

### ISSUE THREAD

**Issue by badaiardiat** [shprink/wordpress-hybrid-client#260]
![blank](https://cloud.githubusercontent.com/assets/19369415/16866644/492007c0-4a97-11e6-934e-449d584d4bcc.png)
and console chrome
![console](https://cloud.githubusercontent.com/assets/19369415/16866668/71e5e86e-4a97-11e6-837e-dd0d9f0fb702.png)
 help me for fix this problem sir

**Comment by shprink** [comment]
re install node modules and cordova's plugins:

```
npm install && npm run restore
```

let me know if it helps

**Comment by badaiardiat** [comment]
Stil not solved dude, console in chrome same

**Comment by shprink** [comment]
StatusBar is a cordova plugin https://github.com/shprink/wordpress-hybrid-client/blob/develop/package.json#L115

make sure it is correctly installed. https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/

**Comment by badaiardiat** [comment]
already correctly, but stil not working :(
npm version 3.10.5
node version v4.4.7
cordova version 6.2.0
ionic version 1.7.16

**Comment by shprink** [comment]
It cannot be correct if you do not have access to the Cordova plugin. Try
calling it from the console.

**Comment by badaiardiat** [comment]
i try reinstall npm node cordova ionic but this problem not solved -_-

**Comment by badaiardiat** [comment]
plis anyone can help me, cant resolve for this problame

**Comment by shprink** [comment]
can you access `StatusBar` via the console? if not the plugin is not correctly installed.

**Comment by badaiardiat** [comment]
how to do that? sorry im newbie for this

**Comment by shprink** [comment]
In here:

![image](https://cloud.githubusercontent.com/assets/1388706/16908067/fe5052ca-4cc8-11e6-87c0-1c77ef3d18cb.png)

you can type JavaScript. Try `StatusBar`. If undefined then the plugin is not correctly installed

**Comment by badaiardiat** [comment]
![statusbarbaru](https://cloud.githubusercontent.com/assets/19369415/16908183/eb2b05e8-4cf3-11e6-9d96-ef7fce22e885.png)
error dude, what i must do?

**Comment by shprink** [comment]
run `./node_modules/.bin/cordova plugin list` in the terminal and dump the result here

**Comment by badaiardiat** [comment]
`va plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
com.telerik.plugins.nativepagetransitions 0.5.5 "Native Page Transitions"
cordova-plugin-admobpro 2.14.0 "AdMob Plugin Pro"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-crosswalk-webview 1.6.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-file 2.1.0 "File"
cordova-plugin-file-transfer 1.2.1 "File Transfer"
cordova-plugin-globalization 1.0.1 "Globalization"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.1 "SocialSharing"
nl.x-services.plugins.toast 2.1.1 "Toast"
org.pushandplay.cordova.apprate 1.1.7 "AppRate"
phonegap-plugin-push 1.5.3 "PushPlugin"`

**Comment by shprink** [comment]
you do not have the right statusBar version for some reason.

https://github.com/shprink/wordpress-hybrid-client/blob/develop/package.json#L115

you should have 1.0.1.

**Comment by badaiardiat** [comment]
ohh ok sir, how to downgrade that ?

**Comment by shprink** [comment]
run `npm run restore` and dump the result here. here is mine:

```
$ npm run restore

> wordpress-hybrid-client@2.0.0-beta10 restore /Users/shprink/Sites/WPHC/wordpress-hybrid-client
> ionic state restore

Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android@5.x
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist@1.0.0
cordova plugin add cordova-plugin-inappbrowser@1.3.0
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-file@2.1.0
cordova plugin add cordova-plugin-file-transfer@1.2.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-network-information@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate#v1.1.7
cordova plugin add cordova-plugin-x-toast@2.1.1
cordova plugin add https://github.com/driftyco/ionic-plugin-keyboard#v1.0.4
cordova plugin add cordova-plugin-statusbar@1.0.1
cordova plugin add cordova-plugin-google-analytics@0.8.1
cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5
cordova plugin add phonegap-plugin-push@1.5.3
cordova plugin add cordova-plugin-crosswalk-webview@1.6.0
cordova plugin add cordova-plugin-spinner-dialog@1.3.1
cordova plugin add cordova-plugin-admobpro@2.14.0
cordova plugin add cordova-plugin-x-socialsharing@5.1.1
```

**Comment by badaiardiat** [comment]
root@badai-X450LD:/home/badai/wordpress-hybrid-client# npm run restore

> wordpress-hybrid-client@2.0.0-beta10 restore /home/badai/wordpress-hybrid-client
> ionic state restore

Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android@5.x
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist@1.0.0
cordova plugin add cordova-plugin-inappbrowser@1.3.0
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-file@2.1.0
cordova plugin add cordova-plugin-file-transfer@1.2.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-network-information@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate#v1.1.7 
cordova plugin add cordova-plugin-x-toast@2.1.1
cordova plugin add https://github.com/driftyco/ionic-plugin-keyboard#v1.0.4 
cordova plugin add cordova-plugin-statusbar@1.0.1
cordova plugin add cordova-plugin-google-analytics@0.8.1
cordova plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5 
cordova plugin add phonegap-plugin-push@1.5.3
cordova plugin add cordova-plugin-crosswalk-webview@1.6.0
cordova plugin add cordova-plugin-spinner-dialog@1.3.1
cordova plugin add cordova-plugin-admobpro@2.14.0
cordova plugin add cordova-plugin-x-socialsharing@5.1.1
Restore plugins is complete

Ionic state restore completed

**Comment by shprink** [comment]
as you can see `cordova-plugin-statusbar@1.0.1` was installed . Re run `./node_modules/.bin/cordova plugin list` now

**Comment by badaiardiat** [comment]
./node_modules/.bin/cordova plugin list
com.ionic.keyboard 1.0.4 "Keyboard"
com.telerik.plugins.nativepagetransitions 0.5.5 "Native Page Transitions"
cordova-plugin-admobpro 2.14.0 "AdMob Plugin Pro"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-crosswalk-webview 1.6.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-extension 1.5.1 "Cordova Plugin Extension"
cordova-plugin-file 2.1.0 "File"
cordova-plugin-file-transfer 1.2.1 "File Transfer"
cordova-plugin-globalization 1.0.1 "Globalization"
cordova-plugin-google-analytics 0.8.1 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-spinner-dialog 1.3.1 "SpinnerDialog"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-x-socialsharing 5.1.1 "SocialSharing"
nl.x-services.plugins.toast 2.1.1 "Toast"
org.pushandplay.cordova.apprate 1.1.7 "AppRate"
phonegap-plugin-push 1.5.3 "PushPlugin"

But still error 
![errortetep](https://cloud.githubusercontent.com/assets/19369415/16908836/b0cf87c0-4cf8-11e6-98d9-82397bd4aabd.png)

**Comment by shprink** [comment]
have you rebuilt the app?

**Comment by badaiardiat** [comment]
using npm run android

**Comment by shprink** [comment]
looks like you do not have the `cordova_plugin.js` file.

Does `platforms/android/assets/www` have all files? (i.e. a plugins folder with scripts, cordova_plugins.js should mention your plugin, a platform-specific cordova.js)

Here is mine:

![image](https://cloud.githubusercontent.com/assets/1388706/16910050/948b110a-4cd6-11e6-9ae4-2f816ae24646.png)

**Comment by badaiardiat** [comment]
i have all file 
![file](https://cloud.githubusercontent.com/assets/19369415/16910391/95bff4ec-4d02-11e6-8262-457c6ed7377a.png)

**Comment by shprink** [comment]
then maybe it is a problem with the emulator. Try on a real device.

**Comment by badaiardiat** [comment]
Nexus_5X_API_22 86x_64
already try on a readl device but stil blank just white screen -_-
or my OS problem :(

**Comment by shprink** [comment]
run this and try again.

```
rm -rf platforms/ plugins/ && npm run restore && npm run android
```

**Comment by badaiardiat** [comment]
error sir 
[ 94%] /data/local/tmp/android-x86-debug.apk
[ 94%] /data/local/tmp/android-x86-debug.apk
[ 95%] /data/local/tmp/android-x86-debug.apk
[ 95%] /data/local/tmp/android-x86-debug.apk
[ 95%] /data/local/tmp/android-x86-debug.apk
[ 95%] /data/local/tmp/android-x86-debug.apk
[ 96%] /data/local/tmp/android-x86-debug.apk
[ 96%] /data/local/tmp/android-x86-debug.apk
[ 96%] /data/local/tmp/android-x86-debug.apk
[ 96%] /data/local/tmp/android-x86-debug.apk
[ 96%] /data/local/tmp/android-x86-debug.apk
[ 97%] /data/local/tmp/android-x86-debug.apk
[ 97%] /data/local/tmp/android-x86-debug.apk
[ 97%] /data/local/tmp/android-x86-debug.apk
[ 97%] /data/local/tmp/android-x86-debug.apk
[ 97%] /data/local/tmp/android-x86-debug.apk
[ 98%] /data/local/tmp/android-x86-debug.apk
[ 98%] /data/local/tmp/android-x86-debug.apk
[ 98%] /data/local/tmp/android-x86-debug.apk
[ 98%] /data/local/tmp/android-x86-debug.apk
[ 99%] /data/local/tmp/android-x86-debug.apk
[ 99%] /data/local/tmp/android-x86-debug.apk
[ 99%] /data/local/tmp/android-x86-debug.apk
[ 99%] /data/local/tmp/android-x86-debug.apk
[ 99%] /data/local/tmp/android-x86-debug.apk
[100%] /data/local/tmp/android-x86-debug.apk
	pkg: /data/local/tmp/android-x86-debug.apk
Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]

You may not have the required environment or OS to run this project
root@badai-X450LD:/home/badai/wordpress-hybrid-client#

**Comment by shprink** [comment]
`INSTALL_FAILED_INSUFFICIENT_STORAGE` is clear enough is not it?

**Comment by badaiardiat** [comment]
OMGGGGGG 
thanksss u very much dude
Already work 
Thanksssssssssssssssssssssssssssssssssssssssssssssss
