### ISSUE TITLE
Can't walkthrough from custom taxonomies to a custom post

### ISSUE THREAD

**Issue by Aditha-Sansa** [shprink/wordpress-hybrid-client#261]
I've put `"route": "public.taxonomies({ term: 'make', postType: 'listings'})"` in order to get custom taxonomies list of available "Makes", like in the following image. But When one item is clicked, all listings are shown instead of showing only the related ones. 

![customtaxonomies_01](https://cloud.githubusercontent.com/assets/11178783/16900273/c180e502-4c3d-11e6-933f-4b6868f25e68.jpg)

When one item is clicked:
![customtaxonomies_02](https://cloud.githubusercontent.com/assets/11178783/16900299/d4d898f6-4c3e-11e6-97ad-0dc38e804e08.jpg)

Thanks for your time.

**Comment by shprink** [comment]
That really depends on the custom post type that you created.

Check this example out: https://github.com/shprink/wordpress-hybrid-client/blob/develop/dist/menu.json#L91-L106

Open http://m.julienrenaux.fr/ and play with it:

![image](https://cloud.githubusercontent.com/assets/1388706/16901287/5db5b46a-4c3f-11e6-9fbc-9ae98fc16355.png)

In your case clicking on Toyota should return the Toyota cars. If not then make sure your server returns the right information.
