### ISSUE TITLE
How to edit display in single post

### ISSUE THREAD

**Issue by badaiardiat** [shprink/wordpress-hybrid-client#262]
![single post](https://cloud.githubusercontent.com/assets/19369415/16941617/5fc432d6-4dbb-11e6-8be2-748e2cafe339.png)

i will edit this display, but i dont know file script for this

**Comment by shprink** [comment]
You will find all the docs in there: https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md
