### ISSUE TITLE
Not allowed to load local resource: file:///android_asset/www/index.html

### ISSUE THREAD

**Issue by jefflinhq** [shprink/wordpress-hybrid-client#264]
I am trying to build this on OSX for Android. I am able to run the latest version v2.0 beta 10 on dev server. But when I ran it with Android phone or emulator, I got an File Not Found error. It couldn't find the index.html file.
 
![screen shot 2016-08-01 at 2 21 00 pm](https://cloud.githubusercontent.com/assets/20778554/17304348/3a6abeaa-57f3-11e6-869f-a6808426e11e.png)

I checked the  apk file. It is actually there. Below is the debug info from Chrome.
![screen shot 2016-08-01 at 2 24 30 pm](https://cloud.githubusercontent.com/assets/20778554/17304517/f0341c90-57f3-11e6-98c9-c10f9210bdf4.png)

**Not allowed to load local resource: file:///android_asset/www/index.html**

I am new to mobile app development and have googled around for hours to fix this. So please bear with me if the answer is obvious.

**Comment by shprink** [comment]
`rm -rf platforms/ plugins/ && npm run restore && npm run android`

Try reinstalling the app and let me know

**Comment by jefflinhq** [comment]
Reinstalling the app did the trick. It works now.
