### ISSUE TITLE
Not working after setup

### ISSUE THREAD

**Issue by sannyrss** [shprink/wordpress-hybrid-client#265]
I installed same way as suggested in the documentation but it s not working.

I checkout with the version v2.0.0-beta09. 

Now after all the process when I use IONIC SERVE (http://172.20.24.116:8100) it says MISSING **INDEX.HTML** 

I tried http://172.20.24.116:8100/webpack-dev-server/ but shows : Cannot GET /webpack-dev-server/

Also I checked in the folder www it has only .gitignore file

Please tell me what mistake I am doing. 

Thanks

**Comment by shprink** [comment]
do not use ionic serve . Use `npm run devserver`

**Comment by sannyrss** [comment]
It returns this:

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "devserver"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! path /var/www/html/App/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/www/html/App/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/html/App/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/App/npm-debug.log

Please Help!

**Comment by shprink** [comment]
Try the quick start commands again in a folder where you have the rights:

https://github.com/shprink/wordpress-hybrid-client#quick-start

**Comment by sannyrss** [comment]
I tried fresh installation but at the time of checkout it says:

Note: checking out 'v2.0.0-beta10'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 571a374... Merge branch 'release/2.0.0-beta10'


What does this mean and last time also it was showing and I did some alternative and result did not work.

Please suggest the right step here.

Thanks in advance.

**Comment by shprink** [comment]
there is nothing to do here. continue the steps

**Comment by sannyrss** [comment]
You are super fast, thank you.

Just proceeding..!!

Stay with me please..!!

Thanks

**Comment by sannyrss** [comment]
After the command npm **$ install && npm run installWPHC**
It shows many warnings, does this need to be corrected to get desired result?

```

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/App/wordpress-hybrid-client/npm-debug.log

```

After command **$npm run devserver**

`
> wordpress-hybrid-client@1.7.0 devserver /var/www/html/App/wordpress-hybrid-client
> webpack-dev-server --port 8080 --json --progress

module.js:327
    throw err;
    ^

Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/App/wordpress-hybrid-client/webpack.config.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "devserver"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@1.7.0 devserver: `webpack-dev-server --port 8080 --json --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wordpress-hybrid-client@1.7.0 devserver script 'webpack-dev-server --port 8080 --json --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8080 --json --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/App/wordpress-hybrid-client/npm-debug.log
`

It did not run again.

**Comment by shprink** [comment]
> Not compatible with your operating system or architecture

what OS are you using?

**Comment by sannyrss** [comment]
Ubuntu

**Comment by shprink** [comment]
try to upgrade node to v6

**Comment by sannyrss** [comment]
Okay Thank you Will Try.

It can not be from Windows right?

**Comment by shprink** [comment]
yes

**Comment by shprink** [comment]
join the chat it will be easier to discuss https://gitter.im/shprink/wordpress-hybrid-client

**Comment by sannyrss** [comment]
Okay I will try with my MAC once, LINUX is a pain.

But still very thankful to you, you gave a quick and great support.
