### ISSUE TITLE
 Android Compatibility List

### ISSUE THREAD

**Issue by pavini** [shprink/wordpress-hybrid-client#268]
Dears, 
What can I do to increase the list of compatible devices. Today with a fresh install, my list is 383 devices. Most are tablets.

**Comment by shprink** [comment]
android? are you uploading both arm and x86 apks?

**Comment by pavini** [comment]
Yes android. I upload only x86,. 
I did not know that it should send the two versions . I will do this.

Tks a lot!

**Comment by shprink** [comment]
yes you need to enable the advance mode and upload both apks so you will cover most of the devices ;) Closing
