### ISSUE TITLE
Beta 11 error Error: ENOENT: no such file or directory, open '/wordpress-hybrid-client-2.0.0-beta11/www/index.html'

### ISSUE THREAD

**Issue by koboldsp** [shprink/wordpress-hybrid-client#270]
I get a fresh install of beta 11 and after build i try to run `npm start` and get this msg

`Error: ENOENT: no such file or directory, open '/Users/pavini/Downloads/wordpress-hybrid-client-2.0.0-beta11/www/index.html'`

**Comment by shprink** [comment]
can you past the whole error stack please?

**Comment by koboldsp** [comment]
This is the whole error that show in the browser or in when a open in android emulator. (in emulator show a popup as you can see on attached image
![screen shot 2016-09-05 at 08 29 40](https://cloud.githubusercontent.com/assets/13852064/18246579/edb0267a-7342-11e6-8a21-f837a5cad0ef.png)

**Comment by shprink** [comment]
`npm start` is for the browser. If you want to run Android run `npm run android`

**Comment by koboldsp** [comment]
Yes, I know... I just show you the same error when run `npm run android`.

**Comment by shprink** [comment]
if you see this error, you have an error on the webpack build. Can you please share the whole stack?

Try to re install: `rm -rf node_modules/ && npm i` in case
