### ISSUE TITLE
Admob on iOS

### ISSUE THREAD

**Issue by koboldsp** [shprink/wordpress-hybrid-client#272]
Dear,

In my iOS version, I can´t see the admob banner. I get this message in console:

<Google> Invalid Request. Cannot determine request type. Is your ad unit id correct?
AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'banner','adEvent':'onAdFailLoad','error':0,'reason':'Request Error: Invalid ad request parameter(s). 

My config.cson file

```
"admob":
        "enabled":true
        "android":
            "bannerID": "ca-app-pub-xxxxxxxx/xxxx" (I´m using my correct banner id)
            "interstitialID": null
        "ios":
            "bannerID": "ca-app-pub-xxxxx/xxxxx" (I´m using my correct banner id)
            "interstitialID": null
```

**Comment by shprink** [comment]
The indentation of the config file is very important. Please use markdown to properly display it here.

**Comment by koboldsp** [comment]
Sorry...

In config the indentation is correct.

![screen shot 2016-09-12 at 09 08 27](https://cloud.githubusercontent.com/assets/13852064/18435352/f2730160-78c8-11e6-8015-6d631ab4277e.png)

**Comment by shprink** [comment]
It does look correct. Have you tried on android?

**Comment by koboldsp** [comment]
In android is working good!

**Comment by shprink** [comment]
IDK, try to display an `interstitial` to test please.

**Comment by koboldsp** [comment]
Same error

`2016-09-12 11:28:37.091 NH Noticias[32788:4214966] <Google> Invalid Request. Cannot determine request type. Is your ad unit id correct?
2016-09-12 11:28:37.093 NH Noticias[32788:4214597] AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'banner','adEvent':'onAdFailLoad','error':0,'reason':'Request Error: Invalid ad request parameter(s). Check the Xcode console for details.'}`

**Comment by shprink** [comment]
Put this somewhere to get the details
```
document.addEventListener('onAdFailLoad', function(e){
   if(typeof e.originalEvent !== 'undefined') e = e.originalEvent;
      var data = e.detail || e.data || e;
      alert('error: ' + data.error +
          ', reason: ' + data.reason +
          ', adNetwork:' + data.adNetwork +
          ', adType:' + data.adType +
          ', adEvent:' + data.adEvent); // adType: 'banner', 'interstitial', etc.
})
```

**Comment by koboldsp** [comment]
Can you specify where I can put this code, please? I´m new with this...

**Comment by shprink** [comment]
put is under `$ionicPlatform.ready(() => {` in `lib/cordova/cordova.admob.js` file

**Comment by koboldsp** [comment]
I think that i should see a alert with more details, but not. I get the error in console but in emulator not show the alert.

`2016-09-12 11:45:50.944 NH Noticias[33259:4228220] <Google> Invalid Request. Cannot determine request type. Is your ad unit id correct?
2016-09-12 11:45:50.946 NH Noticias[33259:4226187] AdMob, onAdFailLoad, {'adNetwork':'AdMob','adType':'banner','adEvent':'onAdFailLoad','error':0,'reason':'Request Error: Invalid ad request parameter(s). Check the Xcode console for details.'}
`

**Comment by shprink** [comment]
use safari to debug via the console. Check for any JS errors.

**Comment by koboldsp** [comment]
As you can see on image, the safari debug do not show anything.

![screen shot 2016-09-12 at 12 03 07](https://cloud.githubusercontent.com/assets/13852064/18440867/0ae81c68-78e1-11e6-9ed2-587b86fecf52.png)

After some clicks, this is the safari console

![screen shot 2016-09-12 at 12 07 47](https://cloud.githubusercontent.com/assets/13852064/18441045/ccdfe2b0-78e1-11e6-8f87-ae2ad190cc32.png)

**Comment by shprink** [comment]
I need the complete trace (the beginning is missing). try to reload the webview using `command + R`

**Comment by koboldsp** [comment]
![screen shot 2016-09-12 at 12 22 18](https://cloud.githubusercontent.com/assets/13852064/18441506/b032e764-78e3-11e6-972f-81390de25778.png)

**Comment by shprink** [comment]
ok nothing there. Have you tried on real device? Maybe admobs does not display ads on emulator (which is understandable).

**Comment by koboldsp** [comment]
Running on my iPhone.

In Xcode console, same error.

![screen shot 2016-09-12 at 12 48 30](https://cloud.githubusercontent.com/assets/13852064/18442467/3b64e65e-78e7-11e6-8ad9-046643de4bf2.png)

**Comment by shprink** [comment]
try to dump the variables in https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/cordova/cordova.admob.js

```
if (AdMob && bannerID) {
    console.log('HERE', bannerID, AdMob.AD_POSITION[bannerPosition]);
                AdMob.createBanner({
                    adId: bannerID,
                    position: AdMob.AD_POSITION[bannerPosition],
                    autoShow: true
           });
}
```

If the inputs are fine then it is a problem with the admobs/cordova version

**Comment by shprink** [comment]
hello, any update?

**Comment by pavini** [comment]
Hi @shprink ,

Still not working on ios :( I stop to try to make work...

**Comment by shprink** [comment]
Just tested and it worked on my side.

my config is the following:

```
"cordova":
    "admob":
        "enabled": true
        "android":
            "bannerID": 'ca-app-pub-XXXX/YYYY'
            "interstitialID": 'ca-app-pub-XXXX/WWW'
        "ios":
            "bannerID": 'ca-app-pub-XXXX/YYYY'
            "interstitialID": 'ca-app-pub-XXXX/WWW'
```

![image](https://cloud.githubusercontent.com/assets/1388706/20237500/48b58b0c-a8d4-11e6-97af-1ddc3f58cbbe.png)


I am going to close this. I have added more logs into the new version (will release today). Please try it out
