### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by happy-dev** [shprink/wordpress-hybrid-client#274]
Hello, 

I want to give **Wordpress-Hybrid-Client** a try, as I am building a Wordpress app with Ionic, but I am not able to install the framework. I followed [those installations guidelines](https://github.com/shprink/wordpress-hybrid-client/blob/develop/INSTALLATION.md), but when I run `npm install`, the installation get stuck. 

The last logs I get are those : 
```
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm WARN deprecated conventional-changelog@0.0.11: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
```

Node version : **v6.6.0**
NPM version : **v3.10.3**

I am willing to help and solve this. If you provide me with a debugging path, I am ready to take it :) 

Best regards !

**Comment by shprink** [comment]
There is no error in this log, only warnings.

**Comment by happy-dev** [comment]
I know. Still, the installation doesn't get through though.

**Comment by shprink** [comment]
Still do not understand what is your problem. Please share it on the chat https://gitter.im/shprink/wordpress-hybrid-client

**Comment by shprink** [comment]
I re installed today, no problem with npm3 and node6
