### ISSUE TITLE
Date formatting not showing german translation

### ISSUE THREAD

**Issue by jensfae** [shprink/wordpress-hybrid-client#276]
The date conversion of amDateFormat:'dddd, DD.MM' is only showing english days.
Even if in config.cson set to:
"translation":
"displayed" : ["de", "en", "fr"]
"prefered": "de"

German days are not displayed

**Comment by goaround** [comment]
I have not problems with the german date conversion.

**Comment by shprink** [comment]
```
{{authorCtrl.date | amDateFormat:'dddd, DD.MM'}}
```

![image](https://cloud.githubusercontent.com/assets/1388706/19836073/a5b80eda-9e96-11e6-85b8-ace92e752737.png)

Works for me.
