### ISSUE TITLE
Architectures for iOS

### ISSUE THREAD

**Issue by dshamenkov** [shprink/wordpress-hybrid-client#277]
Dear @shprink! Thank you so much for a great support! You are really done a great job!
I already build and release app, based in wphc, but have some questions - one of them - how to build app version which can support earliest architectures (iPhone 5, iPhone 5c, and devices with iOS 7.0)? Thank you so much for answer!

**Comment by shprink** [comment]
you app should be compatible with old iphones too. Have you tried? I am not a iOS guy so I do not have an answer for you. the best would be to search for the answer on Google. We use Cordova iOS you can start here.

**Comment by dshamenkov** [comment]
Yes, I tried of course! It sent me an error while debugging about wrong architecture. So, if there are no limitations from application, I will solve this problem and write here the path! 
Thank you so much for a quick reply!
How can I send you donation for you help, and for using your template?

--
С уважением, 
Дмитрий Шаменков
Член Экспертной коллегии Фонда Сколково
Член Экспертной коллегии Фонда содействия развитию малых форм предприятий в научно-технической сфере (Фонда Бортника)
SUZ.community, Founder&CEO
Руководитель Школы "Система управления здоровьем"

skype: dshamenkov
www.shamenkov.ru
SUZ.community

**Comment by shprink** [comment]
here: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PFP99GE9V56RS

thanks very much
