### ISSUE TITLE
Normal Website

### ISSUE THREAD

**Issue by 3kynox** [shprink/wordpress-hybrid-client#281]
Hello,

does wordpress-hybrid-client can be used for normal websites? And not only ionic / Cordova ?

Any theme creation process simplified ?

Thanks

**Comment by shprink** [comment]
WPHC can be used with any WordPress website. All you need to do is install WP-API plugin.

**Comment by 3kynox** [comment]
That was not my question, sorry if I was not clear.

I don't ask if I can use any wordpress site with WPHC but if I can build a WPHC angular2 frontend for web browsers api-linked to a Wordpress installation besides of ionic / mobile features.

Thanks

**Comment by shprink** [comment]
Still do not understand the question.

If your question is: can I build a website with WPHC, the answer is yes.
You can even create a progressive web app since beta13.

WPHC only works with Ionic1 right now but We could have a Ionic2 version to
play with in January.

**Comment by 3kynox** [comment]
Ok, great news, last question please, does the web version is SEO friendly ?

Thanks again :)

**Comment by shprink** [comment]
that's a great question and the answer is no. SEO and Angular1 are not friends

**Comment by 3kynox** [comment]
Normally angular(2?) allow it ! http://blog.angular-university.io/angular-2-universal-meet-the-internet-of-the-future-seo-friendly-single-page-web-apps/

I saw your documentation page, where I suppose you to use wordpress-hybrid-client and I don't see url changes while navigating throught the menu.

That's why my question :)

**Comment by shprink** [comment]
Angular2 supports Universal rendering so yes it will be possible with Ionic2 version.

**Comment by 3kynox** [comment]
Awww I understand, you still use angular v1 ! I got it.

I also notice we could speak french but maybe it's better to use english for folks :)

Any discord, support channel ? Want me to help ? I'm a php / JS / SaaS coder if needed, I'll be able to post some PR's once I know correctly your system.

I just have to decide with my company if we will use wordpress-hybrid-client for our next websites forest (around game development)

**Comment by shprink** [comment]
We have a support channel on gitter. The link is on the readme ;) talk to
you soon
