### ISSUE TITLE
cannot load more than 2 pages of customPosts

### ISSUE THREAD

**Issue by SharmPRO** [shprink/wordpress-hybrid-client#283]
after loading 2 full pages, the third one does not react. No network activity, just the spinning icon

**Comment by shprink** [comment]
Please share your wp-api baseUrl and the menu json file (with the three pages you want to open).

**Comment by SharmPRO** [comment]
the page i'm try to load is Real Estate -> For Rent (I want to rent out 
my property)

http://www.sharmwomen.com/wp-json/wp/v2/Real_Estate/category/58?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=1&per_page=10

http://www.sharmwomen.com/wp-json/wp/v2/Real_Estate/category/58?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=2&per_page=10

http://www.sharmwomen.com/wp-json/wp/v2/Real_Estate/category/58?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=3&per_page=10

     1.
        Access-Control-Allow-Headers:
        Authorization
     2.
        Access-Control-Expose-Headers:
        X-WP-Total, X-WP-TotalPages
     3.
        Allow:
        GET
     4.
        Cache-Control:
        no-cache, must-revalidate, max-age=0
     5.
        Connection:
        keep-alive
     6.
        Content-Type:
        application/json; charset=UTF-8
     7.
        Date:
        Mon, 17 Oct 2016 12:43:55 GMT
     8.
        Expires:
        Wed, 11 Jan 1984 05:00:00 GMT
     9.
        Keep-Alive:
        timeout=15
    10.
        Last-Modified:
        Thu, 01 Jan 1970 00:00:00 GMT
    11.
        Link:
        </wp/v2/Real_Estate/category/58?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=2&per_page=10>;
        rel="prev",
        </wp/v2/Real_Estate/category/58?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=4&per_page=10>;
        rel="next"
    12.
        Pragma:
        no-cache
    13.
        Server:
        Apache
    14.
        Transfer-Encoding:
        chunked
    15.
        X-Content-Type-Options:
        nosniff
    16.
        X-Powered-By:
        PHP/7.0.11
    17.
        X-Robots-Tag:
        noindex
    18.
        X-WP-Total:
        3727
    19.
        X-WP-TotalPages:
        373
 1. Query String Parametersview sourceview URL encoded
     1.
        _embed:
        true
     2.
        filter[order]:
        desc
     3.
        filter[orderby]:
        date
     4.
        filter[post_status]:
        publish
     5.
        page:
        3
     6.
        per_page:
        10
 2.

"baseUrl": "http://www.sharmwomen.com/wp-json"

[{
     "type": "internal",
     "icon": "icon ion-home",
     "trans": "Sample page",
         "route": "public.pages.id({ id: 4 })"
}, {
     "type": "folder",
     "trans": "Real Estate",
     "icon": "icon ion-videocamera",
     "list": [{
         "type": "internal",
         "trans": "For Rent (I want to rent out my property)",
         "route": "public.customPosts({ slug: 'Real_Estate', category: 
58, subtitle: 'For Rent (I want to rent out my property)' })",
         "icon": "icon ion-videocamera"
         },{
         "type": "internal",
         "trans": "To Rent (I want to find something to rent)",
         "route": "public.customPosts({ slug: 'Real_Estate', category: 
59, subtitle: 'To Rent (I want to find something to rent)' })",
         "icon": "icon ion-videocamera"
         },{
         "type": "internal",
         "trans": "To Buy (I want to buy a property)",
         "route": "public.customPosts({ slug: 'Real_Estate', category: 
61 })",
         "icon": "icon ion-videocamera"
         },{
         "type": "internal",
         "trans": "For Sale (I want to sell my property)",
         "route": "public.customPosts({ slug: 'Real_Estate', category: 
61 })",
         "icon": "icon ion-videocamera"
         }]
}, {
     "type": "internal",
     "trans": "params.title",
     "route": "public.params",
     "icon": "icon ion-gear-b"
}, {
     "type": "external",
     "trans": "My blog (external link)",
     "href": "http://julienrenaux.fr",
     "icon": "icon ion-link"
}, {
     "type": "internal",
     "trans": "About (page)",
     "route": "public.pages.id({ id: 2596 })",
     "icon": "icon ion-information"
}]

**Comment by SharmPRO** [comment]
Still not loading more pages after second.
I can send my codebase to debug ?

**Comment by shprink** [comment]
Yes please remove node_modules/, plugins/ and platforms/ folder and zip the whole project. Send it to contact@julienrenaux.fr. 

thanks

**Comment by shprink** [comment]
Ok I can see a problem. Thanks for reporting.
