### ISSUE TITLE
Post order no longer working in Beta13?

### ISSUE THREAD

**Issue by henmaker** [shprink/wordpress-hybrid-client#288]
I just tried the latest beta13 today, notice this custom order (sort order) no longer working, no matter by title, menu_order etc. It is still sort by date.

# POST PAGES
"posts":
	"query":
		"per_page": 5
		"filter[orderby]": "title"
		"filter[order]": "asc"
		"filter[post_status]": "publish"

**Comment by henmaker** [comment]
i think i found the problem, is not the query not working, is the taxonomiesPosts affected the category posts listed, if have a different query in taxonomiesPosts, it will sort by that query..
In that's the case, seems like we don't have the way to have different sort order for custom taxonomy vs post category, am i correct?

Example. If i define:

# TAXONOMIES
"taxonomiesPosts":
    "query":
        "per_page": 7
        "filter[orderby]": "title"
        "filter[order]": "asc"

Then when i call the menu link via:
{
    "type": "internal",
    "trans": "Blog",
    "route": "public.taxonomies.slug({ term: 'category', slug: 'blog', postType: 'post' })",
    "icon" : ""   
}

The blog listing will be orderby title, not date, even i define 
"post":
    "query":
        "filter[orderby]": "date"
        "filter[order]": "asc"
    "comments":
        "enabled": false   

This not going to help, as seems like that is only for home page, which is the default listing only...

**Comment by shprink** [comment]
Can you explain what you are trying to do concisely?

Using a conf like that:

```
"taxonomiesPosts":
    "query":
        "orderby": "title"
        "order": "desc"
```

will affect the order of custom taxonomies items. All of them in the same way. If you list posts or pages it will be the same. For now that's what we have.

![image](https://cloud.githubusercontent.com/assets/1388706/19747471/0d985658-9bdc-11e6-924b-23903ea2ed51.png)

```
"taxonomiesPosts":
    "query":
        "orderby": "title"
        "order": "asc"
```

![image](https://cloud.githubusercontent.com/assets/1388706/19747477/1a05f5a8-9bdc-11e6-8334-a36206ba8423.png)

I can understand that you would expect the `post` query to be used here but that's not the case.

```
"post":
    "comments":
        "enabled": true
        "depth": 2
        "per_page": 50
    "cache":
        "maxAge": 10800000
        "capacity": 10
```

I will make this happen in v3.

**Comment by henmaker** [comment]
Thanks shprink, this is a great script, i would suggest if possible, to make a query that available for each taxonomiesPosts.

Example, if i have a custom post type call Event, and another custom post type is Food, which i have a custom Taxonomies assigned to Event post type which is by Events type, and Food Types for Food custom post type. 

For taxonomiesPosts,
I can define the Event types to be sort by date, but I do not want of "Food types" sort by date, but by title.

If we can define taxonomiesPosts to have a unique key say:

`"taxonomiesPosts":
    "query":
        "term": "food_types"
        "orderby": "title"
        "order": "asc" `

That will be great, since we can sort the post type according to the term we define in config.  

And if possible, make customPosts to have something like this, that will be awesome. As currently, customPost query is apply to all custom post type, if there is options like:

`"customPosts":
    "query":
        "post_type": "food"
        "orderby": "title"
        "order": "asc" `

then that will be great. Just a suggestion, i saw some one suggest to define query in "menu.json" but i think config should be the right way, just like how we can define sorting in our wordpress function.php.

Keep up the good job, appreciate the hard works, i will contribute to make this script better too.

**Comment by shprink** [comment]
We can easily do something like this:

```
"taxonomiesPosts":
    "query":
        "orderby": "title"
        "order": "asc"
    "post"
        "query":
            "orderby": "date"
            "order": "asc"
    "page"
        "query":
            "orderby": "date"
            "order": "desc"
```

`taxonomiesPosts.query` would be the default and if `taxonomiesPosts.post` exists when we want to display posts then we will use it.

would this be ok for your use case?

**Comment by henmaker** [comment]
Hi shprink, you mean, this is a new query for your new version or this query can be use in beta13? As i tried, it return the error message:

./config/config.cson
Module build failed: [stdin]:50:5: error: unexpected newline
    "post"
    ^
 @ ./lib/config.js 13:24-56

**Comment by henmaker** [comment]
Hi shprink, after update to beta14, and run the sudo npm run android to deploy into androids and using Chrome inspector, i notice there is this error:

TypeError: Object.assign is not a function
    at _default.getMergedQuery (file:///android_asset/www/bundle-a8687f.js:126066:28)
    at _default.doLoadMore (file:///android_asset/www/bundle-a8687f.js:126030:31)
    at _default.init (file:///android_asset/www/bundle-a8687f.js:126001:26)
    at fn (eval at <anonymous> (file:///android_asset/www/bundle-a8687f.js:27900:16), <anonymous>:2:252)
    at Controller.destination.(anonymous function) [as onLoad] (file:///android_asset/www/bundle-a8687f.js:23371:23)
    at Controller.load (file:///android_asset/www/bundle-a8687f.js:129309:24)
    at file:///android_asset/www/bundle-a8687f.js:129296:24
    at file:///android_asset/www/bundle-a8687f.js:32585:32
    at completeOutstandingRequest (file:///android_asset/www/bundle-a8687f.js:19456:11)
    at file:///android_asset/www/bundle-a8687f.js:19732:8(anonymous function) @ console-via-logger.js:174(anonymous function) @ bundle-a8687f.js:27056(anonymous function) @ bundle-a8687f.js:23769(anonymous function) @ bundle-a8687f.js:32588completeOutstandingRequest @ bundle-a8687f.js:19456(anonymous function) @ bundle-a8687f.js:19732


Any ideas why? I'm using clean install also the same... When run iOS emulator and check, no such error...

**Comment by shprink** [comment]
damn, I should I used `angular.merge` ... Object.assign is ES6

**Comment by shprink** [comment]
https://github.com/shprink/wordpress-hybrid-client/issues/294

I fixed it but have not tested. please try it out on `develop` or copy manually the change

**Comment by henmaker** [comment]
Thanks it is fine now
