### ISSUE TITLE
Author page

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#30]
Having a way to display all author posts

**Comment by shprink** [comment]
List: http://wp-api.org/#users_retrieve-users
Authors articles: http://julienrenaux.fr/wp-json/posts?filter[orderby]=desc&filter[post_status]=publish&filter[posts_per_page]=6&filter[s]=test&page=1&author=3335235"

**Comment by shprink** [comment]
Requires authentification:

https://www.npmjs.com/package/wp-api-angularjs#users-wpapiusers

**Comment by shprink** [comment]
Good news @mingxia with WP-API v2, authors are available without authentifications. I have started to map the services https://github.com/shprink/wp-api-angularjs/tree/v2
Next release will probably support WP-API v2 :)

**Comment by mingxia** [comment]
great！ i will fork it！

**Comment by shprink** [comment]
I will let you know when the project is ready to get help from others. I need to update the readme and setup some basics first, but I will definitely need your help @mingxia  :)

**Comment by mingxia** [comment]
No problem, very happy to be able to contribute.

**Comment by shprink** [comment]
Done in v2
