### ISSUE TITLE
iOS notifications not working 

### ISSUE THREAD

**Issue by mayurss786** [shprink/wordpress-hybrid-client#304]
/pnfw/categories/?os=iOS&token=5e99cccce6eb2770924d49bd5f154970fe283cc809cbc93fbe9f18c12faad078 API Error (401) from IP address 2405:204:e504:eef2:64d5:bac4:f355:6159: Unauthorized, Token not registered. To solve the problem please uninstall and reinstall the app..

Tried so many times

After app install wp plugin show subscriber
But while add a new post no notification sent it says

Finished iOS notificationsShow more details
November 27, 2016 9:44 am
Processing new subpage with 0 tokensShow more details
November 27, 2016 9:44 am
Processing new chunk from offset 0Show more details
November 27, 2016 9:44 am
Starting iOS notificationsShow more details
November 27, 2016 9:44 am
INFO: Disconnected.Show more details
November 27, 2016 5:30 am
INFO: Reading...Show more details
November 27, 2016 5:30 am
INFO: Connected to tls://feedback.push.apple.com:2196.Show more details
November 27, 2016 5:30 am
INFO: Trying tls://feedback.push.apple.com:2196...Show more details
November 27, 2016 5:30 am
Feedback Provider is running.Show more details
November 27, 2016 5:30 am

Now if i check in app parameters push notifications are always disabled 

When i try to enable it adds anonymous subscriber in wp panel, but when i again check push setting, it again shows disabled with this devug log

/pnfw/categories/?os=iOS&token=5e99cccce6eb2770924d49bd5f154970fe283cc809cbc93fbe9f18c12faad078 API Error (401) from IP address 2405:204:e504:eef2:64d5:bac4:f355:6159: Unauthorized, Token not registered. To solve the problem please uninstall and reinstall the app..

**Comment by mayurss786** [comment]
I can add so many subscribers via one device, by doing enable push->check again-> enable push

**Comment by shprink** [comment]
Have you followed that? https://github.com/shprink/wordpress-hybrid-client/blob/develop/PUSHNOTIFICATIONS.md#param-tells-me-that-i-am-not-registered

**Comment by mayurss786** [comment]
Yes

**Comment by mayurss786** [comment]
Even I tested on 3 iOS devices

**Comment by shprink** [comment]
If `/pnfw/categories/?os=iOS&token=5e99cccce6eb2770924d49bd5f154970fe283cc809cbc93fbe9f18c12faad078` does not work then the app cannot know if you are registered or not. That's the reason is shows that you are not register.

Try to find out why this http requests does not work. Maybe share the response with the WordPress plugin creator. 

Let me know it works on my side.

**Comment by mayurss786** [comment]
Please explain how to do this

**Comment by shprink** [comment]
With Safari you can open the dev tools to inspect the device. https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html

**Comment by mayurss786** [comment]
i am in big trouble
unable to update macos, having OS X Yosemite with Xcode 7
iPhone has iOS 10.1.1 

without update can't get logs
is there any way, because I installed app in Device via TestFlight

**Comment by shprink** [comment]
To build iOS 10 you need xCode 8 I beleive. I do not have much time to debug this, I would love to have some detailled logs if you have enough knowledge in web development
