### ISSUE TITLE
youtube videos width is not matching to the app

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#305]
![screenshot from 2016-12-05 12-55-39](https://cloud.githubusercontent.com/assets/14105960/20876768/4621d706-baea-11e6-99ca-3e3b6dc7fc3c.png)
![screenshot from 2016-12-05 12-56-27](https://cloud.githubusercontent.com/assets/14105960/20876769/4622c260-baea-11e6-8b2a-adaa4c180145.png)

how align youtube video in proper size?

**Comment by shprink** [comment]
Jetpack does this for you. Inspect this post: https://m.julienrenaux.fr/#/public/posts/2585

**Comment by Prabhat36** [comment]
ok i did install jetpack plugin still facing same issue.

**Comment by Prabhat36** [comment]
how to setup jetppack?

**Comment by shprink** [comment]
https://jetpack.com/support/shortcode-embeds/
