### ISSUE TITLE
In WP v4.7 REST API posts?filter[category_name]= does not work!

### ISSUE THREAD

**Issue by vankof** [shprink/wordpress-hybrid-client#308]
I have installed WPHC v2.0.0-beta16 on Linux. The installation is OK, requests to dev.julienrenaux.fr/wp-json working OK, but I found some problem on my own WP server side. I have installed new WP 4.7 + WP Rest API. But categories, search, tags filtering does not work - each time all posts are shown. This is critical.

I found an article: https://jeremy.hu/update-rest-api-post-embeds/ - it tells that in WP 4.7 filter will NOT work:
**wp-json/wp/v2/posts?filter[category_name]=wordpress**

Now need to be:
**wp-json/wp/v2/posts?categories=11**
and need to retrieve by ID, not slug.

I have **downgrade WP** (with help of plugin WP Downgrade) **from 4.7 to 4.6.1 - this fixed this issue**. Now wp-json/wp/v2/posts?filter[category_name]= works OK!

But are there other solutions? Plugins for WP? Or need to make core update to WPHC to use new API techniques?

**Comment by caseylessard** [comment]
Same problem on a live app here.

**Comment by caseylessard** [comment]
Reverting to 4.6.1 as directed above fixed the problem. But obviously this is a short-term fix. Does the latest beta fix this?

**Comment by shprink** [comment]
nope, we need to evolve to handle those breaking changes. Please do not upgrade until this is resolved.

**Comment by shprink** [comment]
I will not have time off until beginning of January. Just be patient for this. PR are welcome :)

**Comment by pinkasey** [comment]
If I find time, maybe I'll try solving this.
@shprink -
My idea of a solution is to adapt to WP new built-in API, while retaining support to old API.
Switching APIs could be done by configuration, e.g:
 ### config.cson:
"api":
    "baseUrl": "https://dev.julienrenaux.fr/wp-json"
    "timeout": 30000
    "maxAttempt": 3
    **"usePluginApi": false**

Or alternatively, it can be deduced from the baseUrl.
What do you think?

**Comment by shprink** [comment]
Does it imply to create a WP plugin?

**Comment by pinkasey** [comment]
No.
WP 4.7 comes with integrated API:
https://wordpress.org/news/2016/12/vaughan/

If I understand correctly, WP API 1 was integrated to it (not version 2, which we use).

**Comment by shprink** [comment]
ok, is it two different endpoints?

**Comment by shprink** [comment]
it seems `/wp/v2/posts`

**Comment by shprink** [comment]
you can select the Rest api you want using `baseUrl` only then.

**Comment by shprink** [comment]
WP-API being integrated to the core is really great, we wont need to install a plugin anymore. Will make the necessary changes and update the Docs ASAP (most probably first week of january)

**Comment by pinkasey** [comment]
Awesome
I think so too.

I'm not sure I understand what an endpoint is.
If "wp-json" is an endpoint, then yes - the both use the same endpoint:
[https://developer.wordpress.org/rest-api/routes-and-endpoints/#endpoints
](https://developer.wordpress.org/rest-api/routes-and-endpoints/#endpoints
)So my suggestion about deducing which api to use from the "api.baseUrl" config would not work.

**Comment by pinkasey** [comment]
Thanks!
Works for me.

**Comment by bigbassroller** [comment]
wp-json/wp/v2/posts?filter[category_name]=cat still doesn't work. Did it change?

**Comment by ugurcandede** [comment]
https://github.com/shprink/wordpress-hybrid-client/blob/develop/INSTALLATION.md#L51

**Comment by ugurcandede** [comment]
@bigbassroller 
https://github.com/shprink/wordpress-hybrid-client/blob/develop/INSTALLATION.md#L51

**Comment by shprink** [comment]
yes please update you WP to 4.7 or higher

**Comment by mantagen** [comment]
@bigbassroller 
see: https://github.com/WP-API/WP-API/issues/2990

Since WP 4.7, filter has been removed from WP-API
  _no idea why_
Need to use https://github.com/WP-API/rest-filter
