### ISSUE TITLE
i want native flip transition how to do that?

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#309]
# IONIC
"ionicConfig":
    "views":
        "transition": null
        "maxCache": 10
        "forwardCache": false
    "scrolling":
        "jsScrolling": false
    "backButton":
        "icon": null
        "previousTitleText": null
    "form":
        "checkbox": null
        "toggle": null
    "spinner":
        "icon": null
    "tabs":
        "style": null
        "position": null
    "templates":
        "maxPrefetch": null
    "navBar":
        "alignTitle": null
        "positionPrimaryButtons": null
        "positionSecondaryButtons": null

**Comment by Prabhat36** [comment]
@shprink  help please

**Comment by shprink** [comment]
The native transition plugin is not maintained, you should not use it.
