### ISSUE TITLE
How to make page title center display？

### ISSUE THREAD

**Issue by mingxia** [shprink/wordpress-hybrid-client#31]
this Screenshot is from android app

![2015-07-05 10 00 19](https://cloud.githubusercontent.com/assets/12199412/8510008/3a6db28a-22fd-11e5-9e42-f16dc1701c49.png)

**Comment by shprink** [comment]
Ionic follow each platform specification to display some of the UI component. The page title is therefor left aligned on android and centered on iOS.

WPHC does not let you change this for now. What you can do is to add css rules to the config.scss file to align the title the way you want.

Does it answer your question?

**Comment by mingxia** [comment]
The introduction is very clear, thank you.
