### ISSUE TITLE
How to iterate over images from json 

### ISSUE THREAD

**Issue by Aditha-Sansa** [shprink/wordpress-hybrid-client#313]
This is basically angular related issue , I'm a newbie to the framework. I have 'vehicle_images:' array from wp rest api which I want to iterate over the 'guid' field in it. Can you show me an example on how to do it in wPHC

![vehicle images](https://cloud.githubusercontent.com/assets/11178783/21307384/4625a96e-c5fb-11e6-85dd-859d184ac4a5.png)

I've did something like this:
`<ion-item>
     <ul>
            <li data-ng-repeat="guid in vehicle_images">
                <img ng-src="{{::customPostsItemCtrl.item.vehicle_images.guid}}">
            </li>
        </ul>
    </ion-item>`

but the console output is:
` <ion-item>
        <ul>
            
        </ul>
    </ion-item>`

Thank you for your time

**Comment by shprink** [comment]
try that
```
<ion-item> <ul> <li data-ng-repeat="img in customPostsItemCtrl.item.vehicle_images"> <img ng-src="{{::img.guid}}"> </li> </ul> </ion-item>
```

**Comment by Aditha-Sansa** [comment]
Thank you !
