### ISSUE TITLE
Can't run npm run restore

### ISSUE THREAD

**Issue by Aditha-Sansa** [shprink/wordpress-hybrid-client#314]
When I run 'npm run restore' it wont proceed to add 'cordova plugin whitelist' throwing this error(I have set ANDROID_HOME and PATH variables in .bashrc file):

Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "restore"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! wordpress-hybrid-client@2.0.0-beta16 restore: `rm -rf platforms/ plugins/ && ionic state restore`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wordpress-hybrid-client@2.0.0-beta16 restore script 'rm -rf platforms/ plugins/ && ionic state restore'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wordpress-hybrid-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf platforms/ plugins/ && ionic state restore
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wordpress-hybrid-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wordpress-hybrid-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/aditha/other/Projects/Autodirect/app/wordpress-hybrid-client/npm-debug.log

**Comment by shprink** [comment]
You have not installed Android SDK correctly. `ANDROID_HOME` must be defined. If you have set them up, try to source the bash file or reboot your machine.
