### ISSUE TITLE
Apprate popup show every times

### ISSUE THREAD

**Issue by MariusMez** [shprink/wordpress-hybrid-client#317]
Apprate plugin popup show every time at lunch, even after choosing "No, Thanks".

Settings and more informations here : https://github.com/pushandplay/cordova-plugin-apprate#dont-call-rate-dialog-immediately

_Since v2.0.0_

**Comment by shprink** [comment]
v2.0.1 released

**Comment by mingxia** [comment]
#319 v2.0.0 is ok
