### ISSUE TITLE
How add pt-br language and set pt-br as default language

### ISSUE THREAD

**Issue by fredroo** [shprink/wordpress-hybrid-client#322]
Hi how add pt-br language and submit for this project, and set as default and list all languages avaliable to menu params, because show only EN and FR but have more in translation folder
@shprink please help me

**Comment by shprink** [comment]
use your `config/config.cson` file to overwrite any default configuration that is listed in there: https://github.com/shprink/wordpress-hybrid-client/blob/develop/config/config.default.cson#L159-L162
