### ISSUE TITLE
Creating offline (local) page

### ISSUE THREAD

**Issue by AndreyGubin** [shprink/wordpress-hybrid-client#327]
Hello. In my application **I want to create local pages (access without internet)**, but stuck and don't know how to add one of them.

I have installed wordpress, wp-json, npm, etc... Everything works fine. I found how to add online posts, how to change style of pages. App works perfect on my device.

For your understanding - I want to create app for my university. Local (offline) pages will contain map (inside building, no GPS required), list of teachers with contacts. This information should be available locally.

**Comment by shprink** [comment]
The only offline capability is with bookmarks sorry. Adding offline pages is as simple as adding a new module with the associated route and add a link within the menu. If you have AngularJS knowledge it is super easy.
