### ISSUE TITLE
App cannot load data（branch of develop）

### ISSUE THREAD

**Issue by mingxia** [shprink/wordpress-hybrid-client#33]
develop in webserver is No problem，but when build android app （dumpdev），it Always show like this pic（Configuration no problem）：

![2015-07-12 14 28 54](https://cloud.githubusercontent.com/assets/12199412/8636736/e9006986-28a3-11e5-85e1-9997a09f8c95.png)

**Comment by shprink** [comment]
probably related to #23 and #24. Can you share the http errors that you get?

**Comment by mingxia** [comment]
it's ok now! 

still need add:

cordova plugin add cordova-plugin-whitelist

and add <allow-navigation href="http://*/*" /> into config.xml

**Comment by shprink** [comment]
Awesome, I will add this to the documentation.
