### ISSUE TITLE
Running the server does not compile files but reload page in browser

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#330]
even if im not running "npm start"
the servere is loding old file and my changes are not displaying
when i run "npm start" it taks me to this below link and old icon and menu is shown and no changes are being execute on local host
http://localhost:8080/#/public/taxonomies/category/post/Breaking%20News

is this is happening because of service worker?
![screenshot from 2017-02-17 15-35-31](https://cloud.githubusercontent.com/assets/14105960/23061183/c73226b8-f526-11e6-81c2-119745762aea.png)

**Comment by shprink** [comment]
probably, try not to activate the service worker when developing. The service worker cache is cleaned when a new version (config.xml) is released, it is not cleaned on dev.

**Comment by Prabhat36** [comment]
now what should i do? how can i clean on dev

**Comment by shprink** [comment]
Use chrome dev tools

![image](https://cloud.githubusercontent.com/assets/1388706/23067829/4811ddce-f521-11e6-8569-c002defad858.png)

**Comment by Prabhat36** [comment]
yes it worked. thank you @shprink
