### ISSUE TITLE
how to jump into another page of same website in app?

### ISSUE THREAD

**Issue by Prabhat36** [shprink/wordpress-hybrid-client#331]
if i add button with link of another page of my same website, like if from my home page tab,  i added button to this link-https://julienrenaux.fr/contact/ it takes me to webview, but i want to open this contact page into the app, how to do that?

**Comment by shprink** [comment]
Have you tried to play with those options? https://github.com/shprink/wordpress-hybrid-client/blob/develop/config/config.default.cson#L49-L50

docs https://github.com/apache/cordova-plugin-inappbrowser#cordovainappbrowseropen

**Comment by Prabhat36** [comment]
yes i have, but its not that i want to jump to apps about page by clicking button which is created in home page..

**Comment by shprink** [comment]
You want that the content of you post/page/customPost link to pages within the app? Deep linking? This is not implemented

**Comment by Prabhat36** [comment]
yes deep linking. is it possible or not?
but in local host when i use http://localhost:8080/#/public/pages/430 this types of link it allow to jump into my content.. so i thought maybe in app also its possible.

**Comment by shprink** [comment]
possible maybe but not easy. Not on the scope of v2.

**Comment by Prabhat36** [comment]
okay if there is any way please let me know the, thanks @shprink

**Comment by shprink** [comment]
Closing in favor of https://github.com/shprink/wordpress-hybrid-client/issues/148
