### ISSUE TITLE
..and custom javascript?

### ISSUE THREAD

**Issue by maxlinux2000** [shprink/wordpress-hybrid-client#333]
Hi, I'm trying to add to menu a custom button in order to open an simple alert box but it doesn't works, and in the console there is any  error.
I can see a test div (so the custom directive is working) but the javascript doesn't works... why?

I'm trying to add in the config/template/directive/menu.html

```
<div>TEST</div>
<!--
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert 
-->
<button onclick="myFunction()">Try it</button>
<script>
function myFunction() {
    alert("Hello! I am an alert box!");
}
</script>
```
but the button do nothing.

so I tried with ionic...

```
<div>TEST</div>
<!--
http://codepen.io/hannuraina/pen/qIbsE?editors=101
-->
<button ng-click="showPopup()" class="button icon ion-edit">Show Popup</button>
<script>
angular.module('ionicApp', ['ionic'])

.controller('PlaylistsCtrl', function($scope, $ionicPopup, $timeout) {
  $scope.data = {}
  
  // Triggered on a button click, or some other target
  $scope.showPopup = function() {
    var alertPopup = $ionicPopup.alert({
      title: 'Dont eat that!',
      template: 'It might taste good'
    });
    alertPopup.then(function(res) {
      console.log('Thank you for not eating my delicious ice cream cone');
    });
  };
});
</script>
```

still not workinkg, but I can see the TEST div, and the button

Any tips to solve this problem?

![xwphc1](https://cloud.githubusercontent.com/assets/5683921/23340590/2fb2b0e0-fc39-11e6-8676-1f9c1e561223.png)

**Comment by shprink** [comment]
WPHC is just an Angular app, you need to learn how Angular works first. The code you shared cannot work. If you want a custom item within your menu you could create a new directive and overwrite the menu template to add the directive https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/templates/directive/menu.html

The docs explain how to overwrite templates https://github.com/shprink/wordpress-hybrid-client/blob/develop/CONFIGURATION.md#configtemplates

Good luck
