### ISSUE TITLE
About featured image & where to find icons

### ISSUE THREAD

**Issue by alzearafat** [shprink/wordpress-hybrid-client#338]
Hi there!

First, I want to thank you for this great tool... Really helped me a lot!

But I have difficulties about featured image and icons : 

1. Why featured image is blurry? Did I miss something?
2. Where I can find all the icons? I'm trying using this (https://ionicframework.com/docs/v2/ionicons/) but seems not working << **[SOLVED]**
3. Can I add color to my icons?

Anyone care to explain? Any help would be greatly appreciated!

Thank you

**Comment by shprink** [comment]
1. should not be blurry but it depends on the quality of images you uploaded on your website. You can change the quality here https://github.com/shprink/wordpress-hybrid-client/blob/f07482f673d3fc78d49367c92b43793abe6e53b7/lib/directives/post/index.js#L28

2. Use Ionicons v2 not v3
3. you can set the color of any icons using Sass in your `config/config.scss` file.

**Comment by alzearafat** [comment]
wow, that was fast. Thanks @shprink !
