### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by coolwebs** [shprink/wordpress-hybrid-client#34]
Hi there. I am trying to install locally following the instructions here http://wphc.julienrenaux.fr/getting-started.html

It's unable to complete the job in terminal and I keep receiving this error:

Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

This happens even if using "sudo" command prefix.
Is there something I am not doing right or another necessary prefix? I already have NodeJs, NPM and Cordova installed and running latest stable versions. I have the ionic stack installed and am already building/testing ionic apps (from ionic framework templates)

**Comment by shprink** [comment]
seems like you have a problem cloning from github. Have you registered your SSH key on github? https://help.github.com/articles/generating-ssh-keys/

You can also use the https version ```git clone https://github.com/shprink/wordpress-hybrid-client.git``` instead

**Comment by coolwebs** [comment]
I had no idea about registering SSH key on GitHub before you mentioned it. I have cloned from GitHub before and never had any issues with it. Your alternative solution did the trick? Maybe it's worth making a note about it on your docs? (for the noobs like me)

**Comment by shprink** [comment]
You are right, https://github.com/shprink/wordpress-hybrid-client/commit/d4b27e3ccb822cd4f9153d6490becc7fbaf8f4c2

Thanks

**Comment by coolwebs** [comment]
Thanks, I have some other questions for you Julien. What's the best channel to contact you on?

**Comment by shprink** [comment]
https://gitter.im/shprink/wordpress-hybrid-client
