### ISSUE TITLE
Error: /Users/mufaddal/wordpress-hybrid-client/platforms/android/gradlew

### ISSUE THREAD

**Issue by mufaddalm** [shprink/wordpress-hybrid-client#341]
when i run **npm run android**

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 25].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

**Comment by shprink** [comment]
> You have not accepted the license agreements of the following SDK components:

run `android`, update everything that needs to be updated and accept terms.
