### ISSUE TITLE
getting issue from itunes connect

### ISSUE THREAD

**Issue by iRajul** [shprink/wordpress-hybrid-client#345]
When i submit my app  on app store. I keep on getting a mail from apple regarding following issue:
Missing Info.plist key
Missing Push Notification Entitlement 

Though I am not using push notification in my app. 

Please help.

**Comment by shprink** [comment]
Try to remove this line https://github.com/shprink/wordpress-hybrid-client/blob/develop/package.json#L115

then delete plugins/ and platform/ and restore.

building the app without the cordova plugin should solve it.
