### ISSUE TITLE
Progressive web app - where to put it/integrate with wordpress.

### ISSUE THREAD

**Issue by dreadedhamish** [shprink/wordpress-hybrid-client#347]
I'm running a wordpress site, that currently is serving different layouts for mobile and desktop (one template with 2 parts and some is_mobile() conditionals care of mobble.)

I'm wondering how to integrate this with a wordpress installation?
Looking at https://m.julienrenaux.fr/ it's running the pwa full-time.

I guess the easiest would be to redirect mobile users to an m.dot subdomain, or less efficient would be changing the links on the current template to point to the subdomain, so that on their second interaction they'd be pushed to the pwa.

Or is the idea to rewrite even my desktop templates to work with the pwa?

Thanks for any help you can offer.

**Comment by shprink** [comment]
you can have WPHC on a `m` subdomain and your normal WP on `www`. You can redirect the users from one to the other depending on their device using nginx or apache rules.

**Comment by dreadedhamish** [comment]
So you wouldn't use the same for both?
For technical reasons, or because it's a heap of work?

**Comment by dreadedhamish** [comment]
Also is it possible to overwrite a template for one particular page?
I'm primarily thinking about the home page, but there are specific custom post types I'd like to style distinctly.

**Comment by shprink** [comment]
You can style whatever you want by either modifying the CSS or by creating your own template. It is explained in the docs

**Comment by dreadedhamish** [comment]
Thanks.

Just so I'm sure I've read it correctly:

I can change the home page to a page.
I can style an individual page using CSS.
I cannot create a template for one specific page (only pages in general).

**Comment by dreadedhamish** [comment]
Could I get around this by creating a custom post type for my homepage?
And add additional custom post types for any other single pages that I want custom?

Being able to target specific pages with different templates would be great - that would make it possible for me to run my whole site (mobile and desktop) as a pwa without losing much of my desktop functionality.
