### ISSUE TITLE
Porting the project to Visual Studio

### ISSUE THREAD

**Issue by hamid-gh** [shprink/wordpress-hybrid-client#351]
How can I port this project to Visual Studio. Is it possible?
I want to use Visual Studio for editting and debugging the project.

**Comment by shprink** [comment]
Not sure what you are talking about. This is simply a Web project, open it with any IDE you want.

**Comment by hamid-gh** [comment]
Ok. Then, I Can open this project in Visual Studio 2015?
I didn't find .sln file in the project's folder.
