### ISSUE TITLE
Any plan to switch to lazy loading for v3?

### ISSUE THREAD

**Issue by VinceRafale** [shprink/wordpress-hybrid-client#396]
Not an issue just a quick question 

Any plan to switch to lazy loading for v3?

**Comment by shprink** [comment]
Do you mean page lazy loading?

**Comment by VinceRafale** [comment]
Not only pages but  components, pipes directives also
https://blog.ionicframework.com/ionic-and-lazy-loading-pt-1/
https://blog.ionicframework.com/ionic-and-lazy-loading-pt-2/

Looks like performances can really be improved

**Comment by shprink** [comment]
I use a lot of components created dynamically that's the reason I need all pages loaded at runtime. I spent some time trying to make it work but I failed. If you have the XP on this and want to contribute that would awesome otherwise it will stay like this.

Let me know. thanks
