### ISSUE TITLE
WP-API 2.x

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#45]
http://v2.wp-api.org/

**Comment by foxpcteam** [comment]
Hi,
are you going to add support for wp rest api v2?
i want to know if i can pull data from posts,page,custom post types,users,menus,metadata and etc..?

Thanks

**Comment by shprink** [comment]
Yes support for v2 is scheduled. I have already prepared the client lib for angular https://github.com/shprink/wp-api-angularjs. Just waiting for wp-api v2 to be released.
