### ISSUE TITLE
Ability to modify ionic configuration through config.json

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#55]
http://ionicframework.com/docs/api/provider/$ionicConfigProvider/

1. Create a new key in config.json named "ionicConfig"
1. Basically in index.coffee we need to map all config function that $ionicConfigProvider provides:

```
app.config ($WPHCConfig, $ionicConfigProvider) ->
    $ionicConfigProvider.views.maxCache _.get($WPHCConfig, 'ionicConfig.cache.views') || 10
    $ionicConfigProvider.views.forwardCache _.get($WPHCConfig, 'ionicConfig.cache.forward') || false
    $ionicConfigProvider.scrolling.jsScrolling _.get($WPHCConfig, 'ionicConfig.scrolling.jsScrolling') || false
    // MORE HERE
```

**Comment by mingxia** [comment]
I am busy something else, you do it. In addition “backButton.text(value) ” default is back, can according to language change?

**Comment by shprink** [comment]
+ translate back button

**Comment by shprink** [comment]
Done except translation the back button. Creating another issue just for it
