### ISSUE TITLE
some bugs v1.5.1

### ISSUE THREAD

**Issue by mingxia** [shprink/wordpress-hybrid-client#58]
I debug android on ubuntu, discovered the problem

1, share and bookmark button is disappeared.
2, category and tag button is cann't click
3, comments can't display.

**Comment by shprink** [comment]
Related to ionic/angular version. I am gonna check for a fix

**Comment by mingxia** [comment]
i use v1.5.2 , Well, there is no problem. ：）

**Comment by shprink** [comment]
angular 1.4 and ionic 1.1 will be updated on v1.6
