### ISSUE TITLE
Custom posts

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#60]

**Comment by mingxia** [comment]
will show post by post types？

**Comment by shprink** [comment]
Yes, display pages and custom posts list.

**Comment by chidinweke** [comment]
How about widgets...how do you display custom widget post.

**Comment by shprink** [comment]
What's a "custom widget post" @chidinweke ?

**Comment by chidinweke** [comment]
I meant Widget Post...Does it support Widget post.

**Comment by shprink** [comment]
WPHC does not support widgets and will not. I do not think widgets are in the scope of WP-API v2.

**Comment by chidinweke** [comment]
Does widget pose a security threat...to WPHC ?

**Comment by shprink** [comment]
As I explained WP-API v1 or v2 do not support widgets: http://wp-api.org/

**Comment by shprink** [comment]
Please follow #80 instead
