### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by zhouhao27** [shprink/wordpress-hybrid-client#61]
Do you support user registration/login?
Are there any sample application for this?

Thanks.

**Comment by shprink** [comment]
This is not supported at the moment. What would be the use case?

**Comment by zhouhao27** [comment]
I'm developing a mobile application (iOS/android):

1. User registration/login
2. Users are able to post photos and those photos can be commented by other users
3. Users are able to view news which are posted in CMS by admin
4. Users are able to view events which are posted in CMS by admin
5. Users are able to join the events
6. Server is able to push message to client to remind the user at the event date

Thanks

**Comment by shprink** [comment]
Ok I see thanks.

User login might be possible in WP-API v2 but not in v1 (do not want to develop anything for v1 anymore). If you want a timeline I would say end of 2015.

Good luck with your app
