### ISSUE TITLE
Custom Theming

### ISSUE THREAD

**Issue by ChrisHurrell** [shprink/wordpress-hybrid-client#62]
Great app but how do I customize the templating? Can you please include a basic how-to guide on using a different front-end template?

Thanks

**Comment by shprink** [comment]
Hi, so far basic ionic UI is used. You can overwrite any css or sass
variables in config.scss at the root of your project.
Templating is not a feature available yet so what you can do is directly
modify html files within lib folder.

**Comment by ChrisHurrell** [comment]
Hi and thanks for your reply. Nothing wrong with the ionic UI theme BTW, just my creative side that wants to hack everything. ;)

**Comment by shprink** [comment]
Built in v2.0.0 feature
