### ISSUE TITLE
Sub-Domain

### ISSUE THREAD

**Issue by chidinweke** [shprink/wordpress-hybrid-client#65]
Hello

Can sub-domain name be used. for example

hybrid.mydomain.com

**Comment by shprink** [comment]
You want to build a web mobile version of your website I am correct? This project is about building hybrid application (ios and android) not mobile version of your website (even though it is possible).

You can build the application and use whatever sub domain you want but features such as push notifications and sharing will not work. Up to you.

**Comment by chidinweke** [comment]
Thanks
