### ISSUE TITLE
Translate back button in Polish and Chinese

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#71]
Guys @mingxia @skibson I need your help on translating the Back button to your languages: https://github.com/shprink/wordpress-hybrid-client/commit/b55d5b5de7b674dd95aedb36bc3077f48810d194

Thanks :)

**Comment by skibson** [comment]
No problem. I will do it when I'll come back home 

Pozdrawiam, Michał Skibicki

Wysłano z TypeMail



W dniu 21 wrz 2015, 19:10, o 19:10, użytkownik Julien Renaux <notifications@github.com> napisał:

**Comment by mingxia** [comment]
should close this! :)

**Comment by shprink** [comment]
Still missing the polish translation for the back button: https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/translations/pl.json#L4

**Comment by mingxia** [comment]
I use the default Chinese, but sometimes the back button will occasionally (only a few) are displayed in English back, is not it I switch language, cache, and slow to change？

**Comment by shprink** [comment]
no idea @mingxia it will need more testing I guess

**Comment by mingxia** [comment]
This is just a very minor problem, does not affect the use, I'll pay attention.

**Comment by shprink** [comment]
Will create a more generic issue for translations in v2
