### ISSUE TITLE
Article title display bug and other v1.6.0 beta

### ISSUE THREAD

**Issue by mingxia** [shprink/wordpress-hybrid-client#73]
Sure is greatly improved, is progressing well, I have tested iOS9 app in the phone

Everything was smooth, but there is a problem:

1，Sometimes（May will be normal when open app ）, it will appear as shown, Navbar article title display dislocation.
![image1](https://cloud.githubusercontent.com/assets/12199412/10011255/0e31ef40-612a-11e5-8358-22791aa9f85f.PNG)

2，I still think it looks better  the original search box (containing the Clear button) layout.  O(∩_∩)O哈哈~

**Comment by shprink** [comment]
I have noticed that. For me it was only when I changed the language, it must be a ionic bug.

**Comment by mingxia** [comment]
Continue testing, and repeated use app, just started good, with the use of the wrong, the horizontal screen as well.

 it must be a ionic bug！

**Comment by shprink** [comment]
Closing this as it will not fix till next ionic release
