### ISSUE TITLE
Post title contains decimal

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#74]
title like this: "Gamer’s Life, son histoire" when retrieved from the webservice looks like this: ```Gamer&#8217;s Life, son histoire``` and is not properly displayed on the post header.

**Comment by shprink** [comment]
@SilentKernel

**Comment by shprink** [comment]
![image](https://cloud.githubusercontent.com/assets/1388706/10065769/6046471e-6250-11e5-8a37-f5f11f8a4384.png)

"Gamer’s Life" as a title work on my side:

![image](https://cloud.githubusercontent.com/assets/1388706/10065774/71d24cee-6250-11e5-97a5-2faaf1526772.png)

Which version are you using?

**Comment by SilentKernel** [comment]
Version 1.5.2 :)

**Comment by shprink** [comment]
@SilentKernel sorry I was talking about WP-API version.

**Comment by SilentKernel** [comment]
Ok, sorry i was not here for the last days

Version 1.2.3 of WP REST API

**Comment by shprink** [comment]
I am running the same version and "Gamer’s Life" as a title work for me. I am closing the issue cause I cannot reproduce it.

**Comment by alcholever** [comment]
This problem caused by REST API plug-in. 
![REST API](http://www.teknotik.org/github/Untitled.png)
