### ISSUE TITLE
cards resize when i pull to refresh

### ISSUE THREAD

**Issue by phipix01** [shprink/wordpress-hybrid-client#79]
when i pull down to refresh, the cards and their containing images and text in the post overview get bigger.

i'm on an Elephone P6000 with Android 5.0
![issue](https://cloud.githubusercontent.com/assets/1699734/10157407/2343682c-668a-11e5-95a3-32ed8691080c.png)

**Comment by shprink** [comment]
I also noticed that. I wonder if it is not a ionic bug with native scroll
