### ISSUE TITLE
Custom endpoints and routes

### ISSUE THREAD

**Issue by CoachBirgit** [shprink/wordpress-hybrid-client#80]
Hi Julian,

how it is possible to define / use custom endpoints and their routes?

Example: I´ll try to get the menu, realized with custom post types, in custom endpoints like fdm-menu and fdm-menu-item.

I am very new in .json and WP REST API, so how can I use these custom endpoints in WHC config.json? 

Our extending plugin on WP REST API v 1.x at this moment, but it can be ported to v2.x.

Thanks for your reply. 

Best regards,
Birgit

**Comment by shprink** [comment]
Custom post types are not supported in current versions #60 

What is a custom endpoint ?

**Comment by CoachBirgit** [comment]
You can define another Url-Format like "products" "team" "whatever-you-want" as an custom endpoint via plugin in WordPress to extend the regular API. Some plugins define own endpoints like WooCommerce etc. 

http://wp-api.org/guides/extending.html (v1)
http://v2.wp-api.org/extending/adding/ (v2)
http://torquemag.io/adding-custom-routes-wordpress-rest-api/

That´s the very best thing in WP REST API. In the upcoming merge into the core, the custom endpoints aren´t included, but in merge step 2. 

https://make.wordpress.org/core/2015/09/21/wp-rest-api-merge-proposal/

I guess, the WHC needs a dynamic call for custom post types and REST API endpoints.  

Another example: https://wptalents.com/about/api/ it brings an own endpoint `/api/talents` to deliver pre-defined content and routes.

**Comment by shprink** [comment]
Thanks for the explanation, I definitely want to support that but I need to find a solution for developers to create templates for custom posts first.

**Comment by shprink** [comment]
I am working on integrating custom posts and custom taxonomies on v2. The release is release close now

**Comment by shprink** [comment]
Done in v2. You have access to custom posts and taxonomies.
