### ISSUE TITLE
Content not updated

### ISSUE THREAD

**Issue by morsiiii** [shprink/wordpress-hybrid-client#81]
While im using Development (Web) or ios simulator content is not updating when I post new posts in my wordpress.

Plus @font-face not working with arabic fonts,

**Comment by shprink** [comment]
There is no live update. You can set the cache maxAge ```posts.cache.maxAge``` to be as low as possible so every time users get into the list page, the content will be refreshed. 
Also if you use push notifications, you will get new post notifications.

**Comment by morsiiii** [comment]
I tried to update to minimum value like 1 or 2 not working I don't mean live update but at least on daily basis or how its updated?

**Comment by shprink** [comment]
```posts.cache.maxAge``` works for me. Every time you open the app, the post list will be reloaded. Let's create a feature request to have "live" updates. It should not be complicated to add.

**Comment by morsiiii** [comment]
Yes thats will be awesome, PS i don't use it on final app just on browser and simulator.
Thanks dear
