### ISSUE TITLE
using @font-face error

### ISSUE THREAD

**Issue by morsiiii** [shprink/wordpress-hybrid-client#87]
when I try to change the font face family @ font.scss with another fonts in same dir its gives me an error:

./lib/font/NotoKufiArabic-Regular.woff2
Module parse failed: /Users/morsiiii/alwatan/app/lib/font/NotoKufiArabic-Regular.woff2 Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./lib/font/font.scss 6:914-956

./lib/font/NotoKufiArabic-Regular.woff
Module parse failed: /Users/morsiiii/alwatan/app/lib/font/NotoKufiArabic-Regular.woff Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./lib/font/font.scss 6:989-1029

./lib/font/NotoKufiArabic-Regular.ttf
Module parse failed: /Users/morsiiii/alwatan/app/lib/font/NotoKufiArabic-Regular.ttf Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./lib/font/font.scss 6:1061-1100

**Comment by morsiiii** [comment]
I added this line to module loader in webpack.config.js even its not working but its worked with me suddenly when i renamed my new fonts to Roboto.ttf etc and deleted the old ones

 {
            test: [/NotoKufiArabic-Regular\.ttf/, /NotoKufiArabic-Regular\.woff/, /NotoKufiArabic-Regular\.woff2/],
            loader: 'file?name=fonts/[name].[ext]'
        },

**Comment by maxlinux2000** [comment]
+1
I'm trying to change the fonts with a simple josefinsans.ttf (from google fonts), but nothing... I can't.

**Comment by maxlinux2000** [comment]
...as workaround you can use the css stylesheet directly in the index.html


```
<body ng-strict-di ng-app="wordpress-hybrid-client">
      <ion-nav-view></ion-nav-view>
        <script src="bundle-abcdefg.js"></script>

    <style>
        @font-face {
            font-family: 'JosefinSans';
            font-style: normal;
            font-weight: 400;
            src: local('Josefin Sans'), local('JosefinSans'), url(fonts/JosefinSans.ttf);     
        }
        @font-face {
            font-family: 'JustMeAgainDownHere';
            font-style: normal;
            font-weight: 400;
            src: local('JustMeAgainDownHere'), local('JustMeAgainDownHere'), url(fonts/JustMeAgainDownHere.ttf);     
        }        
                span.nav-bar-title {
            font-family: JosefinSans;
            font-size: 32px;        
        }
        ion-header-bar.bar-positive.bar.bar-header {
            font-family: JosefinSans;
            font-size: 32px;
        }
        h1.title.title-left {
            font-size: 30px !important;
        }  
wphc-posts .card {
    margin: 0 0 3px;
    cursor: pointer;
    box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.16), 0 0px 0px 0 rgba(0, 0, 0, 0.12);
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
}
p.xportada {
    padding-top: 2px;
}        
img.thumb {
    height: 110px;
}        
        ion-side-menus.pane.view {
            font-family: JosefinSans;
            font-size: 1.1em;     
        }        
        h1.item-title {
            font-family: JustMeAgainDownHere;
            font-size: 1.4em;
            font-weight: normal;
        }
        wphc-posts .card .item-image>h1 {
            position: absolute;
            color: #fff;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 20px;
            font-size: 2.1em;
            font-weight: normal;
            white-space: normal;
            text-shadow: 0 0 5px rgba(0,0,0,.3);
        }
        wphc-pages .card .item-image>h1 {
            position: absolute;
            color: #fff;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 20px;
            font-size: 1.8em;
            font-weight: normal;
            white-space: normal;
            text-shadow: 0 0 5px rgba(0,0,0,.3);
        }        
        wphc-author {
            font-family: JosefinSans;    
        }
        .item.item-text-wrap {
            font-family: JosefinSans;
        }
        .post-content {
            font-family: JosefinSans;
            font-size: 1.1em;     
        } 
        a.button.button-positive.button-open-browser.activated {
            display: none;
        }
        a.button.button-positive.button-open-browser {
            display: none;
        }
    </style>        
</body>

```

in this example I suppose that you put the .ttf fonts in the www/fonts folder, but I think that is possible to use the link to a webfonts like google fonts.

ciao
MaX
