### ISSUE TITLE
Displaying pages

### ISSUE THREAD

**Issue by gkodikara** [shprink/wordpress-hybrid-client#88]
Hi there,

How do I add specific, singular pages to the menu?

Thanks for any help.

Greg

**Comment by shprink** [comment]
It is not possible with the versions up to 1.6.

It is possible on develop with the new WP-API v2.beta4:

```
{
                "type": "internal",
                "trans": "Page id:1",
                "route": "public.pages.id({ id: 1 })",
                "icon": "icon ion-android-document"
            }
```

Please note that the develop branch is under a lot of changes.

Closing, #86 already exist

**Comment by AcquireLearning** [comment]
@shprink ok - thank you. But how do we point to pages that are named logically?

**Comment by shprink** [comment]
As far as I know the ID is the only way to get a unique page.

BTW: v2 is under wip/v2 branch now.
