### ISSUE TITLE
Adding native transitions

### ISSUE THREAD

**Issue by shprink** [shprink/wordpress-hybrid-client#91]

**Comment by mingxia** [comment]
I have seen the ionic-native-transitions, very much looking forward, very nice

**Comment by shprink** [comment]
@mingxia I might just include that into 1.7 and make a release if it is not too much work. Otherwise it will be included in 2.0

**Comment by mingxia** [comment]
I have tested on the iphone, no problem. Page switching works well.

**Comment by shprink** [comment]
Have not tested on iOS yet, will do soon as well. Thanks
