### ISSUE TITLE
White page showing after splash screen before app load

### ISSUE THREAD

**Issue by mingxia** [shprink/wordpress-hybrid-client#92]
I have encountered this problem on ios app, today I use v1.7.0 development process, found a solution:

Add two lines In config.xml file to solve:
```
<preference name = "ShowSplashScreenSpinner" value = "false" />
<preference name = "AutoHideSplashScreen" value = "false" />
```
Reference Address: 

http://forum.ionicframework.com/t/white-page-showing-after-splash-screen-before-app-load/2908/5

**Comment by shprink** [comment]
good job @mingxia !

**Comment by yogeshpatil143** [comment]
Yes it's working also in my app for same problem
