### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by morsiiii** [shprink/wordpress-hybrid-client#93]
Pull to refresh is never updates or refresh content 1.7 , 1.6 and 2
what the problem ?

**Comment by shprink** [comment]
Yeah you are right, the PTR gets the first page from the cache if exist. 

the PTR will work if you set a low cache time in the config.json file: `posts.cache.maxAge` 

I am planning to fix that in 1.7.1, stay tuned.

**Comment by morsiiii** [comment]
thank you,  can you give me exactly which line i can find this?

**Comment by shprink** [comment]
In you `config.json` file: https://github.com/shprink/wordpress-hybrid-client/blob/develop/config.json.dist#L155

It is currently set to 1 day (86400000 ms). If you set that to 0 the PTR will get fresh data everytime. If you set to 2 mins then every 2min the PTR will pull new data.

**Comment by morsiiii** [comment]
i already set them to 
          "capacity": 0,
            "maxAge": 0
without any new
 i also removed :
        "orderby": "date",
        "orderby": "desc",

to bring last posts when intializing the app before i delete this values was brings very old posts  and ignores any new posts

**Comment by shprink** [comment]
Actually i have just tested it is working as expected even with the cache set to one day.

You can check the code here https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/posts/posts.controller.coffee#L34-L40

What it does is to remove the cache, then remove posts and ask for the first page once again. I have tested locally with a new post and it is correctly displayed after PTR.

**Comment by morsiiii** [comment]
yes sorry i doubled checked with new posts and the category pages was updating now
but the home or recent posts is not updating does its only refresh on app loading.

**Comment by shprink** [comment]
There is no PTR on category and tag list because the list is unlikely to be changed often. The cache is set to 2 days: https://github.com/shprink/wordpress-hybrid-client/blob/develop/config.json.dist#L145

The PTR is only on the home page and search page (until 1.7.0) and work as expected. Have not tested on 2.0 yet, this branch is not stable so please do not use it in production.
