### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by guschaves** [shprink/wordpress-hybrid-client#98]
I don't know how to fix it, I did all the steps in the documentation, but I couldn't build the app or execute the command run runAndroid.
Can you help me?
![printscreen - 29-10-2015 - 13 56 28](https://cloud.githubusercontent.com/assets/7849140/10830409/391da856-7e5e-11e5-8c92-2aae2f9966cd.png)

**Comment by shprink** [comment]
ANDROID_HOME needs to be defined.

https://www.airpair.com/javascript/posts/a-year-using-ionic-to-build-hybrid-applications#android

**Comment by guschaves** [comment]
I followed your guide, but it doesn't work. 
It's strange, cause if I execute the command "android" it opens the Android SDK.
I'm really confused

**Comment by shprink** [comment]
Check if it is set using:

```
15:36 $ echo $ANDROID_HOME
/Users/shprink/Library/Android/sdk
```

**Comment by guschaves** [comment]
It shows 

/home/gustavo/android-sdk-linux

**Comment by shprink** [comment]
That's good. Do you still have this error? Have you changed the paths inside release.sh?

**Comment by guschaves** [comment]
Yes the error still happens.
About the release.sh, I did change, can I paste it here for you to check?

**Comment by shprink** [comment]
A chat is better to talk. I invite you to join gitter: https://gitter.im/shprink/wordpress-hybrid-client
